# Bagging Regressor with Decision Trees

__INDEX__
1. [Bagging with Decision Trees](#bagging_dt) <br>
       1.1. [About Bagging and Decision Trees](#about) <br>
       1.2. [BaggingRegressor with DecisionTreeRegressor in Scikit-learn](#scikit) <br>
       1.3. [Why We Use Bagging + Decision Trees in This Project](#project) <br>

2. [Setup and Data Preparation](#setup)

3. [Experimental Runs](#expruns) <br>
       3.1. [Baseline Bagging Model (Preprocessed Data Only)](#baseline) <br>
       3.2. [Baseline Bagging Model with Feature Selection](#baselinefs) <br>
       3.3. [Impact of Removing Previous Owners](#noprevious) <br>
       3.4. [Bagging with Feature Engineering (No Feature Selection)](#fe_nofs) <br>
       3.5. [Effect of Hyperparameter Tuning on Bias and Overfitting](#bias_overfit) <br>

4. [Final Configuration and Best Model Selection](#finalconfig)

5. [Model Evaluation, Stability Analysis, and Final Remarks](#visualization)

## 1. Bagging with Decision Trees
<a id="bagging_dt"></a>

### 1.1. About Bagging and Decision Trees
<a id="about"></a>

Bagging (Bootstrap Aggregating) is an ensemble learning technique designed to improve the stability and generalization performance of high-variance models. The core idea consists of training multiple base learners on different bootstrap samples of the training data and aggregating their predictions, typically through averaging in regression tasks.

Decision Trees are particularly well-suited as base estimators for Bagging. While individual trees are powerful and able to capture complex non-linear relationships, they are also highly sensitive to small changes in the training data. This instability makes them prone to overfitting but, at the same time, ideal candidates for variance reduction through ensembling.

Decision Trees naturally handle feature interactions and non-linear splits, while Bagging mitigates their tendency to overfit by averaging multiple diversified trees.

As a result, Bagging with Decision Trees provides a strong and interpretable non-linear baseline that balances model expressiveness and robustness.

### 1.2. BaggingRegressor with DecisionTreeRegressor in Scikit-learn
<a id="scikit"></a>

Scikit-learn offers a flexible implementation of Bagging through the BaggingRegressor class, which allows any regressor to be used as the base estimator. In this project, we combine BaggingRegressor with DecisionTreeRegressor to explicitly control both ensemble-level and tree-level complexity.

At the ensemble level, we tune parameters such as:

    - the number of trees (n_estimators);
    - the proportion of samples used per tree (max_samples);
    - the proportion of features considered by each estimator (max_features).

At the base tree level, we control:

    - the maximum depth of each tree;
    - the minimum number of samples required to split a node;
    - the minimum number of samples in leaf nodes.

Bagging trains all trees independently and in parallel, which improves training stability and reduces sensitivity to noise. Furthermore, this setup allows us to explicitly study the bias–variance trade-off by adjusting tree depth and ensemble size.

### 1.3. Why We Use Bagging + Decision Trees in This Project

<a id="project"></a>

We include Bagging with Decision Trees as a core model in our experimental framework for several reasons:

- This approach serves as a strong non-linear benchmark that does not rely on gradient-based optimization or assumptions about feature distributions. Trees naturally handle feature interactions and non-monotonic effects, which are common in vehicle pricing.

- Bagging allows us to reduce overfitting without aggressively restricting individual trees. Instead of simplifying the model too early, we allow trees to be expressive and rely on aggregation to stabilize predictions across different bootstrap samples.

- Compared to more complex ensemble methods such as Gradient Boosting, Bagging is easier to interpret in terms of bias–variance behavior and less sensitive to noise in the target variable. This makes it particularly suitable for datasets where pricing may include inconsistencies, outliers, or unobserved factors.

- Bagging provides an excellent reference point to assess whether more sophisticated models actually deliver meaningful improvements over a well-regularized ensemble of decision trees.

## 2. Setup and Preparation
<a id="setup"></a>

In [10]:
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold, ParameterSampler
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import BaggingRegressor
from sklearn.feature_selection import SelectFromModel
from sklearn.tree import DecisionTreeRegressor
import random
import logging
import os
from sklearn.model_selection import ParameterSampler, KFold
from sklearn.metrics import (
    mean_squared_error, mean_absolute_error, median_absolute_error,
    mean_absolute_percentage_error, r2_score
)
from sklearn.ensemble import RandomForestRegressor

In [11]:
def rmse(y_true, y_pred) -> float:
    return float(np.sqrt(mean_squared_error(y_true, y_pred)))

def bias(y_true, y_pred) -> float:
    return float(np.mean(np.asarray(y_true) - np.asarray(y_pred)))

def get_random_configs(n_iter: int):
    configs = []
    keys = list(param_distributions.keys())

    for i in range(n_iter):
        params = {k: random.choice(list(param_distributions[k])) for k in keys}

        name = (
            f"R{i}"
            f"_n{params['n_estimators']}"
            f"_ms{params['max_samples']}"
            f"_mf{params['max_features']}"
            f"_d{params['tree_max_depth']}"
            f"_leaf{params['tree_min_samples_leaf']}"
            f"_split{params['tree_min_samples_split']}"
        )

        configs.append((name, params))

    return configs

In [12]:
# All of our preprocessing helper functions are in this notebook
%run 05_0_preproc_helpers.ipynb  

# this is the target column - the value we want to predict 
TARGET_COL = "price"  

# separate features and target variable from the full training datase
y = full_train_dataset[TARGET_COL].copy()
X = full_train_dataset.drop(columns=[TARGET_COL]).copy()

# lists previously defined in 05_0_preproc_helpers.ipynb
numeric_features = num_feat                      # ['year', 'mileage', ...]
categorical_features = cat_feat                  # ['Brand', 'model', 'transmission', 'fuelType']

print("X shape:", X.shape)
print("y shape:", y.shape)
print("Num features:", numeric_features)
print("Cat features:", categorical_features)

N_SPLITS = 5 # the number of folds for K-Fold cross-validation
RANDOM_STATE = 42 # seed to control randomness

X shape: (75973, 10)
y shape: (75973,)
Num features: ['year', 'mileage', 'engineSize', 'tax', 'mpg', 'previousOwners']
Cat features: ['Brand', 'model', 'transmission', 'fuelType']

### 3.1 modelo normal features todas sem fs nem fe <br>

In [13]:

# K-FOLD CROSS-VALIDATION

# The data is shuffled before splitting to ensure that, at least theoretically, each fold is more balanced and
# representative of the full dataset distribution.
kf = KFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)



# HYPERPARAMETER SPACE FOR RANDOM SEARCH

# Each random configuration will sample exactly one value
# from each list below.
# The parameters are divided into:
#  - ensemble-level (Bagging)
#  - base estimator-level (Decision Tree)
param_distributions = {

    # Bagging (ensemble-level)
    
    # Number of trees in the ensemble.
    # Higher values usually improve stability but increase training time.
    "n_estimators": [400,1000,1200],

    # Fraction of samples used to train each tree.
    # Values < 1.0 increase diversity between estimators.
    "max_samples": [0.5, 1.0],

    # Fraction of features used by each estimator.
    # This helps reduce correlation between trees.
    "max_features": [0.8, 0.9],

    
    # Decision Tree (base model)
    
    # Maximum depth of each decision tree.
    "tree_max_depth": [15, 25],

    # Minimum number of samples required at a leaf node.
    # Larger values increase regularization.
    "tree_min_samples_leaf": [1, 5],

    # Minimum number of samples required to split an internal node.
    "tree_min_samples_split": [10, 30]
}

# Number of random configurations to evaluate.
# This is intentionally small, as this run is intended
# to provide baseline and comparative results.
N_RANDOM_CONFIGS = 15



# RANDOM SAMPLER

# Randomly samples N_RANDOM_CONFIGS combinations from the hyperparameter space defined above.
sampler = ParameterSampler(
    param_distributions,
    n_iter=N_RANDOM_CONFIGS,
    random_state=RANDOM_STATE
)

# List to store results for each configuration
search_results = []

# Track the best configuration according to validation RMSE
best_rmse = np.inf
best_config = None



# LOGGING SETUP

# All logs are written both to the console and to a file for reproducibility and later inspection.
log_path = "Bagging_DT_complete_random_search.txt"

with open(log_path, "w", encoding="utf-8") as log_file:

    # Helper logging function
    def log(msg: str):
        print(msg)
        log_file.write(msg + "\n")
        log_file.flush()

    # Log header
    log("# =============================")
    log("# START OF BAGGING + DECISION TREE SEARCH")
    log("# DETAILED METRICS: R2, RMSE, MAE, BIAS")
    log(f"# LOG FILE SAVED TO: {log_path}")
    log("# =============================")

    
    # RANDOM SEARCH LOOP
    
    for config_id, params in enumerate(sampler, start=1):
        log("")
        log(f"######## CONFIG {config_id}/{N_RANDOM_CONFIGS} ########")
        log(f"Parameters: {params}")

        # Containers for fold-level metrics
        fold_rmses_val, fold_maes_val, fold_r2s_val, fold_bias_val = [], [], [], []
        fold_rmses_tr, fold_maes_tr, fold_r2s_tr, fold_bias_tr = [], [], [], []
        fold_med_ae = []

        
        # K-FOLD CROSS-VALIDATION
        
        for fold, (train_idx, val_idx) in enumerate(kf.split(X), start=1):

            # Split data into training and validation sets
            X_train, X_val = X.iloc[train_idx].copy(), X.iloc[val_idx].copy()
            y_train, y_val = y.iloc[train_idx].copy(), y.iloc[val_idx].copy()

            log(f"\n[C{config_id}|F{fold}] Processing fold...")

            
            # PREPROCESSING PIPELINE
        
            # All transformations are fit ONLY on the training data
            # and then applied to both training and validation sets.

            year_state = fit_year_median(X_train, year_col="year", model_col="model")
            X_train = transform_year_with_model_median(X_train, state=year_state)
            X_val   = transform_year_with_model_median(X_val,   state=year_state)

            mileage_state = fit_mileage_imputer(X_train, mileage_col="mileage", do_abs=True)
            X_train = transform_mileage_imputer(X_train, state=mileage_state)
            X_val   = transform_mileage_imputer(X_val,   state=mileage_state)

            engine_state = fit_engine_size_imputer(X_train, engine_col="engineSize")
            X_train = transform_engine_size_imputer(X_train, state=engine_state)
            X_val   = transform_engine_size_imputer(X_val,   state=engine_state)

            X_train = transform_tax_custom_rules(X_train, "tax", "year", "fuelType", "engineSize")
            X_val   = transform_tax_custom_rules(X_val, "tax", "year", "fuelType", "engineSize")

            mpg_state = fit_mpg_imputer(X_train, mpg_col="mpg", do_abs=True)
            X_train = transform_mpg_imputer(X_train, state=mpg_state)
            X_val   = transform_mpg_imputer(X_val,   state=mpg_state)

            owners_state = fit_previous_owners_imputer(X_train, "previousOwners", "year", "mileage")
            X_train = transform_previous_owners_imputer(X_train, state=owners_state)
            X_val   = transform_previous_owners_imputer(X_val,   state=owners_state)

            brand_state = fit_ambiguous_brand_resolver(X_train, valid_brands)
            X_train, _, _ = transform_ambiguous_brands(X_train, brand_state)
            X_val, _, _   = transform_ambiguous_brands(X_val, brand_state)

            model_state = fit_invalid_model_resolver(X_train, valid_models_by_brand)
            X_train, _, _ = transform_invalid_models(X_train, model_state)
            X_val, _, _   = transform_invalid_models(X_val, model_state)

            transm_state = fit_transmission_resolver(X_train, valid_transmissions)
            X_train, _, _ = transform_transmission_resolver(X_train, transm_state)
            X_val, _, _   = transform_transmission_resolver(X_val, transm_state)

            fuel_state = fit_fueltype_resolver(X_train, valid_fueltypes)
            X_train, _, _ = transform_fueltype_resolver(X_train, fuel_state)
            X_val, _, _   = transform_fueltype_resolver(X_val, fuel_state)


            # FEATURE ENCODING

            # High-cardinality features use target encoding,
            # low-cardinality features use one-hot encoding.
            high_card_features = ["Brand", "model"]
            low_card_features  = [c for c in categorical_features if c not in high_card_features]

            te = MyTargetEncoder(smoothing=5)
            te.fit(X_train[high_card_features], y_train)
            X_train_high = te.transform(X_train[high_card_features])
            X_val_high   = te.transform(X_val[high_card_features])

            ohe = MyOneHotEncoder()
            ohe.fit(X_train[low_card_features])
            X_train_low = ohe.transform(X_train[low_card_features])
            X_val_low   = ohe.transform(X_val[low_card_features])

            X_train_cat = pd.concat([X_train_high, X_train_low], axis=1)
            X_val_cat   = pd.concat([X_val_high,   X_val_low],   axis=1)

            # Combine numerical and encoded categorical features
            X_train_final = pd.concat([X_train[numeric_features], X_train_cat], axis=1)
            X_val_final   = pd.concat([X_val[numeric_features],   X_val_cat],   axis=1)

            
            # FEATURE SCALING
            
            # Although tree-based models do not strictly require scaling,
            # we apply StandardScaler for numerical stability and
            # consistency across models.
            scaler = StandardScaler()
            X_train_scaled = scaler.fit_transform(X_train_final)
            X_val_scaled   = scaler.transform(X_val_final)

            if fold == 1:
                feature_names = list(X_train_final.columns)
                log(f"  > Features Used ({len(feature_names)}): {feature_names}")

            
            # MODEL DEFINITION
            
            base_tree = DecisionTreeRegressor(
                max_depth=params["tree_max_depth"],
                min_samples_leaf=params["tree_min_samples_leaf"],
                min_samples_split=params["tree_min_samples_split"],
                random_state=RANDOM_STATE
            )

            model = BaggingRegressor(
                estimator=base_tree,
                n_estimators=params["n_estimators"],
                max_samples=params["max_samples"],
                max_features=params["max_features"],
                random_state=RANDOM_STATE,
                n_jobs=-1
            )

            # Train the model
            model.fit(X_train_scaled, y_train)

            
            # PREDICTIONS

            y_pred_train = model.predict(X_train_scaled)
            y_pred_val   = model.predict(X_val_scaled)


            
            # METRICS
            
            mae_tr = mean_absolute_error(y_train, y_pred_train)
            rmse_tr = np.sqrt(mean_squared_error(y_train, y_pred_train))
            r2_tr = r2_score(y_train, y_pred_train)
            bias_tr = np.mean(y_train - y_pred_train)

            mae_val = mean_absolute_error(y_val, y_pred_val)
            rmse_val = np.sqrt(mean_squared_error(y_val, y_pred_val))
            r2_val = r2_score(y_val, y_pred_val)
            bias_val = np.mean(y_val - y_pred_val)
            med_ae_val = median_absolute_error(y_val, y_pred_val)

            log(f"  > [TRAIN] R2: {r2_tr:.4f} | RMSE: {rmse_tr:.0f} | MAE: {mae_tr:.0f} | Bias: {bias_tr:.1f}")
            log(f"  > [VAL]   R2: {r2_val:.4f} | RMSE: {rmse_val:.0f} | MAE: {mae_val:.0f} | Bias: {bias_val:.1f}")

            fold_maes_tr.append(mae_tr)
            fold_rmses_tr.append(rmse_tr)
            fold_r2s_tr.append(r2_tr)
            fold_bias_tr.append(bias_tr)

            fold_maes_val.append(mae_val)
            fold_rmses_val.append(rmse_val)
            fold_r2s_val.append(r2_val)
            fold_bias_val.append(bias_val)
            fold_med_ae.append(med_ae_val)

        
        # AGGREGATED RESULTS
        
        mean_rmse_val = np.mean(fold_rmses_val)
        mean_mae_val  = np.mean(fold_maes_val)
        mean_r2_val   = np.mean(fold_r2s_val)
        mean_bias_val = np.mean(fold_bias_val)

        mean_mae_tr   = np.mean(fold_maes_tr)
        mean_r2_tr    = np.mean(fold_r2s_tr)
        mean_bias_tr  = np.mean(fold_bias_tr)

        log("")
        log(f"Config {config_id} SUMMARY:")
        log(f"  [TRAIN AVG] MAE: {mean_mae_tr:.1f} | R2: {mean_r2_tr:.4f} | Bias: {mean_bias_tr:.1f}")
        log(f"  [VAL AVG]   MAE: {mean_mae_val:.1f} | R2: {mean_r2_val:.4f} | Bias: {mean_bias_val:.1f} | RMSE: {mean_rmse_val:.1f}")

        search_results.append({
            "config_id": config_id,
            **params,
            "val_rmse": mean_rmse_val,
            "val_mae": mean_mae_val,
            "val_r2": mean_r2_val,
            "val_bias": mean_bias_val,
            "train_mae": mean_mae_tr,
            "train_r2": mean_r2_tr,
            "train_bias": mean_bias_tr,
            "val_med_ae": np.mean(fold_med_ae)
        })

        if mean_rmse_val < best_rmse:
            best_rmse = mean_rmse_val
            best_config = {**params}
            log(f"[NEW BEST RMSE] Config {config_id}")

    log("# END OF SEARCH")



# FINAL RESULTS

results_df = pd.DataFrame(search_results)
results_df_sorted = results_df.sort_values(by="val_rmse", ascending=True)

print("\nTop 5 Configurations by RMSE:")
cols = ["n_estimators", "max_samples", "max_features", "tree_max_depth", "tree_min_samples_leaf", "tree_min_samples_split", "val_rmse", "val_mae", "val_r2", "train_r2", "val_bias"]
display(results_df_sorted[cols].head(5))

print("\nBest Config found:")
print(best_config)

# =============================
# START OF BAGGING + DECISION TREE SEARCH
# DETAILED METRICS: R2, RMSE, MAE, BIAS
# LOG FILE SAVED TO: Bagging_DT_complete_random_search.txt
# =============================

######## CONFIG 1/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 1, 'tree_max_depth': 15, 'n_estimators': 1000, 'max_samples': 1.0, 'max_features': 0.9}

[C1|F1] Processing fold...
  > Features Used (16): ['year', 'mileage', 'engineSize', 'tax', 'mpg', 'previousOwners', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9702 | RMSE: 1688 | MAE: 1051 | Bias: -1.9
  > [VAL]   R2: 0.9507 | RMSE: 2118 | MAE: 1328 | Bias: -30.4

[C1|F2] Processing fold...
  > [TRAIN] R2: 0.9701 | RMSE: 1684 | MAE: 1037 | Bias: -1.6
  > [VAL]   R2: 0.9459 | RMSE: 2263 | MAE: 1336 | Bias: 15.1

[C1|F3] Processing fold...
  > [TRAIN] R2: 0.9716 | RMSE: 1627 | MAE: 1038 | Bias: -0.9
  > [VAL]   R2: 0.9322 | RMSE: 2617 | MAE: 1355 | Bias: 22.2

[C1|F4] Processing fold...
  > [TRAIN] R2: 0.9691 | RMSE: 1708 | MAE: 1050 | Bias: -1.3
  > [VAL]   R2: 0.9475 | RMSE: 2255 | MAE: 1320 | Bias: 19.0

[C1|F5] Processing fold...
  > [TRAIN] R2: 0.9703 | RMSE: 1688 | MAE: 1050 | Bias: -1.7
  > [VAL]   R2: 0.9526 | RMSE: 2071 | MAE: 1286 | Bias: -26.8

Config 1 SUMMARY:
  [TRAIN AVG] MAE: 1045.3 | R2: 0.9703 | Bias: -1.5
  [VAL AVG]   MAE: 1325.0 | R2: 0.9458 | Bias: -0.1 | RMSE: 2264.6
[NEW BEST RMSE] Config 1

######## CONFIG 2/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 1, 'tree_max_depth': 25, 'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.9}

[C2|F1] Processing fold...
  > Features Used (16): ['year', 'mileage', 'engineSize', 'tax', 'mpg', 'previousOwners', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9589 | RMSE: 1984 | MAE: 1139 | Bias: -1.4
  > [VAL]   R2: 0.9475 | RMSE: 2186 | MAE: 1354 | Bias: -31.9

[C2|F2] Processing fold...
  > [TRAIN] R2: 0.9603 | RMSE: 1941 | MAE: 1132 | Bias: 0.1
  > [VAL]   R2: 0.9407 | RMSE: 2368 | MAE: 1362 | Bias: 20.1

[C2|F3] Processing fold...
  > [TRAIN] R2: 0.9611 | RMSE: 1905 | MAE: 1129 | Bias: 1.1
  > [VAL]   R2: 0.9276 | RMSE: 2703 | MAE: 1381 | Bias: 30.5

[C2|F4] Processing fold...
  > [TRAIN] R2: 0.9596 | RMSE: 1952 | MAE: 1139 | Bias: -1.0
  > [VAL]   R2: 0.9407 | RMSE: 2398 | MAE: 1349 | Bias: 24.8

[C2|F5] Processing fold...
  > [TRAIN] R2: 0.9594 | RMSE: 1973 | MAE: 1138 | Bias: -0.1
  > [VAL]   R2: 0.9493 | RMSE: 2142 | MAE: 1313 | Bias: -28.3

Config 2 SUMMARY:
  [TRAIN AVG] MAE: 1135.3 | R2: 0.9599 | Bias: -0.3
  [VAL AVG]   MAE: 1351.9 | R2: 0.9412 | Bias: 3.0 | RMSE: 2359.5

######## CONFIG 3/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 1, 'tree_max_depth': 15, 'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.9}

[C3|F1] Processing fold...
  > Features Used (16): ['year', 'mileage', 'engineSize', 'tax', 'mpg', 'previousOwners', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9556 | RMSE: 2061 | MAE: 1210 | Bias: -0.3
  > [VAL]   R2: 0.9462 | RMSE: 2214 | MAE: 1380 | Bias: -29.7

[C3|F2] Processing fold...
  > [TRAIN] R2: 0.9574 | RMSE: 2010 | MAE: 1196 | Bias: 1.2
  > [VAL]   R2: 0.9396 | RMSE: 2390 | MAE: 1387 | Bias: 21.1

[C3|F3] Processing fold...
  > [TRAIN] R2: 0.9580 | RMSE: 1980 | MAE: 1196 | Bias: 2.2
  > [VAL]   R2: 0.9265 | RMSE: 2723 | MAE: 1408 | Bias: 31.8

[C3|F4] Processing fold...
  > [TRAIN] R2: 0.9565 | RMSE: 2026 | MAE: 1208 | Bias: 0.0
  > [VAL]   R2: 0.9395 | RMSE: 2421 | MAE: 1375 | Bias: 25.5

[C3|F5] Processing fold...
  > [TRAIN] R2: 0.9564 | RMSE: 2046 | MAE: 1206 | Bias: 1.1
  > [VAL]   R2: 0.9481 | RMSE: 2167 | MAE: 1339 | Bias: -25.9

Config 3 SUMMARY:
  [TRAIN AVG] MAE: 1203.3 | R2: 0.9568 | Bias: 0.8
  [VAL AVG]   MAE: 1377.6 | R2: 0.9400 | Bias: 4.6 | RMSE: 2383.0

######## CONFIG 4/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 5, 'tree_max_depth': 25, 'n_estimators': 1200, 'max_samples': 1.0, 'max_features': 0.9}

[C4|F1] Processing fold...
  > Features Used (16): ['year', 'mileage', 'engineSize', 'tax', 'mpg', 'previousOwners', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9648 | RMSE: 1835 | MAE: 1021 | Bias: -1.7
  > [VAL]   R2: 0.9489 | RMSE: 2156 | MAE: 1332 | Bias: -29.6

[C4|F2] Processing fold...
  > [TRAIN] R2: 0.9653 | RMSE: 1815 | MAE: 1015 | Bias: -0.9
  > [VAL]   R2: 0.9427 | RMSE: 2329 | MAE: 1336 | Bias: 19.2

[C4|F3] Processing fold...
  > [TRAIN] R2: 0.9672 | RMSE: 1748 | MAE: 1011 | Bias: -0.3
  > [VAL]   R2: 0.9273 | RMSE: 2710 | MAE: 1362 | Bias: 30.7

[C4|F4] Processing fold...
  > [TRAIN] R2: 0.9646 | RMSE: 1826 | MAE: 1021 | Bias: -1.0
  > [VAL]   R2: 0.9430 | RMSE: 2351 | MAE: 1324 | Bias: 19.0

[C4|F5] Processing fold...
  > [TRAIN] R2: 0.9644 | RMSE: 1847 | MAE: 1022 | Bias: -0.3
  > [VAL]   R2: 0.9509 | RMSE: 2108 | MAE: 1290 | Bias: -21.0

Config 4 SUMMARY:
  [TRAIN AVG] MAE: 1018.2 | R2: 0.9653 | Bias: -0.8
  [VAL AVG]   MAE: 1328.7 | R2: 0.9425 | Bias: 3.7 | RMSE: 2330.8

######## CONFIG 5/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 1, 'tree_max_depth': 15, 'n_estimators': 1000, 'max_samples': 1.0, 'max_features': 0.8}

[C5|F1] Processing fold...
  > Features Used (16): ['year', 'mileage', 'engineSize', 'tax', 'mpg', 'previousOwners', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9547 | RMSE: 2081 | MAE: 1236 | Bias: -0.6
  > [VAL]   R2: 0.9460 | RMSE: 2217 | MAE: 1393 | Bias: -33.6

[C5|F2] Processing fold...
  > [TRAIN] R2: 0.9560 | RMSE: 2044 | MAE: 1224 | Bias: -0.3
  > [VAL]   R2: 0.9399 | RMSE: 2384 | MAE: 1401 | Bias: 19.7

[C5|F3] Processing fold...
  > [TRAIN] R2: 0.9569 | RMSE: 2005 | MAE: 1223 | Bias: 0.7
  > [VAL]   R2: 0.9254 | RMSE: 2745 | MAE: 1417 | Bias: 29.8

[C5|F4] Processing fold...
  > [TRAIN] R2: 0.9552 | RMSE: 2054 | MAE: 1235 | Bias: 0.2
  > [VAL]   R2: 0.9383 | RMSE: 2445 | MAE: 1388 | Bias: 24.5

[C5|F5] Processing fold...
  > [TRAIN] R2: 0.9549 | RMSE: 2081 | MAE: 1233 | Bias: 0.2
  > [VAL]   R2: 0.9474 | RMSE: 2182 | MAE: 1358 | Bias: -30.2

Config 5 SUMMARY:
  [TRAIN AVG] MAE: 1230.1 | R2: 0.9555 | Bias: 0.0
  [VAL AVG]   MAE: 1391.3 | R2: 0.9394 | Bias: 2.0 | RMSE: 2394.6

######## CONFIG 6/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 5, 'tree_max_depth': 25, 'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.9}

[C6|F1] Processing fold...
  > Features Used (16): ['year', 'mileage', 'engineSize', 'tax', 'mpg', 'previousOwners', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9524 | RMSE: 2136 | MAE: 1195 | Bias: -0.5
  > [VAL]   R2: 0.9454 | RMSE: 2230 | MAE: 1377 | Bias: -28.6

[C6|F2] Processing fold...
  > [TRAIN] R2: 0.9540 | RMSE: 2089 | MAE: 1188 | Bias: 1.9
  > [VAL]   R2: 0.9381 | RMSE: 2419 | MAE: 1382 | Bias: 23.5

[C6|F3] Processing fold...
  > [TRAIN] R2: 0.9553 | RMSE: 2043 | MAE: 1184 | Bias: 2.5
  > [VAL]   R2: 0.9228 | RMSE: 2791 | MAE: 1406 | Bias: 35.8

[C6|F4] Processing fold...
  > [TRAIN] R2: 0.9532 | RMSE: 2100 | MAE: 1195 | Bias: 0.3
  > [VAL]   R2: 0.9375 | RMSE: 2461 | MAE: 1370 | Bias: 24.3

[C6|F5] Processing fold...
  > [TRAIN] R2: 0.9525 | RMSE: 2133 | MAE: 1196 | Bias: 1.9
  > [VAL]   R2: 0.9473 | RMSE: 2183 | MAE: 1335 | Bias: -21.7

Config 6 SUMMARY:
  [TRAIN AVG] MAE: 1191.4 | R2: 0.9535 | Bias: 1.2
  [VAL AVG]   MAE: 1373.9 | R2: 0.9382 | Bias: 6.6 | RMSE: 2416.9

######## CONFIG 7/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 1, 'tree_max_depth': 25, 'n_estimators': 1200, 'max_samples': 0.5, 'max_features': 0.9}

[C7|F1] Processing fold...
  > Features Used (16): ['year', 'mileage', 'engineSize', 'tax', 'mpg', 'previousOwners', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9494 | RMSE: 2202 | MAE: 1263 | Bias: -0.4
  > [VAL]   R2: 0.9432 | RMSE: 2275 | MAE: 1411 | Bias: -35.3

[C7|F2] Processing fold...
  > [TRAIN] R2: 0.9506 | RMSE: 2165 | MAE: 1256 | Bias: -0.1
  > [VAL]   R2: 0.9359 | RMSE: 2463 | MAE: 1413 | Bias: 17.1

[C7|F3] Processing fold...
  > [TRAIN] R2: 0.9519 | RMSE: 2118 | MAE: 1251 | Bias: 1.3
  > [VAL]   R2: 0.9218 | RMSE: 2809 | MAE: 1436 | Bias: 36.3

[C7|F4] Processing fold...
  > [TRAIN] R2: 0.9502 | RMSE: 2166 | MAE: 1263 | Bias: -0.2
  > [VAL]   R2: 0.9348 | RMSE: 2513 | MAE: 1402 | Bias: 23.6

[C7|F5] Processing fold...
  > [TRAIN] R2: 0.9498 | RMSE: 2193 | MAE: 1262 | Bias: 0.9
  > [VAL]   R2: 0.9447 | RMSE: 2237 | MAE: 1369 | Bias: -27.3

Config 7 SUMMARY:
  [TRAIN AVG] MAE: 1259.0 | R2: 0.9504 | Bias: 0.3
  [VAL AVG]   MAE: 1406.1 | R2: 0.9361 | Bias: 2.9 | RMSE: 2459.6

######## CONFIG 8/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 5, 'tree_max_depth': 15, 'n_estimators': 1200, 'max_samples': 1.0, 'max_features': 0.8}

[C8|F1] Processing fold...
  > Features Used (16): ['year', 'mileage', 'engineSize', 'tax', 'mpg', 'previousOwners', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9592 | RMSE: 1978 | MAE: 1161 | Bias: -0.5
  > [VAL]   R2: 0.9477 | RMSE: 2184 | MAE: 1370 | Bias: -30.6

[C8|F2] Processing fold...
  > [TRAIN] R2: 0.9597 | RMSE: 1956 | MAE: 1149 | Bias: -0.2
  > [VAL]   R2: 0.9417 | RMSE: 2350 | MAE: 1378 | Bias: 22.5

[C8|F3] Processing fold...
  > [TRAIN] R2: 0.9615 | RMSE: 1895 | MAE: 1148 | Bias: 0.4
  > [VAL]   R2: 0.9255 | RMSE: 2742 | MAE: 1398 | Bias: 31.8

[C8|F4] Processing fold...
  > [TRAIN] R2: 0.9589 | RMSE: 1969 | MAE: 1159 | Bias: 0.3
  > [VAL]   R2: 0.9408 | RMSE: 2395 | MAE: 1363 | Bias: 22.0

[C8|F5] Processing fold...
  > [TRAIN] R2: 0.9588 | RMSE: 1988 | MAE: 1160 | Bias: 0.6
  > [VAL]   R2: 0.9488 | RMSE: 2153 | MAE: 1335 | Bias: -22.3

Config 8 SUMMARY:
  [TRAIN AVG] MAE: 1155.3 | R2: 0.9596 | Bias: 0.1
  [VAL AVG]   MAE: 1368.8 | R2: 0.9409 | Bias: 4.7 | RMSE: 2364.7

######## CONFIG 9/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 1, 'tree_max_depth': 15, 'n_estimators': 400, 'max_samples': 0.5, 'max_features': 0.8}

[C9|F1] Processing fold...
  > Features Used (16): ['year', 'mileage', 'engineSize', 'tax', 'mpg', 'previousOwners', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9590 | RMSE: 1982 | MAE: 1183 | Bias: -4.0
  > [VAL]   R2: 0.9478 | RMSE: 2179 | MAE: 1373 | Bias: -38.4

[C9|F2] Processing fold...
  > [TRAIN] R2: 0.9599 | RMSE: 1950 | MAE: 1171 | Bias: -2.3
  > [VAL]   R2: 0.9418 | RMSE: 2347 | MAE: 1383 | Bias: 18.1

[C9|F3] Processing fold...
  > [TRAIN] R2: 0.9610 | RMSE: 1906 | MAE: 1169 | Bias: -1.3
  > [VAL]   R2: 0.9273 | RMSE: 2708 | MAE: 1399 | Bias: 25.9

[C9|F4] Processing fold...
  > [TRAIN] R2: 0.9590 | RMSE: 1967 | MAE: 1183 | Bias: -3.8
  > [VAL]   R2: 0.9413 | RMSE: 2386 | MAE: 1366 | Bias: 17.9

[C9|F5] Processing fold...
  > [TRAIN] R2: 0.9591 | RMSE: 1981 | MAE: 1183 | Bias: -3.8
  > [VAL]   R2: 0.9488 | RMSE: 2153 | MAE: 1341 | Bias: -32.6

Config 9 SUMMARY:
  [TRAIN AVG] MAE: 1177.8 | R2: 0.9596 | Bias: -3.0
  [VAL AVG]   MAE: 1372.6 | R2: 0.9414 | Bias: -1.8 | RMSE: 2354.7

######## CONFIG 10/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 5, 'tree_max_depth': 15, 'n_estimators': 1000, 'max_samples': 0.5, 'max_features': 0.8}

[C10|F1] Processing fold...
  > Features Used (16): ['year', 'mileage', 'engineSize', 'tax', 'mpg', 'previousOwners', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9496 | RMSE: 2196 | MAE: 1255 | Bias: 2.5
  > [VAL]   R2: 0.9439 | RMSE: 2261 | MAE: 1411 | Bias: -31.9

[C10|F2] Processing fold...
  > [TRAIN] R2: 0.9506 | RMSE: 2164 | MAE: 1246 | Bias: 3.4
  > [VAL]   R2: 0.9358 | RMSE: 2465 | MAE: 1420 | Bias: 25.2

[C10|F3] Processing fold...
  > [TRAIN] R2: 0.9521 | RMSE: 2114 | MAE: 1243 | Bias: 2.7
  > [VAL]   R2: 0.9202 | RMSE: 2838 | MAE: 1437 | Bias: 36.5

[C10|F4] Processing fold...
  > [TRAIN] R2: 0.9498 | RMSE: 2175 | MAE: 1254 | Bias: 2.3
  > [VAL]   R2: 0.9344 | RMSE: 2522 | MAE: 1405 | Bias: 26.5

[C10|F5] Processing fold...
  > [TRAIN] R2: 0.9493 | RMSE: 2206 | MAE: 1255 | Bias: 2.6
  > [VAL]   R2: 0.9439 | RMSE: 2254 | MAE: 1377 | Bias: -23.9

Config 10 SUMMARY:
  [TRAIN AVG] MAE: 1250.7 | R2: 0.9503 | Bias: 2.7
  [VAL AVG]   MAE: 1410.1 | R2: 0.9356 | Bias: 6.5 | RMSE: 2467.9

######## CONFIG 11/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 1, 'tree_max_depth': 15, 'n_estimators': 1200, 'max_samples': 0.5, 'max_features': 0.9}

[C11|F1] Processing fold...
  > Features Used (16): ['year', 'mileage', 'engineSize', 'tax', 'mpg', 'previousOwners', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9606 | RMSE: 1942 | MAE: 1151 | Bias: -2.1
  > [VAL]   R2: 0.9482 | RMSE: 2173 | MAE: 1359 | Bias: -35.5

[C11|F2] Processing fold...
  > [TRAIN] R2: 0.9616 | RMSE: 1908 | MAE: 1138 | Bias: -1.8
  > [VAL]   R2: 0.9419 | RMSE: 2344 | MAE: 1364 | Bias: 14.8

[C11|F3] Processing fold...
  > [TRAIN] R2: 0.9629 | RMSE: 1861 | MAE: 1137 | Bias: -0.8
  > [VAL]   R2: 0.9282 | RMSE: 2693 | MAE: 1387 | Bias: 26.6

[C11|F4] Processing fold...
  > [TRAIN] R2: 0.9607 | RMSE: 1924 | MAE: 1149 | Bias: -2.2
  > [VAL]   R2: 0.9424 | RMSE: 2362 | MAE: 1350 | Bias: 19.7

[C11|F5] Processing fold...
  > [TRAIN] R2: 0.9607 | RMSE: 1941 | MAE: 1150 | Bias: -1.8
  > [VAL]   R2: 0.9499 | RMSE: 2128 | MAE: 1318 | Bias: -28.2

Config 11 SUMMARY:
  [TRAIN AVG] MAE: 1145.0 | R2: 0.9613 | Bias: -1.7
  [VAL AVG]   MAE: 1355.4 | R2: 0.9421 | Bias: -0.5 | RMSE: 2339.8

######## CONFIG 12/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 5, 'tree_max_depth': 25, 'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.8}

[C12|F1] Processing fold...
  > Features Used (16): ['year', 'mileage', 'engineSize', 'tax', 'mpg', 'previousOwners', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9628 | RMSE: 1886 | MAE: 1068 | Bias: -2.3
  > [VAL]   R2: 0.9488 | RMSE: 2159 | MAE: 1344 | Bias: -33.0

[C12|F2] Processing fold...
  > [TRAIN] R2: 0.9631 | RMSE: 1872 | MAE: 1063 | Bias: -1.5
  > [VAL]   R2: 0.9427 | RMSE: 2329 | MAE: 1354 | Bias: 21.1

[C12|F3] Processing fold...
  > [TRAIN] R2: 0.9651 | RMSE: 1804 | MAE: 1059 | Bias: 0.5
  > [VAL]   R2: 0.9265 | RMSE: 2724 | MAE: 1374 | Bias: 32.1

[C12|F4] Processing fold...
  > [TRAIN] R2: 0.9626 | RMSE: 1879 | MAE: 1069 | Bias: -1.9
  > [VAL]   R2: 0.9417 | RMSE: 2377 | MAE: 1338 | Bias: 18.6

[C12|F5] Processing fold...
  > [TRAIN] R2: 0.9626 | RMSE: 1895 | MAE: 1069 | Bias: -1.1
  > [VAL]   R2: 0.9499 | RMSE: 2129 | MAE: 1310 | Bias: -23.9

Config 12 SUMMARY:
  [TRAIN AVG] MAE: 1065.6 | R2: 0.9632 | Bias: -1.3
  [VAL AVG]   MAE: 1344.2 | R2: 0.9419 | Bias: 3.0 | RMSE: 2343.5

######## CONFIG 13/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 5, 'tree_max_depth': 15, 'n_estimators': 1200, 'max_samples': 0.5, 'max_features': 0.8}

[C13|F1] Processing fold...
  > Features Used (16): ['year', 'mileage', 'engineSize', 'tax', 'mpg', 'previousOwners', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9496 | RMSE: 2197 | MAE: 1257 | Bias: 2.7
  > [VAL]   R2: 0.9439 | RMSE: 2261 | MAE: 1412 | Bias: -31.9

[C13|F2] Processing fold...
  > [TRAIN] R2: 0.9506 | RMSE: 2164 | MAE: 1247 | Bias: 2.8
  > [VAL]   R2: 0.9357 | RMSE: 2466 | MAE: 1421 | Bias: 24.5

[C13|F3] Processing fold...
  > [TRAIN] R2: 0.9522 | RMSE: 2112 | MAE: 1244 | Bias: 2.6
  > [VAL]   R2: 0.9201 | RMSE: 2840 | MAE: 1438 | Bias: 36.5

[C13|F4] Processing fold...
  > [TRAIN] R2: 0.9498 | RMSE: 2176 | MAE: 1256 | Bias: 2.6
  > [VAL]   R2: 0.9343 | RMSE: 2522 | MAE: 1407 | Bias: 26.5

[C13|F5] Processing fold...
  > [TRAIN] R2: 0.9492 | RMSE: 2207 | MAE: 1256 | Bias: 2.7
  > [VAL]   R2: 0.9438 | RMSE: 2254 | MAE: 1379 | Bias: -23.9

Config 13 SUMMARY:
  [TRAIN AVG] MAE: 1251.9 | R2: 0.9503 | Bias: 2.7
  [VAL AVG]   MAE: 1411.5 | R2: 0.9356 | Bias: 6.3 | RMSE: 2468.5

######## CONFIG 14/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 1, 'tree_max_depth': 25, 'n_estimators': 400, 'max_samples': 0.5, 'max_features': 0.8}

[C14|F1] Processing fold...
  > Features Used (16): ['year', 'mileage', 'engineSize', 'tax', 'mpg', 'previousOwners', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9634 | RMSE: 1871 | MAE: 1078 | Bias: -7.4
  > [VAL]   R2: 0.9494 | RMSE: 2148 | MAE: 1343 | Bias: -44.1

[C14|F2] Processing fold...
  > [TRAIN] R2: 0.9641 | RMSE: 1845 | MAE: 1072 | Bias: -6.1
  > [VAL]   R2: 0.9430 | RMSE: 2322 | MAE: 1355 | Bias: 14.5

[C14|F3] Processing fold...
  > [TRAIN] R2: 0.9654 | RMSE: 1796 | MAE: 1069 | Bias: -4.6
  > [VAL]   R2: 0.9287 | RMSE: 2683 | MAE: 1369 | Bias: 21.1

[C14|F4] Processing fold...
  > [TRAIN] R2: 0.9634 | RMSE: 1858 | MAE: 1080 | Bias: -7.8
  > [VAL]   R2: 0.9427 | RMSE: 2356 | MAE: 1335 | Bias: 11.2

[C14|F5] Processing fold...
  > [TRAIN] R2: 0.9634 | RMSE: 1873 | MAE: 1080 | Bias: -7.2
  > [VAL]   R2: 0.9502 | RMSE: 2123 | MAE: 1311 | Bias: -36.6

Config 14 SUMMARY:
  [TRAIN AVG] MAE: 1075.7 | R2: 0.9640 | Bias: -6.6
  [VAL AVG]   MAE: 1342.4 | R2: 0.9428 | Bias: -6.8 | RMSE: 2326.5

######## CONFIG 15/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 5, 'tree_max_depth': 25, 'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.8}

[C15|F1] Processing fold...
  > Features Used (16): ['year', 'mileage', 'engineSize', 'tax', 'mpg', 'previousOwners', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9513 | RMSE: 2158 | MAE: 1224 | Bias: -0.7
  > [VAL]   R2: 0.9455 | RMSE: 2229 | MAE: 1388 | Bias: -32.6

[C15|F2] Processing fold...
  > [TRAIN] R2: 0.9524 | RMSE: 2124 | MAE: 1218 | Bias: 0.8
  > [VAL]   R2: 0.9382 | RMSE: 2419 | MAE: 1397 | Bias: 24.7

[C15|F3] Processing fold...

,n_estimators,max_samples,max_features,tree_max_depth,tree_min_samples_leaf,tree_min_samples_split,val_rmse,val_mae,val_r2,train_r2,val_bias
0,1000,1.0,0.9,15,1,10,2264.596630,1324.976798,0.945786,0.970258,-0.149291
13,400,0.5,0.8,25,1,10,2326.480327,1342.434084,0.942783,0.963957,-6.793292
3,1200,1.0,0.9,25,5,10,2330.802026,1328.742168,0.942543,0.965285,3.677514
10,1200,0.5,0.9,15,1,10,2339.827172,1355.426716,0.942129,0.961300,-0.512505
11,400,1.0,0.8,25,5,10,2343.539000,1344.178500,0.941916,0.963229,2.967487

Best Config found:
{'tree_min_samples_split': 10, 'tree_min_samples_leaf': 1, 'tree_max_depth': 15, 'n_estimators': 1000, 'max_samples': 1.0, 'max_features': 0.9}

modelo normal mas sem previous owners e com log do price

In [14]:

# K-FOLD CROSS-VALIDATION

# The data is shuffled before splitting to ensure that, at least theoretically, each fold is more balanced and
# representative of the full dataset distribution.
kf = KFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)
#confirmar isto aqui 
numeric_features = ["mileage", "engineSize", "tax", "mpg"]
DROP_FROM_MODEL = ["previousOwners"]

# HYPERPARAMETER SPACE FOR RANDOM SEARCH

# Each random configuration will sample exactly one value
# from each list below.
# The parameters are divided into:
#  - ensemble-level (Bagging)
#  - base estimator-level (Decision Tree)
param_distributions = {

    # Bagging (ensemble-level)
    
    # Number of trees in the ensemble.
    # Higher values usually improve stability but increase training time.
    "n_estimators": [400, 600,1000],

    # Fraction of samples used to train each tree.
    # Values < 1.0 increase diversity between estimators.
    "max_samples": [0.5, 1.0],

    # Fraction of features used by each estimator.
    # This helps reduce correlation between trees.
    "max_features": [0.6, 0.8, 0.9],

    
    # Decision Tree (base model)
    
    # Maximum depth of each decision tree.
    "tree_max_depth": [15, 20, 25],

    # Minimum number of samples required at a leaf node.
    # Larger values increase regularization.
    "tree_min_samples_leaf": [1, 5, 10],

    # Minimum number of samples required to split an internal node.
    "tree_min_samples_split": [10, 30, 50]
}

# Number of random configurations to evaluate.
# This is intentionally small, as this run is intended
# to provide baseline and comparative results.
N_RANDOM_CONFIGS = 15



# RANDOM SAMPLER

# Randomly samples N_RANDOM_CONFIGS combinations from the hyperparameter space defined above.
sampler = ParameterSampler(
    param_distributions,
    n_iter=N_RANDOM_CONFIGS,
    random_state=RANDOM_STATE
)

# List to store results for each configuration
search_results = []

# Track the best configuration according to validation RMSE
best_rmse = np.inf
best_config = None



# LOGGING SETUP

# All logs are written both to the console and to a file for reproducibility and later inspection.
log_path = "Bagging_DT_noprev_log_price.txt"

with open(log_path, "w", encoding="utf-8") as log_file:

    # Helper logging function
    def log(msg: str):
        print(msg)
        log_file.write(msg + "\n")
        log_file.flush()

    # Log header
    log("# =============================")
    log("# START OF BAGGING + DECISION TREE SEARCH")
    log("# DETAILED METRICS: R2, RMSE, MAE, BIAS")
    log(f"# LOG FILE SAVED TO: {log_path}")
    log("# =============================")

    
    # RANDOM SEARCH LOOP
    
    for config_id, params in enumerate(sampler, start=1):
        log("")
        log(f"######## CONFIG {config_id}/{N_RANDOM_CONFIGS} ########")
        log(f"Parameters: {params}")

        # Containers for fold-level metrics
        fold_rmses_val, fold_maes_val, fold_r2s_val, fold_bias_val = [], [], [], []
        fold_rmses_tr, fold_maes_tr, fold_r2s_tr, fold_bias_tr = [], [], [], []
        fold_med_ae = []

        
        # K-FOLD CROSS-VALIDATION
        
        for fold, (train_idx, val_idx) in enumerate(kf.split(X), start=1):

            # Split data into training and validation sets
            X_train, X_val = X.iloc[train_idx].copy(), X.iloc[val_idx].copy()
            y_train, y_val = y.iloc[train_idx].copy(), y.iloc[val_idx].copy()
            y_train_log = np.log1p(y_train)
            log(f"\n[C{config_id}|F{fold}] Processing fold...")

            
            # PREPROCESSING PIPELINE
        
            # All transformations are fit ONLY on the training data
            # and then applied to both training and validation sets.

            year_state = fit_year_median(X_train, year_col="year", model_col="model")
            X_train = transform_year_with_model_median(X_train, state=year_state)
            X_val   = transform_year_with_model_median(X_val,   state=year_state)

            mileage_state = fit_mileage_imputer(X_train, mileage_col="mileage", do_abs=True)
            X_train = transform_mileage_imputer(X_train, state=mileage_state)
            X_val   = transform_mileage_imputer(X_val,   state=mileage_state)

            engine_state = fit_engine_size_imputer(X_train, engine_col="engineSize")
            X_train = transform_engine_size_imputer(X_train, state=engine_state)
            X_val   = transform_engine_size_imputer(X_val,   state=engine_state)

            X_train = transform_tax_custom_rules(X_train, "tax", "year", "fuelType", "engineSize")
            X_val   = transform_tax_custom_rules(X_val, "tax", "year", "fuelType", "engineSize")

            mpg_state = fit_mpg_imputer(X_train, mpg_col="mpg", do_abs=True)
            X_train = transform_mpg_imputer(X_train, state=mpg_state)
            X_val   = transform_mpg_imputer(X_val,   state=mpg_state)

            brand_state = fit_ambiguous_brand_resolver(X_train, valid_brands)
            X_train, _, _ = transform_ambiguous_brands(X_train, brand_state)
            X_val, _, _   = transform_ambiguous_brands(X_val, brand_state)

            model_state = fit_invalid_model_resolver(X_train, valid_models_by_brand)
            X_train, _, _ = transform_invalid_models(X_train, model_state)
            X_val, _, _   = transform_invalid_models(X_val, model_state)

            transm_state = fit_transmission_resolver(X_train, valid_transmissions)
            X_train, _, _ = transform_transmission_resolver(X_train, transm_state)
            X_val, _, _   = transform_transmission_resolver(X_val, transm_state)

            fuel_state = fit_fueltype_resolver(X_train, valid_fueltypes)
            X_train, _, _ = transform_fueltype_resolver(X_train, fuel_state)
            X_val, _, _   = transform_fueltype_resolver(X_val, fuel_state)

            X_train = X_train.drop(columns=DROP_FROM_MODEL, errors="ignore")
            X_val   = X_val.drop(columns=DROP_FROM_MODEL, errors="ignore")

            # FEATURE ENCODING

            # High-cardinality features use target encoding,
            # low-cardinality features use one-hot encoding.
            high_card_features = ["Brand", "model"]
            low_card_features  = [c for c in categorical_features if c not in high_card_features]

            te = MyTargetEncoder(smoothing=5)
            te.fit(X_train[high_card_features], y_train_log)
            X_train_high = te.transform(X_train[high_card_features])
            X_val_high   = te.transform(X_val[high_card_features])

            ohe = MyOneHotEncoder()
            ohe.fit(X_train[low_card_features])
            X_train_low = ohe.transform(X_train[low_card_features])
            X_val_low   = ohe.transform(X_val[low_card_features])

            X_train_cat = pd.concat([X_train_high, X_train_low], axis=1)
            X_val_cat   = pd.concat([X_val_high,   X_val_low],   axis=1)

            # Combine numerical and encoded categorical features
            X_train_final = pd.concat([X_train[numeric_features], X_train_cat], axis=1)
            X_val_final   = pd.concat([X_val[numeric_features],   X_val_cat],   axis=1)

            
            # FEATURE SCALING
            
            # Although tree-based models do not strictly require scaling,
            # we apply StandardScaler for numerical stability and
            # consistency across models.
            scaler = StandardScaler()
            X_train_scaled = scaler.fit_transform(X_train_final)
            X_val_scaled   = scaler.transform(X_val_final)

            if fold == 1:
                feature_names = list(X_train_final.columns)
                log(f"  > Features Used ({len(feature_names)}): {feature_names}")

            
            # MODEL DEFINITION
            
            base_tree = DecisionTreeRegressor(
                max_depth=params["tree_max_depth"],
                min_samples_leaf=params["tree_min_samples_leaf"],
                min_samples_split=params["tree_min_samples_split"],
                random_state=RANDOM_STATE
            )

            model = BaggingRegressor(
                estimator=base_tree,
                n_estimators=params["n_estimators"],
                max_samples=params["max_samples"],
                max_features=params["max_features"],
                random_state=RANDOM_STATE,
                n_jobs=-1
            )

            # Train the model
            model.fit(X_train_scaled, y_train_log)

            
            # PREDICTIONS

            y_pred_train_log = model.predict(X_train_scaled)
            y_pred_val_log   = model.predict(X_val_scaled)

            y_pred_train = np.expm1(y_pred_train_log)
            y_pred_val   = np.expm1(y_pred_val_log)



            
            # METRICS
            
            mae_tr = mean_absolute_error(y_train, y_pred_train)
            rmse_tr = np.sqrt(mean_squared_error(y_train, y_pred_train))
            r2_tr = r2_score(y_train, y_pred_train)
            bias_tr = np.mean(y_train - y_pred_train)

            mae_val = mean_absolute_error(y_val, y_pred_val)
            rmse_val = np.sqrt(mean_squared_error(y_val, y_pred_val))
            r2_val = r2_score(y_val, y_pred_val)
            bias_val = np.mean(y_val - y_pred_val)
            med_ae_val = median_absolute_error(y_val, y_pred_val)

            log(f"  > [TRAIN] R2: {r2_tr:.4f} | RMSE: {rmse_tr:.0f} | MAE: {mae_tr:.0f} | Bias: {bias_tr:.1f}")
            log(f"  > [VAL]   R2: {r2_val:.4f} | RMSE: {rmse_val:.0f} | MAE: {mae_val:.0f} | Bias: {bias_val:.1f}")

            fold_maes_tr.append(mae_tr)
            fold_rmses_tr.append(rmse_tr)
            fold_r2s_tr.append(r2_tr)
            fold_bias_tr.append(bias_tr)

            fold_maes_val.append(mae_val)
            fold_rmses_val.append(rmse_val)
            fold_r2s_val.append(r2_val)
            fold_bias_val.append(bias_val)
            fold_med_ae.append(med_ae_val)

        
        # AGGREGATED RESULTS
        
        mean_rmse_val = np.mean(fold_rmses_val)
        mean_mae_val  = np.mean(fold_maes_val)
        mean_r2_val   = np.mean(fold_r2s_val)
        mean_bias_val = np.mean(fold_bias_val)

        mean_mae_tr   = np.mean(fold_maes_tr)
        mean_r2_tr    = np.mean(fold_r2s_tr)
        mean_bias_tr  = np.mean(fold_bias_tr)

        log("")
        log(f"Config {config_id} SUMMARY:")
        log(f"  [TRAIN AVG] MAE: {mean_mae_tr:.1f} | R2: {mean_r2_tr:.4f} | Bias: {mean_bias_tr:.1f}")
        log(f"  [VAL AVG]   MAE: {mean_mae_val:.1f} | R2: {mean_r2_val:.4f} | Bias: {mean_bias_val:.1f} | RMSE: {mean_rmse_val:.1f}")

        search_results.append({
            "config_id": config_id,
            **params,
            "val_rmse": mean_rmse_val,
            "val_mae": mean_mae_val,
            "val_r2": mean_r2_val,
            "val_bias": mean_bias_val,
            "train_mae": mean_mae_tr,
            "train_r2": mean_r2_tr,
            "train_bias": mean_bias_tr,
            "val_med_ae": np.mean(fold_med_ae)
        })

        if mean_rmse_val < best_rmse:
            best_rmse = mean_rmse_val
            best_config = {**params}
            log(f"[NEW BEST RMSE] Config {config_id}")

    log("# END OF SEARCH")



# FINAL RESULTS

results_df = pd.DataFrame(search_results)
results_df_sorted = results_df.sort_values(by="val_rmse", ascending=True)

print("\nTop 5 Configurations by RMSE:")
cols = ["n_estimators", "max_samples", "max_features", "tree_max_depth", "tree_min_samples_leaf", "tree_min_samples_split", "val_rmse", "val_mae", "val_r2", "train_r2", "val_bias"]
display(results_df_sorted[cols].head(5))

print("\nBest Config found:")
print(best_config)

# =============================
# START OF BAGGING + DECISION TREE SEARCH
# DETAILED METRICS: R2, RMSE, MAE, BIAS
# LOG FILE SAVED TO: Bagging_DT_noprev_log_price.txt
# =============================

######## CONFIG 1/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 10, 'tree_max_depth': 20, 'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.9}

[C1|F1] Processing fold...
  > Features Used (14): ['mileage', 'engineSize', 'tax', 'mpg', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9345 | RMSE: 2504 | MAE: 1409 | Bias: 261.7
  > [VAL]   R2: 0.9251 | RMSE: 2613 | MAE: 1604 | Bias: 237.3

[C1|F2] Processing fold...
  > [TRAIN] R2: 0.9352 | RMSE: 2480 | MAE: 1405 | Bias: 261.1
  > [VAL]   R2: 0.9124 | RMSE: 2879 | MAE: 1618 | Bias: 296.6

[C1|F3] Processing fold...
  > [TRAIN] R2: 0.9352 | RMSE: 2458 | MAE: 1406 | Bias: 259.6
  > [VAL]   R2: 0.8998 | RMSE: 3180 | MAE: 1633 | Bias: 322.2

[C1|F4] Processing fold...
  > [TRAIN] R2: 0.9346 | RMSE: 2482 | MAE: 1407 | Bias: 262.2
  > [VAL]   R2: 0.9148 | RMSE: 2874 | MAE: 1604 | Bias: 322.0

[C1|F5] Processing fold...
  > [TRAIN] R2: 0.9334 | RMSE: 2527 | MAE: 1415 | Bias: 265.2
  > [VAL]   R2: 0.9280 | RMSE: 2551 | MAE: 1561 | Bias: 235.7

Config 1 SUMMARY:
  [TRAIN AVG] MAE: 1408.3 | R2: 0.9346 | Bias: 261.9
  [VAL AVG]   MAE: 1604.2 | R2: 0.9160 | Bias: 282.8 | RMSE: 2819.4
[NEW BEST RMSE] Config 1

######## CONFIG 2/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 1, 'tree_max_depth': 25, 'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.8}

[C2|F1] Processing fold...
  > Features Used (14): ['mileage', 'engineSize', 'tax', 'mpg', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9428 | RMSE: 2341 | MAE: 1343 | Bias: 291.2
  > [VAL]   R2: 0.9297 | RMSE: 2530 | MAE: 1561 | Bias: 277.6

[C2|F2] Processing fold...
  > [TRAIN] R2: 0.9432 | RMSE: 2321 | MAE: 1338 | Bias: 291.9
  > [VAL]   R2: 0.9200 | RMSE: 2751 | MAE: 1579 | Bias: 343.7

[C2|F3] Processing fold...
  > [TRAIN] R2: 0.9450 | RMSE: 2265 | MAE: 1336 | Bias: 289.2
  > [VAL]   R2: 0.9052 | RMSE: 3094 | MAE: 1594 | Bias: 361.1

[C2|F4] Processing fold...
  > [TRAIN] R2: 0.9440 | RMSE: 2298 | MAE: 1340 | Bias: 291.0
  > [VAL]   R2: 0.9207 | RMSE: 2772 | MAE: 1559 | Bias: 359.9

[C2|F5] Processing fold...
  > [TRAIN] R2: 0.9422 | RMSE: 2355 | MAE: 1346 | Bias: 294.4
  > [VAL]   R2: 0.9320 | RMSE: 2480 | MAE: 1526 | Bias: 277.1

Config 2 SUMMARY:
  [TRAIN AVG] MAE: 1340.6 | R2: 0.9434 | Bias: 291.6
  [VAL AVG]   MAE: 1563.8 | R2: 0.9215 | Bias: 323.9 | RMSE: 2725.3
[NEW BEST RMSE] Config 2

######## CONFIG 3/15 ########
Parameters: {'tree_min_samples_split': 50, 'tree_min_samples_leaf': 10, 'tree_max_depth': 25, 'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.9}

[C3|F1] Processing fold...
  > Features Used (14): ['mileage', 'engineSize', 'tax', 'mpg', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9232 | RMSE: 2711 | MAE: 1531 | Bias: 289.1
  > [VAL]   R2: 0.9196 | RMSE: 2706 | MAE: 1659 | Bias: 258.3

[C3|F2] Processing fold...
  > [TRAIN] R2: 0.9234 | RMSE: 2695 | MAE: 1528 | Bias: 289.3
  > [VAL]   R2: 0.9056 | RMSE: 2989 | MAE: 1675 | Bias: 315.9

[C3|F3] Processing fold...
  > [TRAIN] R2: 0.9242 | RMSE: 2658 | MAE: 1525 | Bias: 287.0
  > [VAL]   R2: 0.8934 | RMSE: 3280 | MAE: 1691 | Bias: 350.1

[C3|F4] Processing fold...
  > [TRAIN] R2: 0.9236 | RMSE: 2683 | MAE: 1528 | Bias: 289.9
  > [VAL]   R2: 0.9069 | RMSE: 3004 | MAE: 1665 | Bias: 350.5

[C3|F5] Processing fold...
  > [TRAIN] R2: 0.9223 | RMSE: 2730 | MAE: 1535 | Bias: 293.2
  > [VAL]   R2: 0.9218 | RMSE: 2659 | MAE: 1618 | Bias: 254.7

Config 3 SUMMARY:
  [TRAIN AVG] MAE: 1529.4 | R2: 0.9234 | Bias: 289.7
  [VAL AVG]   MAE: 1661.5 | R2: 0.9095 | Bias: 305.9 | RMSE: 2927.8

######## CONFIG 4/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 10, 'tree_max_depth': 20, 'n_estimators': 600, 'max_samples': 1.0, 'max_features': 0.9}

[C4|F1] Processing fold...
  > Features Used (14): ['mileage', 'engineSize', 'tax', 'mpg', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9305 | RMSE: 2580 | MAE: 1450 | Bias: 274.0
  > [VAL]   R2: 0.9237 | RMSE: 2636 | MAE: 1616 | Bias: 245.9

[C4|F2] Processing fold...
  > [TRAIN] R2: 0.9312 | RMSE: 2554 | MAE: 1446 | Bias: 272.5
  > [VAL]   R2: 0.9101 | RMSE: 2916 | MAE: 1632 | Bias: 305.3

[C4|F3] Processing fold...
  > [TRAIN] R2: 0.9315 | RMSE: 2527 | MAE: 1446 | Bias: 271.4
  > [VAL]   R2: 0.8980 | RMSE: 3208 | MAE: 1647 | Bias: 333.5

[C4|F4] Processing fold...
  > [TRAIN] R2: 0.9310 | RMSE: 2551 | MAE: 1447 | Bias: 273.6
  > [VAL]   R2: 0.9128 | RMSE: 2906 | MAE: 1617 | Bias: 333.3

[C4|F5] Processing fold...
  > [TRAIN] R2: 0.9294 | RMSE: 2602 | MAE: 1455 | Bias: 277.7
  > [VAL]   R2: 0.9264 | RMSE: 2581 | MAE: 1574 | Bias: 245.5

Config 4 SUMMARY:
  [TRAIN AVG] MAE: 1448.9 | R2: 0.9307 | Bias: 273.8
  [VAL AVG]   MAE: 1617.4 | R2: 0.9142 | Bias: 292.7 | RMSE: 2849.4

######## CONFIG 5/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 5, 'tree_max_depth': 20, 'n_estimators': 600, 'max_samples': 0.5, 'max_features': 0.9}

[C5|F1] Processing fold...
  > Features Used (14): ['mileage', 'engineSize', 'tax', 'mpg', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9256 | RMSE: 2669 | MAE: 1509 | Bias: 292.1
  > [VAL]   R2: 0.9215 | RMSE: 2674 | MAE: 1640 | Bias: 261.3

[C5|F2] Processing fold...
  > [TRAIN] R2: 0.9260 | RMSE: 2649 | MAE: 1507 | Bias: 291.8
  > [VAL]   R2: 0.9086 | RMSE: 2941 | MAE: 1654 | Bias: 320.5

[C5|F3] Processing fold...
  > [TRAIN] R2: 0.9270 | RMSE: 2609 | MAE: 1502 | Bias: 290.3
  > [VAL]   R2: 0.8951 | RMSE: 3254 | MAE: 1674 | Bias: 353.3

[C5|F4] Processing fold...
  > [TRAIN] R2: 0.9263 | RMSE: 2637 | MAE: 1507 | Bias: 291.2
  > [VAL]   R2: 0.9092 | RMSE: 2966 | MAE: 1646 | Bias: 348.9

[C5|F5] Processing fold...
  > [TRAIN] R2: 0.9246 | RMSE: 2689 | MAE: 1513 | Bias: 295.6
  > [VAL]   R2: 0.9237 | RMSE: 2626 | MAE: 1599 | Bias: 257.8

Config 5 SUMMARY:
  [TRAIN AVG] MAE: 1507.7 | R2: 0.9259 | Bias: 292.2
  [VAL AVG]   MAE: 1642.8 | R2: 0.9116 | Bias: 308.4 | RMSE: 2892.1

######## CONFIG 6/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 10, 'tree_max_depth': 15, 'n_estimators': 1000, 'max_samples': 1.0, 'max_features': 0.9}

[C6|F1] Processing fold...
  > Features Used (14): ['mileage', 'engineSize', 'tax', 'mpg', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9326 | RMSE: 2540 | MAE: 1444 | Bias: 274.2
  > [VAL]   R2: 0.9249 | RMSE: 2616 | MAE: 1612 | Bias: 247.7

[C6|F2] Processing fold...
  > [TRAIN] R2: 0.9334 | RMSE: 2513 | MAE: 1438 | Bias: 272.8
  > [VAL]   R2: 0.9120 | RMSE: 2886 | MAE: 1626 | Bias: 309.4

[C6|F3] Processing fold...
  > [TRAIN] R2: 0.9335 | RMSE: 2490 | MAE: 1439 | Bias: 271.7
  > [VAL]   R2: 0.8995 | RMSE: 3185 | MAE: 1641 | Bias: 333.8

[C6|F4] Processing fold...
  > [TRAIN] R2: 0.9328 | RMSE: 2517 | MAE: 1441 | Bias: 274.8
  > [VAL]   R2: 0.9143 | RMSE: 2881 | MAE: 1612 | Bias: 334.5

[C6|F5] Processing fold...
  > [TRAIN] R2: 0.9316 | RMSE: 2562 | MAE: 1449 | Bias: 278.2
  > [VAL]   R2: 0.9276 | RMSE: 2558 | MAE: 1571 | Bias: 249.0

Config 6 SUMMARY:
  [TRAIN AVG] MAE: 1442.2 | R2: 0.9328 | Bias: 274.4
  [VAL AVG]   MAE: 1612.4 | R2: 0.9157 | Bias: 294.9 | RMSE: 2825.4

######## CONFIG 7/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 5, 'tree_max_depth': 15, 'n_estimators': 600, 'max_samples': 0.5, 'max_features': 0.8}

[C7|F1] Processing fold...
  > Features Used (14): ['mileage', 'engineSize', 'tax', 'mpg', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9221 | RMSE: 2731 | MAE: 1547 | Bias: 343.9
  > [VAL]   R2: 0.9197 | RMSE: 2704 | MAE: 1657 | Bias: 311.9

[C7|F2] Processing fold...
  > [TRAIN] R2: 0.9224 | RMSE: 2714 | MAE: 1543 | Bias: 343.6
  > [VAL]   R2: 0.9065 | RMSE: 2974 | MAE: 1672 | Bias: 376.5

[C7|F3] Processing fold...
  > [TRAIN] R2: 0.9235 | RMSE: 2671 | MAE: 1539 | Bias: 342.6
  > [VAL]   R2: 0.8920 | RMSE: 3301 | MAE: 1691 | Bias: 406.7

[C7|F4] Processing fold...
  > [TRAIN] R2: 0.9229 | RMSE: 2697 | MAE: 1545 | Bias: 343.3
  > [VAL]   R2: 0.9064 | RMSE: 3012 | MAE: 1664 | Bias: 401.1

[C7|F5] Processing fold...
  > [TRAIN] R2: 0.9212 | RMSE: 2749 | MAE: 1549 | Bias: 347.6
  > [VAL]   R2: 0.9211 | RMSE: 2672 | MAE: 1621 | Bias: 312.7

Config 7 SUMMARY:
  [TRAIN AVG] MAE: 1544.4 | R2: 0.9224 | Bias: 344.2
  [VAL AVG]   MAE: 1661.0 | R2: 0.9091 | Bias: 361.8 | RMSE: 2932.6

######## CONFIG 8/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 1, 'tree_max_depth': 20, 'n_estimators': 1000, 'max_samples': 0.5, 'max_features': 0.8}

[C8|F1] Processing fold...
  > Features Used (14): ['mileage', 'engineSize', 'tax', 'mpg', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9497 | RMSE: 2195 | MAE: 1256 | Bias: 276.1
  > [VAL]   R2: 0.9332 | RMSE: 2466 | MAE: 1523 | Bias: 272.0

[C8|F2] Processing fold...
  > [TRAIN] R2: 0.9502 | RMSE: 2173 | MAE: 1251 | Bias: 276.0
  > [VAL]   R2: 0.9238 | RMSE: 2684 | MAE: 1542 | Bias: 334.1

[C8|F3] Processing fold...
  > [TRAIN] R2: 0.9516 | RMSE: 2125 | MAE: 1249 | Bias: 275.0
  > [VAL]   R2: 0.9098 | RMSE: 3018 | MAE: 1554 | Bias: 350.1

[C8|F4] Processing fold...
  > [TRAIN] R2: 0.9500 | RMSE: 2172 | MAE: 1254 | Bias: 276.7
  > [VAL]   R2: 0.9253 | RMSE: 2691 | MAE: 1526 | Bias: 347.6

[C8|F5] Processing fold...
  > [TRAIN] R2: 0.9488 | RMSE: 2215 | MAE: 1260 | Bias: 279.7
  > [VAL]   R2: 0.9354 | RMSE: 2418 | MAE: 1491 | Bias: 270.3

Config 8 SUMMARY:
  [TRAIN AVG] MAE: 1253.8 | R2: 0.9501 | Bias: 276.7
  [VAL AVG]   MAE: 1527.2 | R2: 0.9255 | Bias: 314.8 | RMSE: 2655.6
[NEW BEST RMSE] Config 8

######## CONFIG 9/15 ########
Parameters: {'tree_min_samples_split': 50, 'tree_min_samples_leaf': 5, 'tree_max_depth': 25, 'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.6}

[C9|F1] Processing fold...
  > Features Used (14): ['mileage', 'engineSize', 'tax', 'mpg', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9008 | RMSE: 3081 | MAE: 1732 | Bias: 572.3
  > [VAL]   R2: 0.8997 | RMSE: 3023 | MAE: 1830 | Bias: 546.6

[C9|F2] Processing fold...
  > [TRAIN] R2: 0.9004 | RMSE: 3073 | MAE: 1730 | Bias: 571.2
  > [VAL]   R2: 0.8860 | RMSE: 3284 | MAE: 1857 | Bias: 612.6

[C9|F3] Processing fold...
  > [TRAIN] R2: 0.9033 | RMSE: 3004 | MAE: 1725 | Bias: 569.0
  > [VAL]   R2: 0.8686 | RMSE: 3642 | MAE: 1887 | Bias: 646.8

[C9|F4] Processing fold...
  > [TRAIN] R2: 0.9023 | RMSE: 3034 | MAE: 1732 | Bias: 570.2
  > [VAL]   R2: 0.8817 | RMSE: 3386 | MAE: 1848 | Bias: 631.5

[C9|F5] Processing fold...
  > [TRAIN] R2: 0.9004 | RMSE: 3091 | MAE: 1737 | Bias: 575.5
  > [VAL]   R2: 0.8992 | RMSE: 3019 | MAE: 1797 | Bias: 545.2

Config 9 SUMMARY:
  [TRAIN AVG] MAE: 1731.3 | R2: 0.9014 | Bias: 571.6
  [VAL AVG]   MAE: 1843.7 | R2: 0.8870 | Bias: 596.5 | RMSE: 3270.8

######## CONFIG 10/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 5, 'tree_max_depth': 20, 'n_estimators': 1000, 'max_samples': 0.5, 'max_features': 0.8}

[C10|F1] Processing fold...
  > Features Used (14): ['mileage', 'engineSize', 'tax', 'mpg', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9231 | RMSE: 2713 | MAE: 1525 | Bias: 344.0
  > [VAL]   R2: 0.9204 | RMSE: 2693 | MAE: 1645 | Bias: 313.1

[C10|F2] Processing fold...
  > [TRAIN] R2: 0.9232 | RMSE: 2699 | MAE: 1522 | Bias: 343.4
  > [VAL]   R2: 0.9072 | RMSE: 2963 | MAE: 1661 | Bias: 376.3

[C10|F3] Processing fold...
  > [TRAIN] R2: 0.9245 | RMSE: 2653 | MAE: 1518 | Bias: 342.4
  > [VAL]   R2: 0.8925 | RMSE: 3295 | MAE: 1679 | Bias: 408.5

[C10|F4] Processing fold...
  > [TRAIN] R2: 0.9238 | RMSE: 2680 | MAE: 1524 | Bias: 343.4
  > [VAL]   R2: 0.9068 | RMSE: 3005 | MAE: 1651 | Bias: 402.3

[C10|F5] Processing fold...
  > [TRAIN] R2: 0.9223 | RMSE: 2730 | MAE: 1528 | Bias: 347.9
  > [VAL]   R2: 0.9216 | RMSE: 2663 | MAE: 1608 | Bias: 314.0

Config 10 SUMMARY:
  [TRAIN AVG] MAE: 1523.4 | R2: 0.9234 | Bias: 344.2
  [VAL AVG]   MAE: 1648.8 | R2: 0.9097 | Bias: 362.8 | RMSE: 2923.9

######## CONFIG 11/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 1, 'tree_max_depth': 20, 'n_estimators': 400, 'max_samples': 0.5, 'max_features': 0.6}

[C11|F1] Processing fold...
  > Features Used (14): ['mileage', 'engineSize', 'tax', 'mpg', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9244 | RMSE: 2691 | MAE: 1536 | Bias: 509.4
  > [VAL]   R2: 0.9107 | RMSE: 2852 | MAE: 1742 | Bias: 513.6

[C11|F2] Processing fold...
  > [TRAIN] R2: 0.9248 | RMSE: 2671 | MAE: 1533 | Bias: 509.6
  > [VAL]   R2: 0.9000 | RMSE: 3076 | MAE: 1769 | Bias: 574.7

[C11|F3] Processing fold...
  > [TRAIN] R2: 0.9264 | RMSE: 2620 | MAE: 1530 | Bias: 507.1
  > [VAL]   R2: 0.8833 | RMSE: 3431 | MAE: 1794 | Bias: 598.4

[C11|F4] Processing fold...
  > [TRAIN] R2: 0.9252 | RMSE: 2656 | MAE: 1536 | Bias: 508.3
  > [VAL]   R2: 0.8976 | RMSE: 3150 | MAE: 1757 | Bias: 585.7

[C11|F5] Processing fold...
  > [TRAIN] R2: 0.9238 | RMSE: 2702 | MAE: 1540 | Bias: 511.4
  > [VAL]   R2: 0.9114 | RMSE: 2831 | MAE: 1713 | Bias: 507.0

Config 11 SUMMARY:
  [TRAIN AVG] MAE: 1534.8 | R2: 0.9249 | Bias: 509.1
  [VAL AVG]   MAE: 1755.1 | R2: 0.9006 | Bias: 555.9 | RMSE: 3068.0

######## CONFIG 12/15 ########
Parameters: {'tree_min_samples_split': 50, 'tree_min_samples_leaf': 5, 'tree_max_depth': 20, 'n_estimators': 400, 'max_samples': 0.5, 'max_features': 0.8}

[C12|F1] Processing fold...
  > Features Used (14): ['mileage', 'engineSize', 'tax', 'mpg', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9129 | RMSE: 2888 | MAE: 1618 | Bias: 367.6
  > [VAL]   R2: 0.9143 | RMSE: 2794 | MAE: 1704 | Bias: 329.0

[C12|F2] Processing fold...
  > [TRAIN] R2: 0.9137 | RMSE: 2861 | MAE: 1617 | Bias: 367.7
  > [VAL]   R2: 0.8993 | RMSE: 3086 | MAE: 1722 | Bias: 395.5

[C12|F3] Processing fold...
  > [TRAIN] R2: 0.9142 | RMSE: 2829 | MAE: 1610 | Bias: 365.7
  > [VAL]   R2: 0.8847 | RMSE: 3412 | MAE: 1743 | Bias: 431.2

[C12|F4] Processing fold...
  > [TRAIN] R2: 0.9136 | RMSE: 2855 | MAE: 1617 | Bias: 367.3
  > [VAL]   R2: 0.8977 | RMSE: 3149 | MAE: 1719 | Bias: 426.9

[C12|F5] Processing fold...
  > [TRAIN] R2: 0.9121 | RMSE: 2904 | MAE: 1622 | Bias: 371.6
  > [VAL]   R2: 0.9146 | RMSE: 2779 | MAE: 1669 | Bias: 330.1

Config 12 SUMMARY:
  [TRAIN AVG] MAE: 1616.9 | R2: 0.9133 | Bias: 368.0
  [VAL AVG]   MAE: 1711.4 | R2: 0.9021 | Bias: 382.5 | RMSE: 3044.0

######## CONFIG 13/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 5, 'tree_max_depth': 25, 'n_estimators': 1000, 'max_samples': 1.0, 'max_features': 0.9}

[C13|F1] Processing fold...
  > Features Used (14): ['mileage', 'engineSize', 'tax', 'mpg', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9522 | RMSE: 2138 | MAE: 1204 | Bias: 225.8
  > [VAL]   R2: 0.9331 | RMSE: 2468 | MAE: 1524 | Bias: 218.6

[C13|F2] Processing fold...
  > [TRAIN] R2: 0.9526 | RMSE: 2121 | MAE: 1202 | Bias: 225.4
  > [VAL]   R2: 0.9235 | RMSE: 2690 | MAE: 1537 | Bias: 278.2

[C13|F3] Processing fold...
  > [TRAIN] R2: 0.9540 | RMSE: 2072 | MAE: 1198 | Bias: 224.4
  > [VAL]   R2: 0.9112 | RMSE: 2994 | MAE: 1551 | Bias: 294.0

[C13|F4] Processing fold...
  > [TRAIN] R2: 0.9523 | RMSE: 2120 | MAE: 1202 | Bias: 226.3
  > [VAL]   R2: 0.9266 | RMSE: 2666 | MAE: 1523 | Bias: 286.0

[C13|F5] Processing fold...
  > [TRAIN] R2: 0.9514 | RMSE: 2159 | MAE: 1209 | Bias: 228.8
  > [VAL]   R2: 0.9365 | RMSE: 2396 | MAE: 1483 | Bias: 215.4

Config 13 SUMMARY:
  [TRAIN AVG] MAE: 1202.9 | R2: 0.9525 | Bias: 226.2
  [VAL AVG]   MAE: 1523.8 | R2: 0.9262 | Bias: 258.5 | RMSE: 2642.9
[NEW BEST RMSE] Config 13

######## CONFIG 14/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 1, 'tree_max_depth': 15, 'n_estimators': 400, 'max_samples': 0.5, 'max_features': 0.9}

[C14|F1] Processing fold...
  > Features Used (14): ['mileage', 'engineSize', 'tax', 'mpg', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9303 | RMSE: 2583 | MAE: 1502 | Bias: 285.3
  > [VAL]   R2: 0.9239 | RMSE: 2633 | MAE: 1633 | Bias: 256.1

[C14|F2] Processing fold...
  > [TRAIN] R2: 0.9308 | RMSE: 2561 | MAE: 1497 | Bias: 285.9
  > [VAL]   R2: 0.9135 | RMSE: 2861 | MAE: 1649 | Bias: 318.8

[C14|F3] Processing fold...
  > [TRAIN] R2: 0.9328 | RMSE: 2504 | MAE: 1491 | Bias: 282.9
  > [VAL]   R2: 0.8989 | RMSE: 3194 | MAE: 1669 | Bias: 346.8

[C14|F4] Processing fold...
  > [TRAIN] R2: 0.9314 | RMSE: 2542 | MAE: 1497 | Bias: 285.1
  > [VAL]   R2: 0.9130 | RMSE: 2903 | MAE: 1641 | Bias: 348.4

[C14|F5] Processing fold...
  > [TRAIN] R2: 0.9295 | RMSE: 2599 | MAE: 1505 | Bias: 289.0
  > [VAL]   R2: 0.9259 | RMSE: 2589 | MAE: 1598 | Bias: 252.2

Config 14 SUMMARY:
  [TRAIN AVG] MAE: 1498.5 | R2: 0.9310 | Bias: 285.7
  [VAL AVG]   MAE: 1638.2 | R2: 0.9150 | Bias: 304.5 | RMSE: 2836.0

######## CONFIG 15/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 5, 'tree_max_depth': 20, 'n_estimators': 1000, 'max_samples': 0.5, 'max_features': 0.9}

[C15|F1] Processing fold...
  > Features Used (14): ['mileage', 'engineSize', 'tax', 'mpg', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9256 | RMSE: 2669 | MAE: 1508 | Bias: 295.9
  > [VAL]   R2: 0.9217 | RMSE: 2670 | MAE: 1638 | Bias: 265.4

[C15|F2] Processing fold...
  > [TRAIN] R2: 0.9260 | RMSE: 2649 | MAE: 1505 | Bias: 294.9
  > [VAL]   R2: 0.9088 | RMSE: 2937 | MAE: 1652 | Bias: 324.1

[C15|F3] Processing fold...
  > [TRAIN] R2: 0.9270 | RMSE: 2609 | MAE: 1501 | Bias: 293.9
  > [VAL]   R2: 0.8953 | RMSE: 3251 | MAE: 1672 | Bias: 357.7


,n_estimators,max_samples,max_features,tree_max_depth,tree_min_samples_leaf,tree_min_samples_split,val_rmse,val_mae,val_r2,train_r2,val_bias
12,1000,1.0,0.9,25,5,10,2642.946254,1523.847803,0.926198,0.952509,258.457521
7,1000,0.5,0.8,20,1,10,2655.565459,1527.227733,0.925490,0.950070,314.831311
1,400,1.0,0.8,25,1,30,2725.339518,1563.775028,0.921526,0.943409,323.880738
0,400,1.0,0.9,20,10,10,2819.373564,1604.189197,0.916015,0.934581,282.764076
5,1000,1.0,0.9,15,10,10,2825.399580,1612.439365,0.915657,0.932785,294.900964

Best Config found:
{'tree_min_samples_split': 10, 'tree_min_samples_leaf': 5, 'tree_max_depth': 25, 'n_estimators': 1000, 'max_samples': 1.0, 'max_features': 0.9}

#### 3.3.1. All Engineered Features (no Feature Selection) <a id="featengnosel"></a>

In [16]:
N_ITER = 10
numeric_features = ["mileage", "engineSize", "tax", "mpg", "year", "previousOwners"]

# Reprodutibilidade do random search (configs)
random.seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

# ---------------------------------------------------------
# 0.1) LOGGING
# ---------------------------------------------------------
LOG_FILE = "bagging_fe_no_fs_iter10.log"
logging.basicConfig(
    filename=LOG_FILE,
    level=logging.INFO,
    format="%(asctime)s - %(message)s",
    filemode="w",
    force=True
)
logging.info(f"- {N_ITER} iterations | {N_SPLITS}-fold | BAGGING_DT | NO_FEATURE_SELECTION")

# ---------------------------------------------------------
# 0.2) RANDOM SEARCH
# ---------------------------------------------------------
param_distributions = {

    # Bagging (ensemble-level)
    
    # Number of trees in the ensemble.
    # Higher values usually improve stability but increase training time.
    "n_estimators": [400, 600,1000],

    # Fraction of samples used to train each tree.
    # Values < 1.0 increase diversity between estimators.
    "max_samples": [0.5, 1.0],

    # Fraction of features used by each estimator.
    # This helps reduce correlation between trees.
    "max_features": [0.6, 0.8, 0.9],

    
    # Decision Tree (base model)
    
    # Maximum depth of each decision tree.
    "tree_max_depth": [15, 20, 25],

    # Minimum number of samples required at a leaf node.
    # Larger values increase regularization.
    "tree_min_samples_leaf": [1, 5, 10],

    # Minimum number of samples required to split an internal node.
    "tree_min_samples_split": [10, 30, 50]
}



CONFIGS = get_random_configs(N_ITER)

# ---------------------------------------------------------
# 1) K-FOLD
# ---------------------------------------------------------
kf = KFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)

cols_to_normalize = ["Brand", "model", "transmission", "fuelType"]
high_card_features = ["Brand", "model"]
low_card_features  = [c for c in categorical_features if c not in high_card_features]

def _normalize_cats(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    for col in cols_to_normalize:
        if col in df.columns:
            df[col] = fill_unknown(df[col])
            df = column_string_transformer(df, column=col, remove_middle_spaces=True, allow_extra_chars="")
    return df

# ---------------------------------------------------------
# 1.3) EVAL DE 1 CONFIG (métricas em €)
# ---------------------------------------------------------
def eval_one_config(name: str, params: dict) -> dict:
    fold_rows = []

    for fold, (train_idx, val_idx) in enumerate(kf.split(X), start=1):
        X_train = X.iloc[train_idx].copy()
        X_val   = X.iloc[val_idx].copy()
        y_train = y.iloc[train_idx].copy()
        y_val   = y.iloc[val_idx].copy()

        # Treino em log
        y_train_log = np.log1p(y_train)

        # Normalização de strings
        X_train = _normalize_cats(X_train)
        X_val   = _normalize_cats(X_val)

        # Restringir às colunas base
        base_cols = [c for c in (numeric_features + categorical_features) if c in X_train.columns]
        X_train = X_train[base_cols].copy()
        X_val   = X_val[base_cols].copy()

        # Guardrails
        required = ["year", "mileage", "engineSize", "tax", "mpg", "previousOwners", "Brand", "model"]
        missing = [c for c in required if c not in X_train.columns]
        if missing:
            raise KeyError(f"[Fold {fold}] faltam colunas necessárias no pipeline: {missing}")

        # -----------------------------------------------------
        # A) CLEANING
        # -----------------------------------------------------
        year_state = fit_year_median(X_train, year_col="year", model_col="model")
        X_train = transform_year_with_model_median(X_train, state=year_state)
        X_val   = transform_year_with_model_median(X_val,   state=year_state)

        mileage_state = fit_mileage_imputer(X_train, mileage_col="mileage", do_abs=True)
        X_train = transform_mileage_imputer(X_train, state=mileage_state)
        X_val   = transform_mileage_imputer(X_val,   state=mileage_state)

        engine_state = fit_engine_size_imputer(X_train, engine_col="engineSize")
        X_train = transform_engine_size_imputer(X_train, state=engine_state)
        X_val   = transform_engine_size_imputer(X_val,   state=engine_state)

        X_train = transform_tax_custom_rules(X_train, "tax", "year", "fuelType", "engineSize")
        X_val   = transform_tax_custom_rules(X_val,   "tax", "year", "fuelType", "engineSize")

        mpg_state = fit_mpg_imputer(X_train, mpg_col="mpg", do_abs=True)
        X_train = transform_mpg_imputer(X_train, state=mpg_state)
        X_val   = transform_mpg_imputer(X_val,   state=mpg_state)

        owners_state = fit_previous_owners_imputer(X_train, "previousOwners", "year", "mileage")
        X_train = transform_previous_owners_imputer(X_train, state=owners_state)
        X_val   = transform_previous_owners_imputer(X_val,   state=owners_state)

        # -----------------------------------------------------
        # B) RESOLVERS
        # -----------------------------------------------------
        brand_state = fit_ambiguous_brand_resolver(X_train, valid_brands)
        X_train, _, _ = transform_ambiguous_brands(X_train, brand_state)
        X_val,   _, _ = transform_ambiguous_brands(X_val,   brand_state)

        model_state = fit_invalid_model_resolver(X_train, valid_models_by_brand)
        X_train, _, _ = transform_invalid_models(X_train, model_state)
        X_val,   _, _ = transform_invalid_models(X_val,   model_state)

        transm_state = fit_transmission_resolver(X_train, valid_transmissions)
        X_train, _, _ = transform_transmission_resolver(X_train, transm_state)
        X_val,   _, _ = transform_transmission_resolver(X_val,   transm_state)

        fuel_state = fit_fueltype_resolver(X_train, valid_fueltypes)
        X_train, _, _ = transform_fueltype_resolver(X_train, fuel_state)
        X_val,   _, _ = transform_fueltype_resolver(X_val,   fuel_state)

        # -----------------------------------------------------
        # C) FEATURE ENGINEERING
        # -----------------------------------------------------
        X_train = add_owners_flagged(X_train, owners_col="previousOwners", new_col="owners_flagged", drop_original=True)
        X_val   = add_owners_flagged(X_val,   owners_col="previousOwners", new_col="owners_flagged", drop_original=True)

        X_train = create_age_and_drop_year(X_train, year_col="year", base_year=2020)
        X_val   = create_age_and_drop_year(X_val,   year_col="year", base_year=2020)

        X_train = add_mileage_features(X_train, mileage_col="mileage", age_col="age", drop_original=True, drop_ratio=True)
        X_val   = add_mileage_features(X_val,   mileage_col="mileage", age_col="age", drop_original=True, drop_ratio=True)

        X_train = add_engine_bins(X_train, engine_col="engineSize", new_col="engine_bin")
        X_val   = add_engine_bins(X_val,   engine_col="engineSize", new_col="engine_bin")

        X_train["engine_bin"] = X_train["engine_bin"].astype("Int64").astype("string").fillna("UNKNOWN")
        X_val["engine_bin"]   = X_val["engine_bin"].astype("Int64").astype("string").fillna("UNKNOWN")
        low_card_curr = low_card_features + ["engine_bin"]

        # -----------------------------------------------------
        # D) ENCODING
        # -----------------------------------------------------
        te = MyTargetEncoder(smoothing=5)
        te.fit(X_train[high_card_features], y_train_log)
        X_train_high = te.transform(X_train[high_card_features])
        X_val_high   = te.transform(X_val[high_card_features])

        ohe = MyOneHotEncoder()
        ohe.fit(X_train[low_card_curr])
        X_train_low = ohe.transform(X_train[low_card_curr])
        X_val_low   = ohe.transform(X_val[low_card_curr])

        X_train_cat = pd.concat([X_train_high, X_train_low], axis=1)
        X_val_cat   = pd.concat([X_val_high,   X_val_low],   axis=1)

        drop_for_numeric = set(high_card_features + low_card_curr)
        numeric_features_curr = [c for c in X_train.columns if c not in drop_for_numeric]

        X_train_final = pd.concat([X_train[numeric_features_curr], X_train_cat], axis=1)
        X_val_final   = pd.concat([X_val[numeric_features_curr],   X_val_cat],   axis=1)

        if len(numeric_features_curr) > 0:
            scaler = StandardScaler()
            X_train_final[numeric_features_curr] = scaler.fit_transform(X_train_final[numeric_features_curr])
            X_val_final[numeric_features_curr]   = scaler.transform(X_val_final[numeric_features_curr])


        X_val_final = X_val_final.reindex(columns=X_train_final.columns, fill_value=0)

        # -----------------------------------------------------
        # E) TREINO (HGB em log) + PREDIÇÃO (euros) [SEM FS]
        # -----------------------------------------------------
        n_feats = int(X_train_final.shape[1])

        base_tree = DecisionTreeRegressor(
            max_depth=params["tree_max_depth"],
            min_samples_leaf=params["tree_min_samples_leaf"],
            min_samples_split=params["tree_min_samples_split"],
            random_state=RANDOM_STATE
        )

        model = BaggingRegressor(
            estimator=base_tree,
            n_estimators=params["n_estimators"],
            max_samples=params["max_samples"],
            max_features=params["max_features"],
            random_state=RANDOM_STATE,
            n_jobs=-1
        )

        model.fit(X_train_final, y_train_log)


        pred_tr_log  = model.predict(X_train_final)
        pred_val_log = model.predict(X_val_final)

        pred_tr  = np.expm1(pred_tr_log)   # euros
        pred_val = np.expm1(pred_val_log)  # euros

        # -----------------------------------------------------
        # F) MÉTRICAS (euros)
        # -----------------------------------------------------
        fold_rows.append({
            "config": name,
            "fold": fold,
            "n_features": n_feats,

            "train_rmse": rmse(y_train, pred_tr),
            "val_rmse":   rmse(y_val,   pred_val),

            "train_mae": float(mean_absolute_error(y_train, pred_tr)),
            "val_mae":   float(mean_absolute_error(y_val,   pred_val)),

            "train_r2": float(r2_score(y_train, pred_tr)),
            "val_r2":   float(r2_score(y_val,   pred_val)),

            "train_bias": bias(y_train, pred_tr),
            "val_bias":   bias(y_val,   pred_val),
        })

    df_folds = pd.DataFrame(fold_rows)

    out = {
        "config": name,

        "val_rmse_mean": float(df_folds["val_rmse"].mean()),
        "train_rmse_mean": float(df_folds["train_rmse"].mean()),
        "val_mae_mean": float(df_folds["val_mae"].mean()),
        "train_mae_mean": float(df_folds["train_mae"].mean()),
        "val_r2_mean": float(df_folds["val_r2"].mean()),
        "train_r2_mean": float(df_folds["train_r2"].mean()),
        "val_bias_mean": float(df_folds["val_bias"].mean()),
        "train_bias_mean": float(df_folds["train_bias"].mean()),

        "avg_features": float(df_folds["n_features"].mean()),
        **params,
    }

    print(
        f"   >> [{name}] "
        f"VAL RMSE: {out['val_rmse_mean']:.1f} | VAL R2: {out['val_r2_mean']:.4f} | "
        f"VAL MAE: {out['val_mae_mean']:.1f} | VAL Bias: {out['val_bias_mean']:.1f} | "
        f"Feats: {out['avg_features']:.0f}"
    )

    logging.info(
        f"{name} | "
        f"VAL_RMSE={out['val_rmse_mean']:.6f} | VAL_MAE={out['val_mae_mean']:.6f} | "
        f"VAL_R2={out['val_r2_mean']:.6f} | VAL_BIAS={out['val_bias_mean']:.6f} | "
        f"TRAIN_RMSE={out['train_rmse_mean']:.6f} | TRAIN_MAE={out['train_mae_mean']:.6f} | "
        f"Params={params}"
    )

    return out

# ---------------------------------------------------------
# 2) CORRER TODAS AS CONFIGS
# ---------------------------------------------------------
results = []
best_rmse = np.inf
best_row = None

for i, (name, params) in enumerate(CONFIGS):
    if i % 5 == 0:
        print(f"\n-- doing {i+1}/{len(CONFIGS)}")

    res = eval_one_config(name, params)
    results.append(res)

    if res["val_rmse_mean"] < best_rmse:
        best_rmse = res["val_rmse_mean"]
        best_row = res

results_df = pd.DataFrame(results)

# ---------------------------------------------------------
# 3) RESULTADOS FINAIS
# ---------------------------------------------------------
print("\n- TOP 10 Configurations (sorted by VAL RMSE)")
results_df_sorted = results_df.sort_values("val_rmse_mean", ascending=True)

cols_show = [
    "config",
    "val_rmse_mean", "val_mae_mean", "val_r2_mean", "val_bias_mean",
    "train_rmse_mean", "train_mae_mean", "train_r2_mean", "train_bias_mean",
    "avg_features",
    "n_estimators", "max_samples", "max_features",
    "tree_max_depth", "tree_min_samples_leaf", "tree_min_samples_split"
]


display(results_df_sorted[cols_show].head(10))

OUT_CSV = "random_search_fe_results_rmse_no_fs_iter10.csv"
results_df_sorted.to_csv(OUT_CSV, index=False)
print(f"stored at: {OUT_CSV}")
print(f"log in: {LOG_FILE}")

print("\n- BEST CONFIG (by VAL RMSE)")
print(f"Best config name: {best_row['config']}")
print(f"VAL RMSE: {best_row['val_rmse_mean']:.3f}")
print(f"VAL R2:   {best_row['val_r2_mean']:.6f}")
print(f"VAL MAE:  {best_row['val_mae_mean']:.3f}")
print(f"VAL Bias: {best_row['val_bias_mean']:.3f}")
print("Params:")
best_params = {k: best_row[k] for k in param_distributions.keys() if k in best_row}
print(best_params)

-- doing 1/10
   >> [R0_n1000_ms0.5_mf0.6_d25_leaf5_split10] VAL RMSE: 2745.6 | VAL R2: 0.9202 | VAL MAE: 1493.1 | VAL Bias: 363.7 | Feats: 25
   >> [R1_n400_ms0.5_mf0.9_d15_leaf10_split50] VAL RMSE: 2874.8 | VAL R2: 0.9126 | VAL MAE: 1541.2 | VAL Bias: 248.7 | Feats: 25
   >> [R2_n1000_ms0.5_mf0.9_d20_leaf1_split10] VAL RMSE: 2414.7 | VAL R2: 0.9383 | VAL MAE: 1341.1 | VAL Bias: 183.5 | Feats: 25
   >> [R3_n400_ms0.5_mf0.6_d25_leaf10_split10] VAL RMSE: 2934.2 | VAL R2: 0.9090 | VAL MAE: 1573.8 | VAL Bias: 401.9 | Feats: 25
   >> [R4_n1000_ms0.5_mf0.9_d25_leaf10_split50] VAL RMSE: 2871.0 | VAL R2: 0.9128 | VAL MAE: 1536.5 | VAL Bias: 246.8 | Feats: 25

-- doing 6/10
   >> [R5_n600_ms0.5_mf0.8_d25_leaf5_split10] VAL RMSE: 2581.9 | VAL R2: 0.9294 | VAL MAE: 1400.9 | VAL Bias: 233.7 | Feats: 25
   >> [R6_n400_ms1.0_mf0.8_d20_leaf1_split10] VAL RMSE: 2347.5 | VAL R2: 0.9416 | VAL MAE: 1313.1 | VAL Bias: 195.1 | Feats: 25
   >> [R7_n600_ms0.5_mf0.6_d20_leaf1_split30] VAL RMSE: 2770.1 | VAL R2: 0.9188 | VAL MAE: 1519.9 | VAL Bias: 382.9 | Feats: 25
   >> [R8_n600_ms1.0_mf0.6_d25_leaf5_split50] VAL RMSE: 2800.2 | VAL R2: 0.9171 | VAL MAE: 1528.2 | VAL Bias: 385.3 | Feats: 25
   >> [R9_n400_ms1.0_mf0.6_d25_leaf5_split50] VAL RMSE: 2807.3 | VAL R2: 0.9166 | VAL MAE: 1533.9 | VAL Bias: 387.0 | Feats: 25

- TOP 10 Configurations (sorted by VAL RMSE)

,config,val_rmse_mean,val_mae_mean,val_r2_mean,val_bias_mean,train_rmse_mean,train_mae_mean,train_r2_mean,train_bias_mean,avg_features,n_estimators,max_samples,max_features,tree_max_depth,tree_min_samples_leaf,tree_min_samples_split
6,R6_n400_ms1.0_mf0.8_d20_leaf1_split10,2347.545538,1313.142253,0.941632,195.076309,1637.208394,906.496366,0.971723,146.420001,25.0,400,1.0,0.8,20,1,10
2,R2_n1000_ms0.5_mf0.9_d20_leaf1_split10,2414.714660,1341.077636,0.938268,183.465750,1919.152813,1055.990129,0.961148,154.938834,25.0,1000,0.5,0.9,20,1,10
5,R5_n600_ms0.5_mf0.8_d25_leaf5_split10,2581.932108,1400.904876,0.929432,233.730023,2223.987767,1187.074664,0.947827,207.086424,25.0,600,0.5,0.8,25,5,10
0,R0_n1000_ms0.5_mf0.6_d25_leaf5_split10,2745.558650,1493.071840,0.920247,363.745392,2412.782402,1295.067830,0.938594,326.996584,25.0,1000,0.5,0.6,25,5,10
7,R7_n600_ms0.5_mf0.6_d20_leaf1_split30,2770.062860,1519.924146,0.918835,382.866156,2503.764706,1379.961685,0.933874,352.469997,25.0,600,0.5,0.6,20,1,30
8,R8_n600_ms1.0_mf0.6_d25_leaf5_split50,2800.188060,1528.245194,0.917063,385.270489,2562.196385,1398.680003,0.930752,357.610304,25.0,600,1.0,0.6,25,5,50
9,R9_n400_ms1.0_mf0.6_d25_leaf5_split50,2807.316247,1533.858439,0.916642,386.977623,2567.493379,1402.878812,0.930466,358.787944,25.0,400,1.0,0.6,25,5,50
4,R4_n1000_ms0.5_mf0.9_d25_leaf10_split50,2871.010937,1536.475095,0.912829,246.796809,2718.249676,1449.032180,0.922061,234.836560,25.0,1000,0.5,0.9,25,10,50
1,R1_n400_ms0.5_mf0.9_d15_leaf10_split50,2874.818824,1541.157559,0.912601,248.740624,2727.016869,1457.186899,0.921557,237.395435,25.0,400,0.5,0.9,15,10,50
3,R3_n400_ms0.5_mf0.6_d25_leaf10_split10,2934.170630,1573.764474,0.908954,401.852601,2733.868211,1453.637080,0.921163,377.504355,25.0,400,0.5,0.6,25,10,10

stored at: random_search_fe_results_rmse_no_fs_iter10.csv
log in: bagging_fe_no_fs_iter10.log

- BEST CONFIG (by VAL RMSE)
Best config name: R6_n400_ms1.0_mf0.8_d20_leaf1_split10
VAL RMSE: 2347.546
VAL R2:   0.941632
VAL MAE:  1313.142
VAL Bias: 195.076
Params:
{'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.8, 'tree_max_depth': 20, 'tree_min_samples_leaf': 1, 'tree_min_samples_split': 10}

fe com fs -65

In [17]:

N_ITER = 35

FS_KEEP_RATIO = 0.65  # percentagem de features a manter no SelectFromModel

RF_FS_PARAMS = {
    "n_estimators": 500,
    "random_state": RANDOM_STATE,
    "n_jobs": -1,
    "max_depth": None,
    "min_samples_split": 2,
    "min_samples_leaf": 2,
    "max_features": "sqrt",
    "bootstrap": True,
}

# Reprodutibilidade do random search (configs)
random.seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

# ---------------------------------------------------------
# 0.1) LOGGING
# ---------------------------------------------------------
LOG_FILE = "fe_fs_results_rmse_fs65m_iter35.log"
logging.basicConfig(
    filename=LOG_FILE,
    level=logging.INFO,
    format="%(asctime)s - %(message)s",
    filemode="w",
    force=True
)
logging.info(f"- {N_ITER} iterations | {N_SPLITS}-fold | FS_KEEP_RATIO={FS_KEEP_RATIO}")

# ---------------------------------------------------------
# 0.2) RANDOM SEARCH
# ---------------------------------------------------------
param_distributions = {

    # Bagging (ensemble-level)
    
    # Number of trees in the ensemble.
    # Higher values usually improve stability but increase training time.
    "n_estimators": [400, 600,1000],

    # Fraction of samples used to train each tree.
    # Values < 1.0 increase diversity between estimators.
    "max_samples": [0.5, 1.0],

    # Fraction of features used by each estimator.
    # This helps reduce correlation between trees.
    "max_features": [0.6, 0.8, 0.9],

    
    # Decision Tree (base model)
    
    # Maximum depth of each decision tree.
    "tree_max_depth": [15, 20, 25],

    # Minimum number of samples required at a leaf node.
    # Larger values increase regularization.
    "tree_min_samples_leaf": [1, 5, 10],

    # Minimum number of samples required to split an internal node.
    "tree_min_samples_split": [10, 30, 50]

}

def get_random_configs(n_iter: int):
    configs = []
    keys = list(param_distributions.keys())

    for i in range(n_iter):
        params = {k: random.choice(list(param_distributions[k])) for k in keys}

        name = (
            f"R{i}_n{params['n_estimators']}"
            f"_ms{params['max_samples']}"
            f"_mf{params['max_features']}"
            f"_d{params['tree_max_depth']}"
            f"_leaf{params['tree_min_samples_leaf']}"
            f"_split{params['tree_min_samples_split']}"
        )

        configs.append((name, params))
    return configs

CONFIGS = get_random_configs(N_ITER)

# ---------------------------------------------------------
# 1) K-FOLD
# ---------------------------------------------------------
kf = KFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)

# Assume que já tens no notebook:
# - X, y
# - numeric_features, categorical_features
# - fill_unknown, column_string_transformer
# - fit_* e transform_* (os teus passos)
# - valid_brands, valid_models_by_brand, valid_transmissions, valid_fueltypes
# - MyTargetEncoder, MyOneHotEncoder

cols_to_normalize = ["Brand", "model", "transmission", "fuelType"]
high_card_features = ["Brand", "model"]
low_card_features  = [c for c in categorical_features if c not in high_card_features]


# ---------------------------------------------------------
# 1.3) EVAL DE 1 CONFIG (métricas em €)
# ---------------------------------------------------------
def eval_one_config(name: str, params: dict) -> dict:
    fold_rows = []

    for fold, (train_idx, val_idx) in enumerate(kf.split(X), start=1):
        X_train = X.iloc[train_idx].copy()
        X_val   = X.iloc[val_idx].copy()
        y_train = y.iloc[train_idx].copy()
        y_val   = y.iloc[val_idx].copy()

        # Treino em log
        y_train_log = np.log1p(y_train)

        # Normalização de strings
        X_train = _normalize_cats(X_train)
        X_val   = _normalize_cats(X_val)

        # Restringir às colunas base
        base_cols = [c for c in (numeric_features + categorical_features) if c in X_train.columns]
        X_train = X_train[base_cols].copy()
        X_val   = X_val[base_cols].copy()

        # Guardrails (evita KeyError silencioso)
        required = ["year", "mileage", "engineSize", "tax", "mpg", "previousOwners", "Brand", "model"]
        missing = [c for c in required if c not in X_train.columns]
        if missing:
            raise KeyError(f"[Fold {fold}] faltam colunas necessárias no pipeline: {missing}")

        # -----------------------------------------------------
        # A) CLEANING
        # -----------------------------------------------------
        year_state = fit_year_median(X_train, year_col="year", model_col="model")
        X_train = transform_year_with_model_median(X_train, state=year_state)
        X_val   = transform_year_with_model_median(X_val,   state=year_state)

        mileage_state = fit_mileage_imputer(X_train, mileage_col="mileage", do_abs=True)
        X_train = transform_mileage_imputer(X_train, state=mileage_state)
        X_val   = transform_mileage_imputer(X_val,   state=mileage_state)

        engine_state = fit_engine_size_imputer(X_train, engine_col="engineSize")
        X_train = transform_engine_size_imputer(X_train, state=engine_state)
        X_val   = transform_engine_size_imputer(X_val,   state=engine_state)

        X_train = transform_tax_custom_rules(X_train, "tax", "year", "fuelType", "engineSize")
        X_val   = transform_tax_custom_rules(X_val,   "tax", "year", "fuelType", "engineSize")

        mpg_state = fit_mpg_imputer(X_train, mpg_col="mpg", do_abs=True)
        X_train = transform_mpg_imputer(X_train, state=mpg_state)
        X_val   = transform_mpg_imputer(X_val,   state=mpg_state)

        owners_state = fit_previous_owners_imputer(X_train, "previousOwners", "year", "mileage")
        X_train = transform_previous_owners_imputer(X_train, state=owners_state)
        X_val   = transform_previous_owners_imputer(X_val,   state=owners_state)

        # -----------------------------------------------------
        # B) RESOLVERS
        # -----------------------------------------------------
        brand_state = fit_ambiguous_brand_resolver(X_train, valid_brands)
        X_train, _, _ = transform_ambiguous_brands(X_train, brand_state)
        X_val,   _, _ = transform_ambiguous_brands(X_val,   brand_state)

        model_state = fit_invalid_model_resolver(X_train, valid_models_by_brand)
        X_train, _, _ = transform_invalid_models(X_train, model_state)
        X_val,   _, _ = transform_invalid_models(X_val,   model_state)

        transm_state = fit_transmission_resolver(X_train, valid_transmissions)
        X_train, _, _ = transform_transmission_resolver(X_train, transm_state)
        X_val,   _, _ = transform_transmission_resolver(X_val,   transm_state)

        fuel_state = fit_fueltype_resolver(X_train, valid_fueltypes)
        X_train, _, _ = transform_fueltype_resolver(X_train, fuel_state)
        X_val,   _, _ = transform_fueltype_resolver(X_val,   fuel_state)

        # -----------------------------------------------------
        # C) FEATURE ENGINEERING
        # -----------------------------------------------------
        X_train = add_owners_flagged(X_train, owners_col="previousOwners", new_col="owners_flagged", drop_original=True)
        X_val   = add_owners_flagged(X_val,   owners_col="previousOwners", new_col="owners_flagged", drop_original=True)

        X_train = create_age_and_drop_year(X_train, year_col="year", base_year=2020)
        X_val   = create_age_and_drop_year(X_val,   year_col="year", base_year=2020)

        X_train = add_mileage_features(X_train, mileage_col="mileage", age_col="age", drop_original=True, drop_ratio=True)
        X_val   = add_mileage_features(X_val,   mileage_col="mileage", age_col="age", drop_original=True, drop_ratio=True)

        X_train = add_engine_bins(X_train, engine_col="engineSize", new_col="engine_bin")
        X_val   = add_engine_bins(X_val,   engine_col="engineSize", new_col="engine_bin")

        X_train["engine_bin"] = X_train["engine_bin"].astype("Int64").astype("string").fillna("UNKNOWN")
        X_val["engine_bin"]   = X_val["engine_bin"].astype("Int64").astype("string").fillna("UNKNOWN")
        low_card_curr = low_card_features + ["engine_bin"]

        # -----------------------------------------------------
        # D) ENCODING
        # -----------------------------------------------------
        te = MyTargetEncoder(smoothing=5)
        te.fit(X_train[high_card_features], y_train_log)
        X_train_high = te.transform(X_train[high_card_features])
        X_val_high   = te.transform(X_val[high_card_features])

        ohe = MyOneHotEncoder()
        ohe.fit(X_train[low_card_curr])
        X_train_low = ohe.transform(X_train[low_card_curr])
        X_val_low   = ohe.transform(X_val[low_card_curr])

        X_train_cat = pd.concat([X_train_high, X_train_low], axis=1)
        X_val_cat   = pd.concat([X_val_high,   X_val_low],   axis=1)

        drop_for_numeric = set(high_card_features + low_card_curr)
        numeric_features_curr = [c for c in X_train.columns if c not in drop_for_numeric]

        X_train_final = pd.concat([X_train[numeric_features_curr], X_train_cat], axis=1)
        X_val_final   = pd.concat([X_val[numeric_features_curr],   X_val_cat],   axis=1)

        if len(numeric_features_curr) > 0:
            scaler = StandardScaler()
            X_train_final[numeric_features_curr] = scaler.fit_transform(X_train_final[numeric_features_curr])
            X_val_final[numeric_features_curr]   = scaler.transform(X_val_final[numeric_features_curr])

        X_val_final = X_val_final.reindex(columns=X_train_final.columns, fill_value=0)

        # -----------------------------------------------------
        # D.1) FEATURE SELECTION (RF + SelectFromModel)
        # -----------------------------------------------------
        n_feats = X_train_final.shape[1]
        k = int(np.ceil(FS_KEEP_RATIO * n_feats))
        k = max(1, min(k, n_feats))

        rf_fs = RandomForestRegressor(**RF_FS_PARAMS)
        rf_fs.fit(X_train_final, y_train_log)

        selector = SelectFromModel(
            estimator=rf_fs,
            threshold=-np.inf,
            max_features=k,
            prefit=True
        )

        selected_cols = X_train_final.columns[selector.get_support()]
        X_train_sel = X_train_final[selected_cols]
        X_val_sel   = X_val_final[selected_cols]

        # -----------------------------------------------------
        # E) TREINO (HGB em log) + PREDIÇÃO (euros)
        # -----------------------------------------------------
        base_tree = DecisionTreeRegressor(
            max_depth=params["tree_max_depth"],
            min_samples_leaf=params["tree_min_samples_leaf"],
            min_samples_split=params["tree_min_samples_split"],
            random_state=RANDOM_STATE
        )

        model = BaggingRegressor(
            estimator=base_tree,
            n_estimators=params["n_estimators"],
            max_samples=params["max_samples"],
            max_features=params["max_features"],
            random_state=RANDOM_STATE,
            n_jobs=-1
        )

        model.fit(X_train_sel, y_train_log)

        pred_tr_log  = model.predict(X_train_sel)
        pred_val_log = model.predict(X_val_sel)

        pred_tr  = np.expm1(pred_tr_log)   # euros
        pred_val = np.expm1(pred_val_log)  # euros

        # -----------------------------------------------------
        # F) MÉTRICAS (euros)
        # -----------------------------------------------------
        rmse_tr = rmse(y_train, pred_tr)
        rmse_val = rmse(y_val, pred_val)

        mae_tr = float(mean_absolute_error(y_train, pred_tr))
        mae_val = float(mean_absolute_error(y_val, pred_val))

        r2_tr = float(r2_score(y_train, pred_tr))
        r2_val = float(r2_score(y_val, pred_val))

        bias_tr = bias(y_train, pred_tr)
        bias_val = bias(y_val, pred_val)

        fold_rows.append({
            "config": name,
            "fold": fold,
            "n_features_total": int(n_feats),
            "n_features_selected": int(len(selected_cols)),

            "train_rmse": rmse_tr,
            "val_rmse": rmse_val,
            "train_mae": mae_tr,
            "val_mae": mae_val,
            "train_r2": r2_tr,
            "val_r2": r2_val,
            "train_bias": bias_tr,
            "val_bias": bias_val,
        })

    df_folds = pd.DataFrame(fold_rows)

    out = {
        "config": name,

        "val_rmse_mean": float(df_folds["val_rmse"].mean()),
        "train_rmse_mean": float(df_folds["train_rmse"].mean()),
        "val_mae_mean": float(df_folds["val_mae"].mean()),
        "train_mae_mean": float(df_folds["train_mae"].mean()),
        "val_r2_mean": float(df_folds["val_r2"].mean()),
        "train_r2_mean": float(df_folds["train_r2"].mean()),
        "val_bias_mean": float(df_folds["val_bias"].mean()),
        "train_bias_mean": float(df_folds["train_bias"].mean()),

        "avg_selected_features": float(df_folds["n_features_selected"].mean()),
        "avg_total_features": float(df_folds["n_features_total"].mean()),
        **params,
    }

    print(
        f"   >> [{name}] "
        f"VAL RMSE: {out['val_rmse_mean']:.1f} | VAL R2: {out['val_r2_mean']:.4f} | "
        f"VAL MAE: {out['val_mae_mean']:.1f} | VAL Bias: {out['val_bias_mean']:.1f} | "
        f"Sel: {out['avg_selected_features']:.0f} feats"
    )

    logging.info(
        f"{name} | "
        f"VAL_RMSE={out['val_rmse_mean']:.6f} | VAL_MAE={out['val_mae_mean']:.6f} | "
        f"VAL_R2={out['val_r2_mean']:.6f} | VAL_BIAS={out['val_bias_mean']:.6f} | "
        f"TRAIN_RMSE={out['train_rmse_mean']:.6f} | TRAIN_MAE={out['train_mae_mean']:.6f} | "
        f"SelAvg={out['avg_selected_features']:.3f} | Params={params}"
    )

    return out

# ---------------------------------------------------------
# 2) CORRER TODAS AS CONFIGS
# ---------------------------------------------------------
results = []
best_rmse = np.inf
best_row = None

for i, (name, params) in enumerate(CONFIGS):
    if i % 5 == 0:
        print(f"\n-- doing {i+1}/{len(CONFIGS)}")

    res = eval_one_config(name, params)
    results.append(res)

    if res["val_rmse_mean"] < best_rmse:
        best_rmse = res["val_rmse_mean"]
        best_row = res

results_df = pd.DataFrame(results)

# ---------------------------------------------------------
# 3) RESULTADOS FINAIS
# ---------------------------------------------------------
print("\n- TOP 10 Configurations (sorted by VAL RMSE)")
results_df_sorted = results_df.sort_values("val_rmse_mean", ascending=True)

cols_show = [
    "config",
    "val_rmse_mean", "val_mae_mean", "val_r2_mean", "val_bias_mean",
    "train_rmse_mean", "train_mae_mean", "train_r2_mean", "train_bias_mean",
    "avg_selected_features",
    "n_estimators", "max_samples", "max_features",
    "tree_max_depth", "tree_min_samples_leaf", "tree_min_samples_split"
]

display(results_df_sorted[cols_show].head(10))

OUT_CSV = "random_search_fe_fs_results_rmse_fs65m_iter35.csv"
results_df_sorted.to_csv(OUT_CSV, index=False)
print(f"stored at: {OUT_CSV}")
print(f"log in: {LOG_FILE}")

print("\n- BEST CONFIG (by VAL RMSE)")
print(f"Best config name: {best_row['config']}")
print(f"VAL RMSE: {best_row['val_rmse_mean']:.3f}")
print(f"VAL R2:   {best_row['val_r2_mean']:.6f}")
print(f"VAL MAE:  {best_row['val_mae_mean']:.3f}")
print(f"VAL Bias: {best_row['val_bias_mean']:.3f}")
print("Params:")
best_params = {k: best_row[k] for k in param_distributions.keys() if k in best_row}
print(best_params)

-- doing 1/35
   >> [R0_n1000_ms0.5_mf0.6_d25_leaf5_split10] VAL RMSE: 2814.0 | VAL R2: 0.9162 | VAL MAE: 1510.5 | VAL Bias: 375.6 | Sel: 17 feats
   >> [R1_n400_ms0.5_mf0.9_d15_leaf10_split50] VAL RMSE: 2891.7 | VAL R2: 0.9116 | VAL MAE: 1547.0 | VAL Bias: 243.3 | Sel: 17 feats
   >> [R2_n1000_ms0.5_mf0.9_d20_leaf1_split10] VAL RMSE: 2425.0 | VAL R2: 0.9377 | VAL MAE: 1341.5 | VAL Bias: 179.3 | Sel: 17 feats
   >> [R3_n400_ms0.5_mf0.6_d25_leaf10_split10] VAL RMSE: 2979.2 | VAL R2: 0.9061 | VAL MAE: 1583.2 | VAL Bias: 397.8 | Sel: 17 feats
   >> [R4_n1000_ms0.5_mf0.9_d25_leaf10_split50] VAL RMSE: 2887.8 | VAL R2: 0.9118 | VAL MAE: 1541.9 | VAL Bias: 243.4 | Sel: 17 feats

-- doing 6/35
   >> [R5_n600_ms0.5_mf0.8_d25_leaf5_split10] VAL RMSE: 2597.7 | VAL R2: 0.9286 | VAL MAE: 1403.7 | VAL Bias: 236.8 | Sel: 17 feats
   >> [R6_n400_ms1.0_mf0.8_d20_leaf1_split10] VAL RMSE: 2366.6 | VAL R2: 0.9407 | VAL MAE: 1318.2 | VAL Bias: 199.2 | Sel: 17 feats
   >> [R7_n600_ms0.5_mf0.6_d20_leaf1_split30] VAL RMSE: 2833.9 | VAL R2: 0.9151 | VAL MAE: 1531.1 | VAL Bias: 384.9 | Sel: 17 feats
   >> [R8_n600_ms1.0_mf0.6_d25_leaf5_split50] VAL RMSE: 2859.1 | VAL R2: 0.9136 | VAL MAE: 1538.4 | VAL Bias: 387.6 | Sel: 17 feats
   >> [R9_n400_ms1.0_mf0.6_d25_leaf5_split50] VAL RMSE: 2869.4 | VAL R2: 0.9129 | VAL MAE: 1546.7 | VAL Bias: 385.8 | Sel: 17 feats

-- doing 11/35
   >> [R10_n1000_ms1.0_mf0.9_d15_leaf10_split10] VAL RMSE: 2637.6 | VAL R2: 0.9264 | VAL MAE: 1430.3 | VAL Bias: 201.0 | Sel: 17 feats
   >> [R11_n400_ms0.5_mf0.8_d15_leaf1_split10] VAL RMSE: 2499.3 | VAL R2: 0.9339 | VAL MAE: 1390.6 | VAL Bias: 233.1 | Sel: 17 feats
   >> [R12_n600_ms1.0_mf0.8_d25_leaf5_split10] VAL RMSE: 2474.5 | VAL R2: 0.9352 | VAL MAE: 1355.1 | VAL Bias: 213.0 | Sel: 17 feats
   >> [R13_n600_ms1.0_mf0.6_d25_leaf5_split50] VAL RMSE: 2859.1 | VAL R2: 0.9136 | VAL MAE: 1538.4 | VAL Bias: 387.6 | Sel: 17 feats
   >> [R14_n1000_ms0.5_mf0.9_d25_leaf1_split50] VAL RMSE: 2741.4 | VAL R2: 0.9205 | VAL MAE: 1497.9 | VAL Bias: 232.0 | Sel: 17 feats

-- doing 16/35
   >> [R15_n1000_ms0.5_mf0.6_d20_leaf5_split30] VAL RMSE: 2924.8 | VAL R2: 0.9095 | VAL MAE: 1562.7 | VAL Bias: 401.4 | Sel: 17 feats
   >> [R16_n1000_ms0.5_mf0.9_d20_leaf1_split10] VAL RMSE: 2425.0 | VAL R2: 0.9377 | VAL MAE: 1341.5 | VAL Bias: 179.3 | Sel: 17 feats
   >> [R17_n400_ms1.0_mf0.8_d20_leaf1_split10] VAL RMSE: 2366.6 | VAL R2: 0.9407 | VAL MAE: 1318.2 | VAL Bias: 199.2 | Sel: 17 feats
   >> [R18_n1000_ms1.0_mf0.6_d25_leaf5_split30] VAL RMSE: 2789.1 | VAL R2: 0.9177 | VAL MAE: 1503.6 | VAL Bias: 374.2 | Sel: 17 feats
   >> [R19_n1000_ms1.0_mf0.6_d20_leaf1_split10] VAL RMSE: 2580.9 | VAL R2: 0.9295 | VAL MAE: 1420.9 | VAL Bias: 333.1 | Sel: 17 feats

-- doing 21/35
   >> [R20_n1000_ms1.0_mf0.9_d25_leaf5_split50] VAL RMSE: 2646.2 | VAL R2: 0.9259 | VAL MAE: 1443.3 | VAL Bias: 210.1 | Sel: 17 feats
   >> [R21_n600_ms1.0_mf0.6_d15_leaf10_split30] VAL RMSE: 2873.4 | VAL R2: 0.9127 | VAL MAE: 1539.4 | VAL Bias: 385.5 | Sel: 17 feats
   >> [R22_n400_ms0.5_mf0.6_d15_leaf10_split10] VAL RMSE: 2985.7 | VAL R2: 0.9057 | VAL MAE: 1590.1 | VAL Bias: 400.8 | Sel: 17 feats
   >> [R23_n1000_ms1.0_mf0.9_d15_leaf5_split30] VAL RMSE: 2572.5 | VAL R2: 0.9300 | VAL MAE: 1414.2 | VAL Bias: 198.7 | Sel: 17 feats
   >> [R24_n1000_ms1.0_mf0.9_d20_leaf10_split10] VAL RMSE: 2623.2 | VAL R2: 0.9272 | VAL MAE: 1415.5 | VAL Bias: 196.1 | Sel: 17 feats

-- doing 26/35
   >> [R25_n1000_ms0.5_mf0.9_d25_leaf5_split50] VAL RMSE: 2807.6 | VAL R2: 0.9166 | VAL MAE: 1514.7 | VAL Bias: 237.8 | Sel: 17 feats
   >> [R26_n600_ms0.5_mf0.8_d20_leaf1_split30] VAL RMSE: 2628.9 | VAL R2: 0.9269 | VAL MAE: 1435.7 | VAL Bias: 252.9 | Sel: 17 feats
   >> [R27_n400_ms1.0_mf0.9_d15_leaf10_split10] VAL RMSE: 2635.7 | VAL R2: 0.9265 | VAL MAE: 1431.1 | VAL Bias: 199.7 | Sel: 17 feats
   >> [R28_n1000_ms1.0_mf0.9_d25_leaf10_split10] VAL RMSE: 2623.1 | VAL R2: 0.9272 | VAL MAE: 1415.3 | VAL Bias: 196.0 | Sel: 17 feats
   >> [R29_n400_ms1.0_mf0.6_d25_leaf10_split10] VAL RMSE: 2844.5 | VAL R2: 0.9144 | VAL MAE: 1524.6 | VAL Bias: 372.5 | Sel: 17 feats

-- doing 31/35
   >> [R30_n1000_ms1.0_mf0.8_d15_leaf1_split30] VAL RMSE: 2540.6 | VAL R2: 0.9317 | VAL MAE: 1406.7 | VAL Bias: 238.2 | Sel: 17 feats
   >> [R31_n600_ms0.5_mf0.6_d15_leaf10_split10] VAL RMSE: 2976.6 | VAL R2: 0.9063 | VAL MAE: 1582.1 | VAL Bias: 402.5 | Sel: 17 feats
   >> [R32_n400_ms1.0_mf0.6_d25_leaf1_split10] VAL RMSE: 2574.3 | VAL R2: 0.9299 | VAL MAE: 1419.3 | VAL Bias: 323.5 | Sel: 17 feats
   >> [R33_n1000_ms1.0_mf0.9_d15_leaf5_split50] VAL RMSE: 2661.0 | VAL R2: 0.9251 | VAL MAE: 1458.0 | VAL Bias: 213.7 | Sel: 17 feats
   >> [R34_n1000_ms1.0_mf0.6_d25_leaf10_split50] VAL RMSE: 2946.2 | VAL R2: 0.9082 | VAL MAE: 1569.0 | VAL Bias: 402.7 | Sel: 17 feats

- TOP 10 Configurations (sorted by VAL RMSE)

,config,val_rmse_mean,val_mae_mean,val_r2_mean,val_bias_mean,train_rmse_mean,train_mae_mean,train_r2_mean,train_bias_mean,avg_selected_features,n_estimators,max_samples,max_features,tree_max_depth,tree_min_samples_leaf,tree_min_samples_split
6,R6_n400_ms1.0_mf0.8_d20_leaf1_split10,2366.552980,1318.158411,0.940700,199.181311,1659.433598,915.789403,0.970951,150.911821,17.0,400,1.0,0.8,20,1,10
17,R17_n400_ms1.0_mf0.8_d20_leaf1_split10,2366.552980,1318.158411,0.940700,199.181311,1659.433598,915.789403,0.970951,150.911821,17.0,400,1.0,0.8,20,1,10
16,R16_n1000_ms0.5_mf0.9_d20_leaf1_split10,2425.043680,1341.480889,0.937744,179.297515,1924.492980,1057.702758,0.960932,152.457545,17.0,1000,0.5,0.9,20,1,10
2,R2_n1000_ms0.5_mf0.9_d20_leaf1_split10,2425.043680,1341.480889,0.937744,179.297515,1924.492980,1057.702758,0.960932,152.457545,17.0,1000,0.5,0.9,20,1,10
12,R12_n600_ms1.0_mf0.8_d25_leaf5_split10,2474.495619,1355.077072,0.935182,212.980919,1962.126325,1045.905490,0.959388,176.857948,17.0,600,1.0,0.8,25,5,10
11,R11_n400_ms0.5_mf0.8_d15_leaf1_split10,2499.297905,1390.631193,0.933892,233.105575,2089.422789,1183.755216,0.953950,203.652414,17.0,400,0.5,0.8,15,1,10
30,R30_n1000_ms1.0_mf0.8_d15_leaf1_split30,2540.633471,1406.687544,0.931699,238.200384,2178.778095,1230.915929,0.949926,211.626929,17.0,1000,1.0,0.8,15,1,30
23,R23_n1000_ms1.0_mf0.9_d15_leaf5_split30,2572.460182,1414.220643,0.929968,198.668002,2254.410535,1248.946769,0.946389,178.459178,17.0,1000,1.0,0.9,15,5,30
32,R32_n400_ms1.0_mf0.6_d25_leaf1_split10,2574.276971,1419.281640,0.929889,323.468683,1851.734144,1002.515404,0.963829,246.935555,17.0,400,1.0,0.6,25,1,10
19,R19_n1000_ms1.0_mf0.6_d20_leaf1_split10,2580.889864,1420.864744,0.929539,333.084072,1887.876525,1037.330722,0.962404,259.152363,17.0,1000,1.0,0.6,20,1,10

stored at: random_search_fe_fs_results_rmse_fs65m_iter35.csv
log in: fe_fs_results_rmse_fs65m_iter35.log

- BEST CONFIG (by VAL RMSE)
Best config name: R6_n400_ms1.0_mf0.8_d20_leaf1_split10
VAL RMSE: 2366.553
VAL R2:   0.940700
VAL MAE:  1318.158
VAL Bias: 199.181
Params:
{'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.8, 'tree_max_depth': 20, 'tree_min_samples_leaf': 1, 'tree_min_samples_split': 10}

age, no prev, log price - no fs

In [18]:
# numeric features used by the model (year is replaced by age; previousOwners is excluded)
numeric_features = ["mileage", "engineSize", "tax", "mpg", "age"]

# shuffles the data, in order to (at least theoretically) have more balanced folds
# we will use an 8-fold cross-validation strategy
kf = KFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)

# we explicitly exclude this feature from the model input
DROP_FROM_MODEL = ["previousOwners"]

# hyperparameter space that we are going to use for random search
# each configuration will get 1 value from each of these lists
param_distributions = {

    # Bagging (ensemble-level)
    
    # Number of trees in the ensemble.
    # Higher values usually improve stability but increase training time.
    "n_estimators": [400,1000,1200],

    # Fraction of samples used to train each tree.
    # Values < 1.0 increase diversity between estimators.
    "max_samples": [0.5, 1.0],

    # Fraction of features used by each estimator.
    # This helps reduce correlation between trees.
    "max_features": [0.6, 0.8, 0.9],
    
    # Decision Tree (base model)
    
    # Maximum depth of each decision tree.
    "tree_max_depth": [15, 20, 25],

    # Minimum number of samples required at a leaf node.
    # Larger values increase regularization.
    "tree_min_samples_leaf": [1, 5, 10],

    # Minimum number of samples required to split an internal node.
    "tree_min_samples_split": [10, 30, 50]

}

N_RANDOM_CONFIGS = 15  # short random search, enough for baseline results

# we get N_RANDOM_CONFIGS random parameter combinations from param_distributions
sampler = ParameterSampler(param_distributions, n_iter=N_RANDOM_CONFIGS, random_state=RANDOM_STATE)

search_results = []  # stores results for ranking
best_rmse = np.inf
best_config = None

# log setup (mainly for development and traceability)
log_path = "baging_noowners_age_logprice_log2.txt"


# Note: this section is included mainly for organizational purposes
with open(log_path, "w", encoding="utf-8") as log_file:

    def log(msg: str):
        print(msg)
        log_file.write(msg + "\n")
        log_file.flush()

    log("# =============================")
    log("# START OF BG+DT SEARCH (LOG TARGET + AGE FEATURE)")
    log("# METRICS ON ORIGINAL SCALE: R2, RMSE, MAE, BIAS")
    log(f"# LOG FILE SAVED TO: {log_path}")
    log("# =============================")

    for config_id, params in enumerate(sampler, start=1):
        log("")
        log(f"######## CONFIG {config_id}/{N_RANDOM_CONFIGS} ########")
        log(f"Parameters: {params}")

        fold_rmses_val, fold_maes_val, fold_r2s_val, fold_bias_val = [], [], [], []
        fold_rmses_tr,  fold_maes_tr,  fold_r2s_tr,  fold_bias_tr  = [], [], [], []
        fold_med_ae = []

        for fold, (train_idx, val_idx) in enumerate(kf.split(X), start=1):

            X_train, X_val = X.iloc[train_idx].copy(), X.iloc[val_idx].copy()
            y_train, y_val = y.iloc[train_idx].copy(), y.iloc[val_idx].copy()

            # log-transform target for training
            y_train_log = np.log1p(y_train)

            log(f"\n[C{config_id}|F{fold}] Processing fold...")

            # -> Preprocessing steps (fit only on training fold, apply to both)
            year_state = fit_year_median(X_train, year_col="year", model_col="model")
            X_train = transform_year_with_model_median(X_train, state=year_state)
            X_val   = transform_year_with_model_median(X_val,   state=year_state)

            mileage_state = fit_mileage_imputer(X_train, mileage_col="mileage", do_abs=True)
            X_train = transform_mileage_imputer(X_train, state=mileage_state)
            X_val   = transform_mileage_imputer(X_val,   state=mileage_state)

            engine_state = fit_engine_size_imputer(X_train, engine_col="engineSize")
            X_train = transform_engine_size_imputer(X_train, state=engine_state)
            X_val   = transform_engine_size_imputer(X_val,   state=engine_state)

            X_train = transform_tax_custom_rules(X_train, "tax", "year", "fuelType", "engineSize")
            X_val   = transform_tax_custom_rules(X_val,   "tax", "year", "fuelType", "engineSize")

            mpg_state = fit_mpg_imputer(X_train, mpg_col="mpg", do_abs=True)
            X_train = transform_mpg_imputer(X_train, state=mpg_state)
            X_val   = transform_mpg_imputer(X_val,   state=mpg_state)

            brand_state = fit_ambiguous_brand_resolver(X_train, valid_brands)
            X_train, _, _ = transform_ambiguous_brands(X_train, brand_state)
            X_val,   _, _ = transform_ambiguous_brands(X_val,   brand_state)

            model_state = fit_invalid_model_resolver(X_train, valid_models_by_brand)
            X_train, _, _ = transform_invalid_models(X_train, model_state)
            X_val,   _, _ = transform_invalid_models(X_val,   model_state)

            transm_state = fit_transmission_resolver(X_train, valid_transmissions)
            X_train, _, _ = transform_transmission_resolver(X_train, transm_state)
            X_val,   _, _ = transform_transmission_resolver(X_val,   transm_state)

            fuel_state = fit_fueltype_resolver(X_train, valid_fueltypes)
            X_train, _, _ = transform_fueltype_resolver(X_train, fuel_state)
            X_val,   _, _ = transform_fueltype_resolver(X_val,   fuel_state)

            # -> Feature engineering: create age and drop year (do this after all year-based steps)
            X_train = create_age_and_drop_year(X_train, year_col="year", base_year=2020)
            X_val   = create_age_and_drop_year(X_val,   year_col="year", base_year=2020)

            # hard guarantee: previousOwners is not used by the model
            X_train = X_train.drop(columns=DROP_FROM_MODEL, errors="ignore")
            X_val   = X_val.drop(columns=DROP_FROM_MODEL, errors="ignore")

            # -> Feature encoding (categorical only)
            high_card_features = ["Brand", "model"]
            low_card_features  = [c for c in categorical_features if c not in high_card_features]

            te = MyTargetEncoder(smoothing=5)
            te.fit(X_train[high_card_features], y_train_log)  # fit using log-target
            X_train_high = te.transform(X_train[high_card_features])
            X_val_high   = te.transform(X_val[high_card_features])

            ohe = MyOneHotEncoder()
            ohe.fit(X_train[low_card_features])
            X_train_low = ohe.transform(X_train[low_card_features])
            X_val_low   = ohe.transform(X_val[low_card_features])

            X_train_cat = pd.concat([X_train_high, X_train_low], axis=1)
            X_val_cat   = pd.concat([X_val_high,   X_val_low],   axis=1)

            # join numerical and categorical (encoded) features
            X_train_final = pd.concat([X_train[numeric_features], X_train_cat], axis=1)
            X_val_final   = pd.concat([X_val[numeric_features],   X_val_cat],   axis=1)

            if len(numeric_features) > 0:
                scaler = StandardScaler()
                X_train_final[numeric_features] = scaler.fit_transform(X_train_final[numeric_features])
                X_val_final[numeric_features]   = scaler.transform(X_val_final[numeric_features])

            # align columns to avoid mismatch due to encoding
            X_val_final = X_val_final.reindex(columns=X_train_final.columns, fill_value=0)

            if fold == 1:
                feature_names = list(X_train_final.columns)
                log(f"  > Features Used ({len(feature_names)}): {feature_names}")

            # -> Model training (train on log-target)
            base_tree = DecisionTreeRegressor(
                max_depth=params["tree_max_depth"],
                min_samples_leaf=params["tree_min_samples_leaf"],
                min_samples_split=params["tree_min_samples_split"],
                random_state=RANDOM_STATE
            )

            model = BaggingRegressor(
                estimator=base_tree,
                n_estimators=params["n_estimators"],
                max_samples=params["max_samples"],
                max_features=params["max_features"],
                random_state=RANDOM_STATE,
                n_jobs=-1
            )

            model.fit(X_train_final, y_train_log)

            # predictions (log scale), then invert to original scale
            y_pred_train_log = model.predict(X_train_final)
            y_pred_val_log   = model.predict(X_val_final)

            y_pred_train = np.expm1(y_pred_train_log)
            y_pred_val   = np.expm1(y_pred_val_log)

            # -> Metrics on original scale
            mae_tr  = mean_absolute_error(y_train, y_pred_train)
            rmse_tr = np.sqrt(mean_squared_error(y_train, y_pred_train))
            r2_tr   = r2_score(y_train, y_pred_train)
            bias_tr = np.mean(y_train - y_pred_train)

            mae_val  = mean_absolute_error(y_val, y_pred_val)
            rmse_val = np.sqrt(mean_squared_error(y_val, y_pred_val))
            r2_val   = r2_score(y_val, y_pred_val)
            bias_val = np.mean(y_val - y_pred_val)

            med_ae_val = median_absolute_error(y_val, y_pred_val)

            log(f"  > [TRAIN] R2: {r2_tr:.4f} | RMSE: {rmse_tr:.0f} | MAE: {mae_tr:.0f} | Bias: {bias_tr:.1f}")
            log(f"  > [VAL]   R2: {r2_val:.4f} | RMSE: {rmse_val:.0f} | MAE: {mae_val:.0f} | Bias: {bias_val:.1f}")

            fold_maes_tr.append(mae_tr);   fold_rmses_tr.append(rmse_tr);   fold_r2s_tr.append(r2_tr);   fold_bias_tr.append(bias_tr)
            fold_maes_val.append(mae_val); fold_rmses_val.append(rmse_val); fold_r2s_val.append(r2_val); fold_bias_val.append(bias_val)
            fold_med_ae.append(med_ae_val)

        mean_rmse_val = np.mean(fold_rmses_val)
        mean_mae_val  = np.mean(fold_maes_val)
        mean_r2_val   = np.mean(fold_r2s_val)
        mean_bias_val = np.mean(fold_bias_val)

        mean_mae_tr   = np.mean(fold_maes_tr)
        mean_r2_tr    = np.mean(fold_r2s_tr)
        mean_bias_tr  = np.mean(fold_bias_tr)

        log("")
        log(f"Config {config_id} SUMMARY:")
        log(f"  [TRAIN AVG] MAE: {mean_mae_tr:.1f} | R2: {mean_r2_tr:.4f} | Bias: {mean_bias_tr:.1f}")
        log(f"  [VAL AVG]   MAE: {mean_mae_val:.1f} | R2: {mean_r2_val:.4f} | Bias: {mean_bias_val:.1f} | RMSE: {mean_rmse_val:.1f}")

        search_results.append({
            "config_id": config_id,
            **params,

            "val_rmse": mean_rmse_val,
            "val_mae": mean_mae_val,
            "val_r2": mean_r2_val,
            "val_bias": mean_bias_val,
            
            "train_mae": mean_mae_tr,
            "train_r2": mean_r2_tr,
            "train_bias": mean_bias_tr,

            "val_med_ae": np.mean(fold_med_ae)
        })

        if mean_rmse_val < best_rmse:
            best_rmse = mean_rmse_val
            best_config = {**params}
            log(f"[NEW BEST RMSE] Config {config_id}")

    log("# END OF SEARCH")

# Results
results_df = pd.DataFrame(search_results)
results_df_sorted = results_df.sort_values(by="val_rmse", ascending=True)

print("\nTop 5 Configurations by RMSE:")

cols = [
    "config_id",
    "val_rmse", "val_mae", "val_r2", "val_bias",
    "train_mae", "train_r2", "train_bias",
    "val_med_ae",
    "n_estimators", "max_samples", "max_features",
    "tree_max_depth", "tree_min_samples_leaf", "tree_min_samples_split"
]

display(results_df_sorted[cols].head(5))

print("\nBest Config found:")
print(best_config)

# =============================
# START OF BG+DT SEARCH (LOG TARGET + AGE FEATURE)
# METRICS ON ORIGINAL SCALE: R2, RMSE, MAE, BIAS
# LOG FILE SAVED TO: baging_noowners_age_logprice_log2.txt
# =============================

######## CONFIG 1/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 10, 'tree_max_depth': 20, 'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.9}

[C1|F1] Processing fold...
  > Features Used (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9438 | RMSE: 2320 | MAE: 1228 | Bias: 196.9
  > [VAL]   R2: 0.9400 | RMSE: 2338 | MAE: 1403 | Bias: 179.0

[C1|F2] Processing fold...
  > [TRAIN] R2: 0.9430 | RMSE: 2326 | MAE: 1229 | Bias: 198.7
  > [VAL]   R2: 0.9265 | RMSE: 2636 | MAE: 1409 | Bias: 240.4

[C1|F3] Processing fold...
  > [TRAIN] R2: 0.9460 | RMSE: 2243 | MAE: 1223 | Bias: 195.7
  > [VAL]   R2: 0.9078 | RMSE: 3050 | MAE: 1435 | Bias: 252.9

[C1|F4] Processing fold...
  > [TRAIN] R2: 0.9440 | RMSE: 2297 | MAE: 1228 | Bias: 197.0
  > [VAL]   R2: 0.9284 | RMSE: 2634 | MAE: 1398 | Bias: 241.6

[C1|F5] Processing fold...
  > [TRAIN] R2: 0.9438 | RMSE: 2320 | MAE: 1233 | Bias: 198.7
  > [VAL]   R2: 0.9373 | RMSE: 2382 | MAE: 1368 | Bias: 184.4

Config 1 SUMMARY:
  [TRAIN AVG] MAE: 1228.4 | R2: 0.9441 | Bias: 197.4
  [VAL AVG]   MAE: 1402.6 | R2: 0.9280 | Bias: 219.6 | RMSE: 2608.1
[NEW BEST RMSE] Config 1

######## CONFIG 2/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 1, 'tree_max_depth': 25, 'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.8}

[C2|F1] Processing fold...
  > Features Used (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9534 | RMSE: 2112 | MAE: 1158 | Bias: 209.3
  > [VAL]   R2: 0.9453 | RMSE: 2233 | MAE: 1355 | Bias: 198.8

[C2|F2] Processing fold...
  > [TRAIN] R2: 0.9529 | RMSE: 2114 | MAE: 1157 | Bias: 210.6
  > [VAL]   R2: 0.9356 | RMSE: 2469 | MAE: 1363 | Bias: 263.7

[C2|F3] Processing fold...
  > [TRAIN] R2: 0.9559 | RMSE: 2028 | MAE: 1152 | Bias: 207.4
  > [VAL]   R2: 0.9159 | RMSE: 2914 | MAE: 1388 | Bias: 272.6

[C2|F4] Processing fold...
  > [TRAIN] R2: 0.9542 | RMSE: 2079 | MAE: 1158 | Bias: 208.4
  > [VAL]   R2: 0.9356 | RMSE: 2498 | MAE: 1353 | Bias: 256.6

[C2|F5] Processing fold...
  > [TRAIN] R2: 0.9532 | RMSE: 2119 | MAE: 1161 | Bias: 210.3
  > [VAL]   R2: 0.9428 | RMSE: 2275 | MAE: 1331 | Bias: 204.6

Config 2 SUMMARY:
  [TRAIN AVG] MAE: 1157.1 | R2: 0.9539 | Bias: 209.2
  [VAL AVG]   MAE: 1358.0 | R2: 0.9350 | Bias: 239.2 | RMSE: 2477.7
[NEW BEST RMSE] Config 2

######## CONFIG 3/15 ########
Parameters: {'tree_min_samples_split': 50, 'tree_min_samples_leaf': 10, 'tree_max_depth': 25, 'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.9}

[C3|F1] Processing fold...
  > Features Used (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9344 | RMSE: 2505 | MAE: 1339 | Bias: 221.8
  > [VAL]   R2: 0.9356 | RMSE: 2422 | MAE: 1453 | Bias: 199.1

[C3|F2] Processing fold...
  > [TRAIN] R2: 0.9329 | RMSE: 2524 | MAE: 1341 | Bias: 223.7
  > [VAL]   R2: 0.9201 | RMSE: 2750 | MAE: 1462 | Bias: 260.6

[C3|F3] Processing fold...
  > [TRAIN] R2: 0.9367 | RMSE: 2429 | MAE: 1333 | Bias: 219.5
  > [VAL]   R2: 0.9022 | RMSE: 3142 | MAE: 1488 | Bias: 276.3

[C3|F4] Processing fold...
  > [TRAIN] R2: 0.9345 | RMSE: 2485 | MAE: 1339 | Bias: 221.8
  > [VAL]   R2: 0.9217 | RMSE: 2755 | MAE: 1455 | Bias: 260.8

[C3|F5] Processing fold...
  > [TRAIN] R2: 0.9346 | RMSE: 2503 | MAE: 1343 | Bias: 223.1
  > [VAL]   R2: 0.9311 | RMSE: 2496 | MAE: 1423 | Bias: 202.8

Config 3 SUMMARY:
  [TRAIN AVG] MAE: 1339.0 | R2: 0.9346 | Bias: 222.0
  [VAL AVG]   MAE: 1456.3 | R2: 0.9221 | Bias: 239.9 | RMSE: 2713.1

######## CONFIG 4/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 10, 'tree_max_depth': 20, 'n_estimators': 1000, 'max_samples': 1.0, 'max_features': 0.9}

[C4|F1] Processing fold...
  > Features Used (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9406 | RMSE: 2385 | MAE: 1265 | Bias: 208.1
  > [VAL]   R2: 0.9390 | RMSE: 2357 | MAE: 1412 | Bias: 186.8

[C4|F2] Processing fold...
  > [TRAIN] R2: 0.9397 | RMSE: 2392 | MAE: 1266 | Bias: 208.9
  > [VAL]   R2: 0.9245 | RMSE: 2673 | MAE: 1421 | Bias: 249.3

[C4|F3] Processing fold...
  > [TRAIN] R2: 0.9428 | RMSE: 2310 | MAE: 1260 | Bias: 205.7
  > [VAL]   R2: 0.9060 | RMSE: 3080 | MAE: 1446 | Bias: 262.7

[C4|F4] Processing fold...
  > [TRAIN] R2: 0.9408 | RMSE: 2362 | MAE: 1265 | Bias: 208.4
  > [VAL]   R2: 0.9266 | RMSE: 2668 | MAE: 1410 | Bias: 249.3

[C4|F5] Processing fold...
  > [TRAIN] R2: 0.9405 | RMSE: 2389 | MAE: 1270 | Bias: 209.6
  > [VAL]   R2: 0.9354 | RMSE: 2418 | MAE: 1382 | Bias: 193.8

Config 4 SUMMARY:
  [TRAIN AVG] MAE: 1265.3 | R2: 0.9409 | Bias: 208.1
  [VAL AVG]   MAE: 1414.3 | R2: 0.9263 | Bias: 228.4 | RMSE: 2639.1

######## CONFIG 5/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 5, 'tree_max_depth': 20, 'n_estimators': 1000, 'max_samples': 0.5, 'max_features': 0.9}

[C5|F1] Processing fold...
  > Features Used (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9368 | RMSE: 2460 | MAE: 1319 | Bias: 225.6
  > [VAL]   R2: 0.9375 | RMSE: 2385 | MAE: 1434 | Bias: 200.8

[C5|F2] Processing fold...
  > [TRAIN] R2: 0.9356 | RMSE: 2472 | MAE: 1320 | Bias: 226.5
  > [VAL]   R2: 0.9231 | RMSE: 2698 | MAE: 1445 | Bias: 264.2

[C5|F3] Processing fold...
  > [TRAIN] R2: 0.9390 | RMSE: 2386 | MAE: 1313 | Bias: 223.1
  > [VAL]   R2: 0.9046 | RMSE: 3103 | MAE: 1471 | Bias: 281.4

[C5|F4] Processing fold...
  > [TRAIN] R2: 0.9375 | RMSE: 2428 | MAE: 1319 | Bias: 224.6
  > [VAL]   R2: 0.9239 | RMSE: 2715 | MAE: 1435 | Bias: 262.1

[C5|F5] Processing fold...
  > [TRAIN] R2: 0.9368 | RMSE: 2461 | MAE: 1324 | Bias: 226.4
  > [VAL]   R2: 0.9333 | RMSE: 2457 | MAE: 1407 | Bias: 207.1

Config 5 SUMMARY:
  [TRAIN AVG] MAE: 1318.9 | R2: 0.9371 | Bias: 225.2
  [VAL AVG]   MAE: 1438.3 | R2: 0.9245 | Bias: 243.1 | RMSE: 2671.5

######## CONFIG 6/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 10, 'tree_max_depth': 15, 'n_estimators': 1200, 'max_samples': 1.0, 'max_features': 0.9}

[C6|F1] Processing fold...
  > Features Used (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9420 | RMSE: 2356 | MAE: 1264 | Bias: 205.4
  > [VAL]   R2: 0.9395 | RMSE: 2348 | MAE: 1414 | Bias: 185.9

[C6|F2] Processing fold...
  > [TRAIN] R2: 0.9413 | RMSE: 2359 | MAE: 1263 | Bias: 206.1
  > [VAL]   R2: 0.9258 | RMSE: 2650 | MAE: 1423 | Bias: 246.9

[C6|F3] Processing fold...
  > [TRAIN] R2: 0.9444 | RMSE: 2278 | MAE: 1257 | Bias: 203.3
  > [VAL]   R2: 0.9072 | RMSE: 3060 | MAE: 1445 | Bias: 260.6

[C6|F4] Processing fold...
  > [TRAIN] R2: 0.9422 | RMSE: 2334 | MAE: 1262 | Bias: 205.8
  > [VAL]   R2: 0.9276 | RMSE: 2648 | MAE: 1408 | Bias: 248.0

[C6|F5] Processing fold...
  > [TRAIN] R2: 0.9420 | RMSE: 2357 | MAE: 1268 | Bias: 207.1
  > [VAL]   R2: 0.9365 | RMSE: 2397 | MAE: 1380 | Bias: 191.7

Config 6 SUMMARY:
  [TRAIN AVG] MAE: 1262.8 | R2: 0.9424 | Bias: 205.5
  [VAL AVG]   MAE: 1413.8 | R2: 0.9273 | Bias: 226.6 | RMSE: 2620.7

######## CONFIG 7/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 5, 'tree_max_depth': 15, 'n_estimators': 1000, 'max_samples': 0.5, 'max_features': 0.8}

[C7|F1] Processing fold...
  > Features Used (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9339 | RMSE: 2515 | MAE: 1354 | Bias: 263.4
  > [VAL]   R2: 0.9360 | RMSE: 2415 | MAE: 1451 | Bias: 239.2

[C7|F2] Processing fold...
  > [TRAIN] R2: 0.9328 | RMSE: 2525 | MAE: 1353 | Bias: 264.4
  > [VAL]   R2: 0.9213 | RMSE: 2728 | MAE: 1465 | Bias: 302.9

[C7|F3] Processing fold...
  > [TRAIN] R2: 0.9361 | RMSE: 2441 | MAE: 1345 | Bias: 261.1
  > [VAL]   R2: 0.9023 | RMSE: 3140 | MAE: 1487 | Bias: 319.8

[C7|F4] Processing fold...
  > [TRAIN] R2: 0.9347 | RMSE: 2481 | MAE: 1352 | Bias: 261.7
  > [VAL]   R2: 0.9212 | RMSE: 2763 | MAE: 1452 | Bias: 301.1

[C7|F5] Processing fold...
  > [TRAIN] R2: 0.9340 | RMSE: 2516 | MAE: 1357 | Bias: 264.0
  > [VAL]   R2: 0.9314 | RMSE: 2491 | MAE: 1428 | Bias: 244.6

Config 7 SUMMARY:
  [TRAIN AVG] MAE: 1352.2 | R2: 0.9343 | Bias: 263.0
  [VAL AVG]   MAE: 1456.7 | R2: 0.9225 | Bias: 281.5 | RMSE: 2707.4

######## CONFIG 8/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 1, 'tree_max_depth': 20, 'n_estimators': 1200, 'max_samples': 0.5, 'max_features': 0.8}

[C8|F1] Processing fold...
  > Features Used (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9584 | RMSE: 1995 | MAE: 1083 | Bias: 201.1
  > [VAL]   R2: 0.9478 | RMSE: 2181 | MAE: 1324 | Bias: 194.8

[C8|F2] Processing fold...
  > [TRAIN] R2: 0.9585 | RMSE: 1985 | MAE: 1081 | Bias: 200.9
  > [VAL]   R2: 0.9380 | RMSE: 2422 | MAE: 1338 | Bias: 259.2

[C8|F3] Processing fold...
  > [TRAIN] R2: 0.9611 | RMSE: 1906 | MAE: 1075 | Bias: 197.8
  > [VAL]   R2: 0.9195 | RMSE: 2850 | MAE: 1359 | Bias: 266.2

[C8|F4] Processing fold...
  > [TRAIN] R2: 0.9589 | RMSE: 1969 | MAE: 1082 | Bias: 200.3
  > [VAL]   R2: 0.9385 | RMSE: 2441 | MAE: 1323 | Bias: 253.2

[C8|F5] Processing fold...
  > [TRAIN] R2: 0.9582 | RMSE: 2001 | MAE: 1085 | Bias: 201.6
  > [VAL]   R2: 0.9460 | RMSE: 2210 | MAE: 1301 | Bias: 203.2

Config 8 SUMMARY:
  [TRAIN AVG] MAE: 1081.4 | R2: 0.9590 | Bias: 200.3
  [VAL AVG]   MAE: 1329.1 | R2: 0.9380 | Bias: 235.3 | RMSE: 2420.9
[NEW BEST RMSE] Config 8

######## CONFIG 9/15 ########
Parameters: {'tree_min_samples_split': 50, 'tree_min_samples_leaf': 5, 'tree_max_depth': 25, 'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.6}

[C9|F1] Processing fold...
  > Features Used (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9250 | RMSE: 2680 | MAE: 1435 | Bias: 399.2
  > [VAL]   R2: 0.9269 | RMSE: 2580 | MAE: 1533 | Bias: 382.7

[C9|F2] Processing fold...
  > [TRAIN] R2: 0.9239 | RMSE: 2687 | MAE: 1434 | Bias: 399.1
  > [VAL]   R2: 0.9126 | RMSE: 2876 | MAE: 1555 | Bias: 445.6

[C9|F3] Processing fold...
  > [TRAIN] R2: 0.9280 | RMSE: 2591 | MAE: 1427 | Bias: 395.9
  > [VAL]   R2: 0.8923 | RMSE: 3297 | MAE: 1574 | Bias: 463.3

[C9|F4] Processing fold...
  > [TRAIN] R2: 0.9267 | RMSE: 2629 | MAE: 1435 | Bias: 395.9
  > [VAL]   R2: 0.9095 | RMSE: 2962 | MAE: 1541 | Bias: 446.5

[C9|F5] Processing fold...
  > [TRAIN] R2: 0.9250 | RMSE: 2682 | MAE: 1437 | Bias: 400.5
  > [VAL]   R2: 0.9224 | RMSE: 2649 | MAE: 1512 | Bias: 384.7

Config 9 SUMMARY:
  [TRAIN AVG] MAE: 1433.6 | R2: 0.9257 | Bias: 398.1
  [VAL AVG]   MAE: 1543.0 | R2: 0.9127 | Bias: 424.6 | RMSE: 2872.8

######## CONFIG 10/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 5, 'tree_max_depth': 20, 'n_estimators': 1200, 'max_samples': 0.5, 'max_features': 0.8}

[C10|F1] Processing fold...
  > Features Used (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9350 | RMSE: 2494 | MAE: 1332 | Bias: 259.1
  > [VAL]   R2: 0.9367 | RMSE: 2402 | MAE: 1439 | Bias: 234.8

[C10|F2] Processing fold...
  > [TRAIN] R2: 0.9339 | RMSE: 2504 | MAE: 1333 | Bias: 259.7
  > [VAL]   R2: 0.9221 | RMSE: 2714 | MAE: 1452 | Bias: 299.5

[C10|F3] Processing fold...
  > [TRAIN] R2: 0.9373 | RMSE: 2419 | MAE: 1325 | Bias: 256.4
  > [VAL]   R2: 0.9031 | RMSE: 3128 | MAE: 1475 | Bias: 315.4

[C10|F4] Processing fold...
  > [TRAIN] R2: 0.9357 | RMSE: 2462 | MAE: 1332 | Bias: 257.7
  > [VAL]   R2: 0.9218 | RMSE: 2754 | MAE: 1441 | Bias: 297.6

[C10|F5] Processing fold...
  > [TRAIN] R2: 0.9350 | RMSE: 2496 | MAE: 1336 | Bias: 260.0
  > [VAL]   R2: 0.9319 | RMSE: 2482 | MAE: 1416 | Bias: 242.4

Config 10 SUMMARY:
  [TRAIN AVG] MAE: 1331.5 | R2: 0.9354 | Bias: 258.6
  [VAL AVG]   MAE: 1444.8 | R2: 0.9231 | Bias: 277.9 | RMSE: 2695.9

######## CONFIG 11/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 1, 'tree_max_depth': 20, 'n_estimators': 400, 'max_samples': 0.5, 'max_features': 0.6}

[C11|F1] Processing fold...
  > Features Used (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9456 | RMSE: 2282 | MAE: 1237 | Bias: 340.0
  > [VAL]   R2: 0.9363 | RMSE: 2409 | MAE: 1444 | Bias: 350.6

[C11|F2] Processing fold...
  > [TRAIN] R2: 0.9457 | RMSE: 2269 | MAE: 1233 | Bias: 338.7
  > [VAL]   R2: 0.9252 | RMSE: 2661 | MAE: 1466 | Bias: 408.3

[C11|F3] Processing fold...
  > [TRAIN] R2: 0.9482 | RMSE: 2198 | MAE: 1230 | Bias: 335.6
  > [VAL]   R2: 0.9054 | RMSE: 3090 | MAE: 1483 | Bias: 416.9

[C11|F4] Processing fold...
  > [TRAIN] R2: 0.9464 | RMSE: 2249 | MAE: 1237 | Bias: 336.7
  > [VAL]   R2: 0.9234 | RMSE: 2725 | MAE: 1450 | Bias: 405.7

[C11|F5] Processing fold...
  > [TRAIN] R2: 0.9454 | RMSE: 2287 | MAE: 1239 | Bias: 340.3
  > [VAL]   R2: 0.9340 | RMSE: 2443 | MAE: 1423 | Bias: 349.9

Config 11 SUMMARY:
  [TRAIN AVG] MAE: 1235.4 | R2: 0.9463 | Bias: 338.3
  [VAL AVG]   MAE: 1453.1 | R2: 0.9248 | Bias: 386.3 | RMSE: 2665.6

######## CONFIG 12/15 ########
Parameters: {'tree_min_samples_split': 50, 'tree_min_samples_leaf': 5, 'tree_max_depth': 20, 'n_estimators': 400, 'max_samples': 0.5, 'max_features': 0.8}

[C12|F1] Processing fold...
  > Features Used (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9263 | RMSE: 2656 | MAE: 1418 | Bias: 279.3
  > [VAL]   R2: 0.9318 | RMSE: 2493 | MAE: 1495 | Bias: 247.4

[C12|F2] Processing fold...
  > [TRAIN] R2: 0.9251 | RMSE: 2666 | MAE: 1419 | Bias: 280.5
  > [VAL]   R2: 0.9146 | RMSE: 2842 | MAE: 1511 | Bias: 318.4

[C12|F3] Processing fold...
  > [TRAIN] R2: 0.9286 | RMSE: 2581 | MAE: 1410 | Bias: 277.2
  > [VAL]   R2: 0.8967 | RMSE: 3229 | MAE: 1535 | Bias: 335.7

[C12|F4] Processing fold...
  > [TRAIN] R2: 0.9267 | RMSE: 2629 | MAE: 1420 | Bias: 278.3
  > [VAL]   R2: 0.9139 | RMSE: 2889 | MAE: 1504 | Bias: 318.9

[C12|F5] Processing fold...
  > [TRAIN] R2: 0.9262 | RMSE: 2661 | MAE: 1423 | Bias: 280.6
  > [VAL]   R2: 0.9254 | RMSE: 2597 | MAE: 1475 | Bias: 255.3

Config 12 SUMMARY:
  [TRAIN AVG] MAE: 1417.8 | R2: 0.9266 | Bias: 279.2
  [VAL AVG]   MAE: 1503.9 | R2: 0.9165 | Bias: 295.2 | RMSE: 2810.0

######## CONFIG 13/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 5, 'tree_max_depth': 25, 'n_estimators': 1200, 'max_samples': 1.0, 'max_features': 0.9}

[C13|F1] Processing fold...
  > Features Used (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9597 | RMSE: 1964 | MAE: 1041 | Bias: 164.5
  > [VAL]   R2: 0.9475 | RMSE: 2186 | MAE: 1325 | Bias: 155.3

[C13|F2] Processing fold...
  > [TRAIN] R2: 0.9591 | RMSE: 1968 | MAE: 1041 | Bias: 164.8
  > [VAL]   R2: 0.9368 | RMSE: 2445 | MAE: 1335 | Bias: 220.3

[C13|F3] Processing fold...
  > [TRAIN] R2: 0.9623 | RMSE: 1875 | MAE: 1036 | Bias: 163.0
  > [VAL]   R2: 0.9184 | RMSE: 2870 | MAE: 1357 | Bias: 227.8

[C13|F4] Processing fold...
  > [TRAIN] R2: 0.9599 | RMSE: 1943 | MAE: 1042 | Bias: 164.6
  > [VAL]   R2: 0.9387 | RMSE: 2438 | MAE: 1321 | Bias: 211.0

[C13|F5] Processing fold...
  > [TRAIN] R2: 0.9594 | RMSE: 1972 | MAE: 1046 | Bias: 165.5
  > [VAL]   R2: 0.9464 | RMSE: 2202 | MAE: 1293 | Bias: 168.3

Config 13 SUMMARY:
  [TRAIN AVG] MAE: 1041.4 | R2: 0.9601 | Bias: 164.5
  [VAL AVG]   MAE: 1326.2 | R2: 0.9376 | Bias: 196.5 | RMSE: 2428.4

######## CONFIG 14/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 1, 'tree_max_depth': 15, 'n_estimators': 400, 'max_samples': 0.5, 'max_features': 0.9}

[C14|F1] Processing fold...
  > Features Used (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9414 | RMSE: 2369 | MAE: 1311 | Bias: 219.2
  > [VAL]   R2: 0.9397 | RMSE: 2343 | MAE: 1430 | Bias: 196.2

[C14|F2] Processing fold...
  > [TRAIN] R2: 0.9409 | RMSE: 2368 | MAE: 1310 | Bias: 219.1
  > [VAL]   R2: 0.9285 | RMSE: 2600 | MAE: 1439 | Bias: 257.6

[C14|F3] Processing fold...
  > [TRAIN] R2: 0.9444 | RMSE: 2278 | MAE: 1302 | Bias: 214.9
  > [VAL]   R2: 0.9092 | RMSE: 3028 | MAE: 1466 | Bias: 275.3

[C14|F4] Processing fold...
  > [TRAIN] R2: 0.9430 | RMSE: 2318 | MAE: 1308 | Bias: 216.5
  > [VAL]   R2: 0.9286 | RMSE: 2631 | MAE: 1427 | Bias: 254.6

[C14|F5] Processing fold...
  > [TRAIN] R2: 0.9420 | RMSE: 2358 | MAE: 1312 | Bias: 218.0
  > [VAL]   R2: 0.9366 | RMSE: 2396 | MAE: 1402 | Bias: 197.6

Config 14 SUMMARY:
  [TRAIN AVG] MAE: 1308.6 | R2: 0.9423 | Bias: 217.6
  [VAL AVG]   MAE: 1432.8 | R2: 0.9285 | Bias: 236.3 | RMSE: 2599.4

######## CONFIG 15/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 5, 'tree_max_depth': 20, 'n_estimators': 1200, 'max_samples': 0.5, 'max_features': 0.9}

[C15|F1] Processing fold...
  > Features Used (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > [TRAIN] R2: 0.9367 | RMSE: 2461 | MAE: 1318 | Bias: 225.4
  > [VAL]   R2: 0.9375 | RMSE: 2385 | MAE: 1433 | Bias: 200.7

[C15|F2] Processing fold...
  > [TRAIN] R2: 0.9356 | RMSE: 2471 | MAE: 1320 | Bias: 226.1
  > [VAL]   R2: 0.9232 | RMSE: 2696 | MAE: 1443 | Bias: 264.0

[C15|F3] Processing fold...

,config_id,val_rmse,val_mae,val_r2,val_bias,train_mae,train_r2,train_bias,val_med_ae,n_estimators,max_samples,max_features,tree_max_depth,tree_min_samples_leaf,tree_min_samples_split
7,8,2420.871603,1329.102444,0.937961,235.315931,1081.381567,0.959007,200.342110,822.415139,1200,0.5,0.8,20,1,10
12,13,2428.413123,1326.187633,0.937551,196.539462,1041.355547,0.960106,164.475307,813.025478,1200,1.0,0.9,25,5,10
1,2,2477.670885,1358.020994,0.935024,239.241912,1157.105199,0.953909,209.206639,838.635300,400,1.0,0.8,25,1,30
13,14,2599.390030,1432.781394,0.928521,236.280989,1308.576105,0.942327,217.550331,883.235440,400,0.5,0.9,15,1,30
0,1,2608.091154,1402.550338,0.928008,219.636422,1228.363490,0.944137,197.387656,852.828571,400,1.0,0.9,20,10,10

Best Config found:
{'tree_min_samples_split': 10, 'tree_min_samples_leaf': 1, 'tree_max_depth': 20, 'n_estimators': 1200, 'max_samples': 0.5, 'max_features': 0.8}

o mesmo mas com feature selection 80%

In [19]:
# numeric features used by the model (year is replaced by age; previousOwners is excluded)
numeric_features = ["mileage", "engineSize", "tax", "mpg", "age"]



# shuffles the data, in order to (at least theoretically) have more balanced folds
# we will use an 8-fold cross-validation strategy
kf = KFold(n_splits=N_SPLITS, shuffle=True, random_state=RANDOM_STATE)

# we explicitly exclude this feature from the model input
DROP_FROM_MODEL = ["previousOwners"]

# feature selection: keep 90% of the final encoded feature space
FS_KEEP_RATIO = 0.80

# RandomForest used only to rank feature importances for SelectFromModel
RF_FS_PARAMS = {
    "n_estimators": 500,
    "random_state": RANDOM_STATE,
    "n_jobs": -1,
    "max_depth": None,
    "min_samples_split": 2,
    "min_samples_leaf": 2,
    "max_features": "sqrt",
    "bootstrap": True,
}

# hyperparameter space that we are going to use for random search
# each configuration will get 1 value from each of these lists
param_distributions = {

    # Bagging (ensemble-level)
    
    # Number of trees in the ensemble.
    # Higher values usually improve stability but increase training time.
    "n_estimators": [400,1000,1200],

    # Fraction of samples used to train each tree.
    # Values < 1.0 increase diversity between estimators.
    "max_samples": [0.5, 1.0],

    # Fraction of features used by each estimator.
    # This helps reduce correlation between trees.
    "max_features": [0.6, 0.8, 0.9],

    
    # Decision Tree (base model)
    
    # Maximum depth of each decision tree.
    "tree_max_depth": [15, 20, 25],

    # Minimum number of samples required at a leaf node.
    # Larger values increase regularization.
    "tree_min_samples_leaf": [1, 5, 10],

    # Minimum number of samples required to split an internal node.
    "tree_min_samples_split": [10, 30, 50]

}

N_RANDOM_CONFIGS = 15  # short random search, enough for baseline results

# we get N_RANDOM_CONFIGS random parameter combinations from param_distributions
sampler = ParameterSampler(param_distributions, n_iter=N_RANDOM_CONFIGS, random_state=RANDOM_STATE)

search_results = []  # stores results for ranking
best_rmse = np.inf
best_config = None

# log setup (mainly for development and traceability)
log_path = "bag_noowners_age_logprice_fs80m_log15it.txt"

# Note: this section is included mainly for organizational purposes
with open(log_path, "w", encoding="utf-8") as log_file:

    def log(msg: str):
        print(msg)
        log_file.write(msg + "\n")
        log_file.flush()

    log("# =============================")
    log("# START OF BG+DT SEARCH (LOG TARGET + AGE FEATURE + FS 80%)")
    log("# METRICS ON ORIGINAL SCALE: R2, RMSE, MAE, BIAS")
    log(f"# LOG FILE SAVED TO: {log_path}")
    log("# =============================")

    for config_id, params in enumerate(sampler, start=1):
        log("")
        log(f"######## CONFIG {config_id}/{N_RANDOM_CONFIGS} ########")
        log(f"Parameters: {params}")

        fold_rmses_val, fold_maes_val, fold_r2s_val, fold_bias_val = [], [], [], []
        fold_rmses_tr,  fold_maes_tr,  fold_r2s_tr,  fold_bias_tr  = [], [], [], []
        fold_med_ae = []
        fold_nsel = []

        for fold, (train_idx, val_idx) in enumerate(kf.split(X), start=1):

            X_train, X_val = X.iloc[train_idx].copy(), X.iloc[val_idx].copy()
            y_train, y_val = y.iloc[train_idx].copy(), y.iloc[val_idx].copy()

            # log-transform target for training
            y_train_log = np.log1p(y_train)

            log(f"\n[C{config_id}|F{fold}] Processing fold...")

            # -> Preprocessing steps (fit only on training fold, apply to both)
            year_state = fit_year_median(X_train, year_col="year", model_col="model")
            X_train = transform_year_with_model_median(X_train, state=year_state)
            X_val   = transform_year_with_model_median(X_val,   state=year_state)

            mileage_state = fit_mileage_imputer(X_train, mileage_col="mileage", do_abs=True)
            X_train = transform_mileage_imputer(X_train, state=mileage_state)
            X_val   = transform_mileage_imputer(X_val,   state=mileage_state)

            engine_state = fit_engine_size_imputer(X_train, engine_col="engineSize")
            X_train = transform_engine_size_imputer(X_train, state=engine_state)
            X_val   = transform_engine_size_imputer(X_val,   state=engine_state)

            X_train = transform_tax_custom_rules(X_train, "tax", "year", "fuelType", "engineSize")
            X_val   = transform_tax_custom_rules(X_val,   "tax", "year", "fuelType", "engineSize")

            mpg_state = fit_mpg_imputer(X_train, mpg_col="mpg", do_abs=True)
            X_train = transform_mpg_imputer(X_train, state=mpg_state)
            X_val   = transform_mpg_imputer(X_val,   state=mpg_state)

            brand_state = fit_ambiguous_brand_resolver(X_train, valid_brands)
            X_train, _, _ = transform_ambiguous_brands(X_train, brand_state)
            X_val,   _, _ = transform_ambiguous_brands(X_val,   brand_state)

            model_state = fit_invalid_model_resolver(X_train, valid_models_by_brand)
            X_train, _, _ = transform_invalid_models(X_train, model_state)
            X_val,   _, _ = transform_invalid_models(X_val,   model_state)

            transm_state = fit_transmission_resolver(X_train, valid_transmissions)
            X_train, _, _ = transform_transmission_resolver(X_train, transm_state)
            X_val,   _, _ = transform_transmission_resolver(X_val,   transm_state)

            fuel_state = fit_fueltype_resolver(X_train, valid_fueltypes)
            X_train, _, _ = transform_fueltype_resolver(X_train, fuel_state)
            X_val,   _, _ = transform_fueltype_resolver(X_val,   fuel_state)

            # -> Feature engineering: create age and drop year (do this after all year-based steps)
            X_train = create_age_and_drop_year(X_train, year_col="year", base_year=2020)
            X_val   = create_age_and_drop_year(X_val,   year_col="year", base_year=2020)

            # hard guarantee: previousOwners is not used by the model
            X_train = X_train.drop(columns=DROP_FROM_MODEL, errors="ignore")
            X_val   = X_val.drop(columns=DROP_FROM_MODEL, errors="ignore")

            # -> Feature encoding (categorical only)
            high_card_features = ["Brand", "model"]
            low_card_features  = [c for c in categorical_features if c not in high_card_features]

            te = MyTargetEncoder(smoothing=5)
            te.fit(X_train[high_card_features], y_train_log)  # fit using log-target
            X_train_high = te.transform(X_train[high_card_features])
            X_val_high   = te.transform(X_val[high_card_features])

            ohe = MyOneHotEncoder()
            ohe.fit(X_train[low_card_features])
            X_train_low = ohe.transform(X_train[low_card_features])
            X_val_low   = ohe.transform(X_val[low_card_features])

            X_train_cat = pd.concat([X_train_high, X_train_low], axis=1)
            X_val_cat   = pd.concat([X_val_high,   X_val_low],   axis=1)

            # join numerical and categorical (encoded) features
            X_train_final = pd.concat([X_train[numeric_features], X_train_cat], axis=1)
            X_val_final   = pd.concat([X_val[numeric_features],   X_val_cat],   axis=1)

            if len(numeric_features) > 0:
                scaler = StandardScaler()
                X_train_final[numeric_features] = scaler.fit_transform(X_train_final[numeric_features])
                X_val_final[numeric_features]   = scaler.transform(X_val_final[numeric_features])

            # align columns to avoid mismatch due to encoding
            X_val_final = X_val_final.reindex(columns=X_train_final.columns, fill_value=0)

            if fold == 1:
                feature_names = list(X_train_final.columns)
                log(f"  > Features before FS ({len(feature_names)}): {feature_names}")

            # -> Feature selection (keep top 90% features by RF importance)
            n_feats = X_train_final.shape[1]
            k = int(np.ceil(FS_KEEP_RATIO * n_feats))
            k = max(1, min(k, n_feats))

            rf_fs = RandomForestRegressor(**RF_FS_PARAMS)
            rf_fs.fit(X_train_final, y_train_log)

            selector = SelectFromModel(
                estimator=rf_fs,
                threshold=-np.inf,  # keep the top max_features
                max_features=k,
                prefit=True
            )

            selected_cols = X_train_final.columns[selector.get_support()]
            fold_nsel.append(len(selected_cols))

            X_train_sel = X_train_final[selected_cols]
            X_val_sel   = X_val_final[selected_cols]

            if fold == 1:
                log(f"  > Selected features ({len(selected_cols)}/{n_feats}) with FS_KEEP_RATIO={FS_KEEP_RATIO:.2f}")

            # -> Model training (train on log-target)
            base_tree = DecisionTreeRegressor(
                max_depth=params["tree_max_depth"],
                min_samples_leaf=params["tree_min_samples_leaf"],
                min_samples_split=params["tree_min_samples_split"],
                random_state=RANDOM_STATE
            )

            model = BaggingRegressor(
                estimator=base_tree,
                n_estimators=params["n_estimators"],
                max_samples=params["max_samples"],
                max_features=params["max_features"],
                random_state=RANDOM_STATE,
                n_jobs=-1
            )

            model.fit(X_train_sel, y_train_log)

            # predictions (log scale), then invert to original scale
            y_pred_train_log = model.predict(X_train_sel)
            y_pred_val_log   = model.predict(X_val_sel)

            y_pred_train = np.expm1(y_pred_train_log)
            y_pred_val   = np.expm1(y_pred_val_log)

            # -> Metrics on original scale
            mae_tr  = mean_absolute_error(y_train, y_pred_train)
            rmse_tr = np.sqrt(mean_squared_error(y_train, y_pred_train))
            r2_tr   = r2_score(y_train, y_pred_train)
            bias_tr = np.mean(y_train - y_pred_train)

            mae_val  = mean_absolute_error(y_val, y_pred_val)
            rmse_val = np.sqrt(mean_squared_error(y_val, y_pred_val))
            r2_val   = r2_score(y_val, y_pred_val)
            bias_val = np.mean(y_val - y_pred_val)

            med_ae_val = median_absolute_error(y_val, y_pred_val)

            log(f"  > [TRAIN] R2: {r2_tr:.4f} | RMSE: {rmse_tr:.0f} | MAE: {mae_tr:.0f} | Bias: {bias_tr:.1f}")
            log(f"  > [VAL]   R2: {r2_val:.4f} | RMSE: {rmse_val:.0f} | MAE: {mae_val:.0f} | Bias: {bias_val:.1f}")

            fold_maes_tr.append(mae_tr);   fold_rmses_tr.append(rmse_tr);   fold_r2s_tr.append(r2_tr);   fold_bias_tr.append(bias_tr)
            fold_maes_val.append(mae_val); fold_rmses_val.append(rmse_val); fold_r2s_val.append(r2_val); fold_bias_val.append(bias_val)
            fold_med_ae.append(med_ae_val)

        mean_rmse_val = np.mean(fold_rmses_val)
        mean_mae_val  = np.mean(fold_maes_val)
        mean_r2_val   = np.mean(fold_r2s_val)
        mean_bias_val = np.mean(fold_bias_val)

        mean_mae_tr   = np.mean(fold_maes_tr)
        mean_r2_tr    = np.mean(fold_r2s_tr)
        mean_bias_tr  = np.mean(fold_bias_tr)

        mean_nsel = float(np.mean(fold_nsel))

        log("")
        log(f"Config {config_id} SUMMARY:")
        log(f"  Selected features (avg): {mean_nsel:.0f} / {n_feats} (after encoding)")
        log(f"  [TRAIN AVG] MAE: {mean_mae_tr:.1f} | R2: {mean_r2_tr:.4f} | Bias: {mean_bias_tr:.1f}")
        log(f"  [VAL AVG]   MAE: {mean_mae_val:.1f} | R2: {mean_r2_val:.4f} | Bias: {mean_bias_val:.1f} | RMSE: {mean_rmse_val:.1f}")

        search_results.append({
            "config_id": config_id,
            **params,

            "fs_keep_ratio": FS_KEEP_RATIO,
            "avg_selected_features": mean_nsel,

            "val_rmse": mean_rmse_val,
            "val_mae": mean_mae_val,
            "val_r2": mean_r2_val,
            "val_bias": mean_bias_val,

            "train_mae": mean_mae_tr,
            "train_r2": mean_r2_tr,
            "train_bias": mean_bias_tr,

            "val_med_ae": np.mean(fold_med_ae)
        })

        if mean_rmse_val < best_rmse:
            best_rmse = mean_rmse_val
            best_config = {**params}
            log(f"[NEW BEST RMSE] Config {config_id}")

    log("# END OF SEARCH")

# Results
results_df = pd.DataFrame(search_results)
results_df_sorted = results_df.sort_values(by="val_rmse", ascending=True)

print("\nTop 5 Configurations by RMSE:")
cols = [
    "config_id",
    "val_rmse", "val_mae", "val_r2", "val_bias",
    "train_mae", "train_r2", "train_bias",
    "avg_selected_features",
    "n_estimators", "max_samples", "max_features",
    "tree_max_depth", "tree_min_samples_leaf", "tree_min_samples_split"
]
display(results_df_sorted[cols].head(5))

print("\nBest Config found:")
print(best_config)

# =============================
# START OF BG+DT SEARCH (LOG TARGET + AGE FEATURE + FS 80%)
# METRICS ON ORIGINAL SCALE: R2, RMSE, MAE, BIAS
# LOG FILE SAVED TO: bag_noowners_age_logprice_fs80m_log15it.txt
# =============================

######## CONFIG 1/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 10, 'tree_max_depth': 20, 'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.9}

[C1|F1] Processing fold...
  > Features before FS (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > Selected features (12/15) with FS_KEEP_RATIO=0.80
  > [TRAIN] R2: 0.9433 | RMSE: 2330 | MAE: 1234 | Bias: 211.4
  > [VAL]   R2: 0.9398 | RMSE: 2342 | MAE: 1404 | Bias: 192.8

[C1|F2] Processing fold...
  > [TRAIN] R2: 0.9424 | RMSE: 2337 | MAE: 1235 | Bias: 212.8
  > [VAL]   R2: 0.9264 | RMSE: 2638 | MAE: 1411 | Bias: 255.8

[C1|F3] Processing fold...
  > [TRAIN] R2: 0.9456 | RMSE: 2253 | MAE: 1228 | Bias: 209.7
  > [VAL]   R2: 0.9077 | RMSE: 3053 | MAE: 1433 | Bias: 267.2

[C1|F4] Processing fold...
  > [TRAIN] R2: 0.9434 | RMSE: 2311 | MAE: 1234 | Bias: 211.0
  > [VAL]   R2: 0.9278 | RMSE: 2645 | MAE: 1400 | Bias: 257.2

[C1|F5] Processing fold...
  > [TRAIN] R2: 0.9431 | RMSE: 2335 | MAE: 1239 | Bias: 213.2
  > [VAL]   R2: 0.9366 | RMSE: 2395 | MAE: 1372 | Bias: 200.5

Config 1 SUMMARY:
  Selected features (avg): 12 / 15 (after encoding)
  [TRAIN AVG] MAE: 1234.0 | R2: 0.9436 | Bias: 211.6
  [VAL AVG]   MAE: 1404.1 | R2: 0.9277 | Bias: 234.7 | RMSE: 2614.4
[NEW BEST RMSE] Config 1

######## CONFIG 2/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 1, 'tree_max_depth': 25, 'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.8}

[C2|F1] Processing fold...
  > Features before FS (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > Selected features (12/15) with FS_KEEP_RATIO=0.80
  > [TRAIN] R2: 0.9515 | RMSE: 2155 | MAE: 1177 | Bias: 230.8
  > [VAL]   R2: 0.9439 | RMSE: 2261 | MAE: 1368 | Bias: 222.0

[C2|F2] Processing fold...
  > [TRAIN] R2: 0.9509 | RMSE: 2158 | MAE: 1176 | Bias: 232.2
  > [VAL]   R2: 0.9339 | RMSE: 2500 | MAE: 1377 | Bias: 287.2

[C2|F3] Processing fold...
  > [TRAIN] R2: 0.9538 | RMSE: 2077 | MAE: 1170 | Bias: 229.1
  > [VAL]   R2: 0.9141 | RMSE: 2945 | MAE: 1399 | Bias: 294.1

[C2|F4] Processing fold...
  > [TRAIN] R2: 0.9522 | RMSE: 2122 | MAE: 1177 | Bias: 229.3
  > [VAL]   R2: 0.9331 | RMSE: 2546 | MAE: 1366 | Bias: 281.0

[C2|F5] Processing fold...
  > [TRAIN] R2: 0.9511 | RMSE: 2165 | MAE: 1180 | Bias: 232.0
  > [VAL]   R2: 0.9414 | RMSE: 2302 | MAE: 1343 | Bias: 228.7

Config 2 SUMMARY:
  Selected features (avg): 12 / 15 (after encoding)
  [TRAIN AVG] MAE: 1176.0 | R2: 0.9519 | Bias: 230.7
  [VAL AVG]   MAE: 1370.7 | R2: 0.9333 | Bias: 262.6 | RMSE: 2510.8
[NEW BEST RMSE] Config 2

######## CONFIG 3/15 ########
Parameters: {'tree_min_samples_split': 50, 'tree_min_samples_leaf': 10, 'tree_max_depth': 25, 'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.9}

[C3|F1] Processing fold...
  > Features before FS (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > Selected features (12/15) with FS_KEEP_RATIO=0.80
  > [TRAIN] R2: 0.9340 | RMSE: 2513 | MAE: 1341 | Bias: 237.5
  > [VAL]   R2: 0.9355 | RMSE: 2425 | MAE: 1453 | Bias: 213.2

[C3|F2] Processing fold...
  > [TRAIN] R2: 0.9324 | RMSE: 2532 | MAE: 1344 | Bias: 238.7
  > [VAL]   R2: 0.9201 | RMSE: 2750 | MAE: 1463 | Bias: 276.3

[C3|F3] Processing fold...
  > [TRAIN] R2: 0.9362 | RMSE: 2439 | MAE: 1335 | Bias: 234.9
  > [VAL]   R2: 0.9019 | RMSE: 3147 | MAE: 1486 | Bias: 291.6

[C3|F4] Processing fold...
  > [TRAIN] R2: 0.9340 | RMSE: 2495 | MAE: 1342 | Bias: 236.6
  > [VAL]   R2: 0.9211 | RMSE: 2765 | MAE: 1455 | Bias: 277.6

[C3|F5] Processing fold...
  > [TRAIN] R2: 0.9340 | RMSE: 2515 | MAE: 1346 | Bias: 238.5
  > [VAL]   R2: 0.9306 | RMSE: 2506 | MAE: 1426 | Bias: 219.2

Config 3 SUMMARY:
  Selected features (avg): 12 / 15 (after encoding)
  [TRAIN AVG] MAE: 1341.9 | R2: 0.9341 | Bias: 237.2
  [VAL AVG]   MAE: 1456.8 | R2: 0.9218 | Bias: 255.6 | RMSE: 2718.6

######## CONFIG 4/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 10, 'tree_max_depth': 20, 'n_estimators': 1000, 'max_samples': 1.0, 'max_features': 0.9}

[C4|F1] Processing fold...
  > Features before FS (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > Selected features (12/15) with FS_KEEP_RATIO=0.80
  > [TRAIN] R2: 0.9401 | RMSE: 2396 | MAE: 1270 | Bias: 221.7
  > [VAL]   R2: 0.9388 | RMSE: 2361 | MAE: 1413 | Bias: 199.6

[C4|F2] Processing fold...
  > [TRAIN] R2: 0.9391 | RMSE: 2403 | MAE: 1271 | Bias: 222.4
  > [VAL]   R2: 0.9244 | RMSE: 2675 | MAE: 1423 | Bias: 263.4

[C4|F3] Processing fold...
  > [TRAIN] R2: 0.9422 | RMSE: 2322 | MAE: 1265 | Bias: 219.1
  > [VAL]   R2: 0.9058 | RMSE: 3083 | MAE: 1446 | Bias: 276.1

[C4|F4] Processing fold...
  > [TRAIN] R2: 0.9402 | RMSE: 2374 | MAE: 1270 | Bias: 221.5
  > [VAL]   R2: 0.9259 | RMSE: 2679 | MAE: 1412 | Bias: 264.4

[C4|F5] Processing fold...
  > [TRAIN] R2: 0.9398 | RMSE: 2402 | MAE: 1276 | Bias: 223.2
  > [VAL]   R2: 0.9349 | RMSE: 2426 | MAE: 1385 | Bias: 208.6

Config 4 SUMMARY:
  Selected features (avg): 12 / 15 (after encoding)
  [TRAIN AVG] MAE: 1270.6 | R2: 0.9403 | Bias: 221.6
  [VAL AVG]   MAE: 1415.9 | R2: 0.9260 | Bias: 242.4 | RMSE: 2645.0

######## CONFIG 5/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 5, 'tree_max_depth': 20, 'n_estimators': 1000, 'max_samples': 0.5, 'max_features': 0.9}

[C5|F1] Processing fold...
  > Features before FS (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > Selected features (12/15) with FS_KEEP_RATIO=0.80
  > [TRAIN] R2: 0.9361 | RMSE: 2473 | MAE: 1324 | Bias: 239.0
  > [VAL]   R2: 0.9372 | RMSE: 2391 | MAE: 1436 | Bias: 214.3

[C5|F2] Processing fold...
  > [TRAIN] R2: 0.9350 | RMSE: 2484 | MAE: 1325 | Bias: 239.6
  > [VAL]   R2: 0.9228 | RMSE: 2703 | MAE: 1447 | Bias: 277.9

[C5|F3] Processing fold...
  > [TRAIN] R2: 0.9383 | RMSE: 2399 | MAE: 1318 | Bias: 236.5
  > [VAL]   R2: 0.9040 | RMSE: 3113 | MAE: 1472 | Bias: 294.6

[C5|F4] Processing fold...
  > [TRAIN] R2: 0.9367 | RMSE: 2442 | MAE: 1324 | Bias: 237.6
  > [VAL]   R2: 0.9229 | RMSE: 2733 | MAE: 1439 | Bias: 277.2

[C5|F5] Processing fold...
  > [TRAIN] R2: 0.9362 | RMSE: 2474 | MAE: 1329 | Bias: 239.6
  > [VAL]   R2: 0.9328 | RMSE: 2465 | MAE: 1411 | Bias: 221.3

Config 5 SUMMARY:
  Selected features (avg): 12 / 15 (after encoding)
  [TRAIN AVG] MAE: 1324.0 | R2: 0.9365 | Bias: 238.5
  [VAL AVG]   MAE: 1441.0 | R2: 0.9239 | Bias: 257.1 | RMSE: 2681.0

######## CONFIG 6/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 10, 'tree_max_depth': 15, 'n_estimators': 1200, 'max_samples': 1.0, 'max_features': 0.9}

[C6|F1] Processing fold...
  > Features before FS (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > Selected features (12/15) with FS_KEEP_RATIO=0.80
  > [TRAIN] R2: 0.9416 | RMSE: 2366 | MAE: 1270 | Bias: 219.4
  > [VAL]   R2: 0.9393 | RMSE: 2352 | MAE: 1415 | Bias: 199.2

[C6|F2] Processing fold...
  > [TRAIN] R2: 0.9408 | RMSE: 2369 | MAE: 1268 | Bias: 219.9
  > [VAL]   R2: 0.9256 | RMSE: 2653 | MAE: 1424 | Bias: 261.7

[C6|F3] Processing fold...
  > [TRAIN] R2: 0.9438 | RMSE: 2289 | MAE: 1262 | Bias: 216.9
  > [VAL]   R2: 0.9070 | RMSE: 3064 | MAE: 1445 | Bias: 273.9

[C6|F4] Processing fold...
  > [TRAIN] R2: 0.9416 | RMSE: 2346 | MAE: 1268 | Bias: 219.4
  > [VAL]   R2: 0.9270 | RMSE: 2659 | MAE: 1410 | Bias: 263.1

[C6|F5] Processing fold...
  > [TRAIN] R2: 0.9415 | RMSE: 2369 | MAE: 1273 | Bias: 221.0
  > [VAL]   R2: 0.9360 | RMSE: 2406 | MAE: 1384 | Bias: 207.3

Config 6 SUMMARY:
  Selected features (avg): 12 / 15 (after encoding)
  [TRAIN AVG] MAE: 1268.1 | R2: 0.9419 | Bias: 219.3
  [VAL AVG]   MAE: 1415.5 | R2: 0.9270 | Bias: 241.0 | RMSE: 2626.8

######## CONFIG 7/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 5, 'tree_max_depth': 15, 'n_estimators': 1000, 'max_samples': 0.5, 'max_features': 0.8}

[C7|F1] Processing fold...
  > Features before FS (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > Selected features (12/15) with FS_KEEP_RATIO=0.80
  > [TRAIN] R2: 0.9322 | RMSE: 2547 | MAE: 1369 | Bias: 286.9
  > [VAL]   R2: 0.9345 | RMSE: 2442 | MAE: 1463 | Bias: 262.9

[C7|F2] Processing fold...
  > [TRAIN] R2: 0.9309 | RMSE: 2560 | MAE: 1369 | Bias: 287.7
  > [VAL]   R2: 0.9197 | RMSE: 2756 | MAE: 1479 | Bias: 326.8

[C7|F3] Processing fold...
  > [TRAIN] R2: 0.9343 | RMSE: 2475 | MAE: 1361 | Bias: 285.1
  > [VAL]   R2: 0.9006 | RMSE: 3167 | MAE: 1498 | Bias: 343.3

[C7|F4] Processing fold...
  > [TRAIN] R2: 0.9329 | RMSE: 2515 | MAE: 1368 | Bias: 285.6
  > [VAL]   R2: 0.9189 | RMSE: 2803 | MAE: 1466 | Bias: 328.3

[C7|F5] Processing fold...
  > [TRAIN] R2: 0.9322 | RMSE: 2550 | MAE: 1372 | Bias: 287.8
  > [VAL]   R2: 0.9300 | RMSE: 2516 | MAE: 1441 | Bias: 269.2

Config 7 SUMMARY:
  Selected features (avg): 12 / 15 (after encoding)
  [TRAIN AVG] MAE: 1367.5 | R2: 0.9325 | Bias: 286.6
  [VAL AVG]   MAE: 1469.1 | R2: 0.9208 | Bias: 306.1 | RMSE: 2736.7

######## CONFIG 8/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 1, 'tree_max_depth': 20, 'n_estimators': 1200, 'max_samples': 0.5, 'max_features': 0.8}

[C8|F1] Processing fold...
  > Features before FS (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > Selected features (12/15) with FS_KEEP_RATIO=0.80
  > [TRAIN] R2: 0.9568 | RMSE: 2033 | MAE: 1104 | Bias: 221.6
  > [VAL]   R2: 0.9465 | RMSE: 2208 | MAE: 1338 | Bias: 218.4

[C8|F2] Processing fold...
  > [TRAIN] R2: 0.9568 | RMSE: 2024 | MAE: 1102 | Bias: 221.2
  > [VAL]   R2: 0.9365 | RMSE: 2452 | MAE: 1353 | Bias: 282.0

[C8|F3] Processing fold...
  > [TRAIN] R2: 0.9594 | RMSE: 1946 | MAE: 1097 | Bias: 218.8
  > [VAL]   R2: 0.9180 | RMSE: 2877 | MAE: 1372 | Bias: 287.7

[C8|F4] Processing fold...
  > [TRAIN] R2: 0.9572 | RMSE: 2008 | MAE: 1104 | Bias: 220.9
  > [VAL]   R2: 0.9364 | RMSE: 2482 | MAE: 1339 | Bias: 278.2

[C8|F5] Processing fold...
  > [TRAIN] R2: 0.9566 | RMSE: 2041 | MAE: 1107 | Bias: 222.3
  > [VAL]   R2: 0.9445 | RMSE: 2241 | MAE: 1316 | Bias: 226.5

Config 8 SUMMARY:
  Selected features (avg): 12 / 15 (after encoding)
  [TRAIN AVG] MAE: 1102.8 | R2: 0.9574 | Bias: 220.9
  [VAL AVG]   MAE: 1343.5 | R2: 0.9364 | Bias: 258.6 | RMSE: 2452.0
[NEW BEST RMSE] Config 8

######## CONFIG 9/15 ########
Parameters: {'tree_min_samples_split': 50, 'tree_min_samples_leaf': 5, 'tree_max_depth': 25, 'n_estimators': 400, 'max_samples': 1.0, 'max_features': 0.6}

[C9|F1] Processing fold...
  > Features before FS (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > Selected features (12/15) with FS_KEEP_RATIO=0.80
  > [TRAIN] R2: 0.9231 | RMSE: 2713 | MAE: 1455 | Bias: 409.6
  > [VAL]   R2: 0.9252 | RMSE: 2610 | MAE: 1549 | Bias: 392.2

[C9|F2] Processing fold...
  > [TRAIN] R2: 0.9221 | RMSE: 2718 | MAE: 1452 | Bias: 409.3
  > [VAL]   R2: 0.9111 | RMSE: 2900 | MAE: 1572 | Bias: 455.0

[C9|F3] Processing fold...
  > [TRAIN] R2: 0.9262 | RMSE: 2623 | MAE: 1447 | Bias: 406.1
  > [VAL]   R2: 0.8908 | RMSE: 3320 | MAE: 1591 | Bias: 471.1

[C9|F4] Processing fold...
  > [TRAIN] R2: 0.9250 | RMSE: 2659 | MAE: 1454 | Bias: 406.6
  > [VAL]   R2: 0.9075 | RMSE: 2994 | MAE: 1561 | Bias: 457.4

[C9|F5] Processing fold...
  > [TRAIN] R2: 0.9232 | RMSE: 2714 | MAE: 1457 | Bias: 411.9
  > [VAL]   R2: 0.9210 | RMSE: 2674 | MAE: 1528 | Bias: 396.6

Config 9 SUMMARY:
  Selected features (avg): 12 / 15 (after encoding)
  [TRAIN AVG] MAE: 1452.9 | R2: 0.9239 | Bias: 408.7
  [VAL AVG]   MAE: 1560.1 | R2: 0.9111 | Bias: 434.4 | RMSE: 2899.6

######## CONFIG 10/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 5, 'tree_max_depth': 20, 'n_estimators': 1200, 'max_samples': 0.5, 'max_features': 0.8}

[C10|F1] Processing fold...
  > Features before FS (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > Selected features (12/15) with FS_KEEP_RATIO=0.80
  > [TRAIN] R2: 0.9333 | RMSE: 2526 | MAE: 1348 | Bias: 283.4
  > [VAL]   R2: 0.9352 | RMSE: 2429 | MAE: 1451 | Bias: 259.7

[C10|F2] Processing fold...
  > [TRAIN] R2: 0.9321 | RMSE: 2538 | MAE: 1349 | Bias: 283.7
  > [VAL]   R2: 0.9206 | RMSE: 2741 | MAE: 1466 | Bias: 324.2

[C10|F3] Processing fold...
  > [TRAIN] R2: 0.9355 | RMSE: 2453 | MAE: 1341 | Bias: 281.0
  > [VAL]   R2: 0.9014 | RMSE: 3155 | MAE: 1487 | Bias: 339.5

[C10|F4] Processing fold...
  > [TRAIN] R2: 0.9339 | RMSE: 2496 | MAE: 1349 | Bias: 282.2
  > [VAL]   R2: 0.9195 | RMSE: 2793 | MAE: 1455 | Bias: 325.3

[C10|F5] Processing fold...
  > [TRAIN] R2: 0.9332 | RMSE: 2531 | MAE: 1352 | Bias: 284.6
  > [VAL]   R2: 0.9305 | RMSE: 2507 | MAE: 1430 | Bias: 267.8

Config 10 SUMMARY:
  Selected features (avg): 12 / 15 (after encoding)
  [TRAIN AVG] MAE: 1347.9 | R2: 0.9336 | Bias: 283.0
  [VAL AVG]   MAE: 1457.9 | R2: 0.9214 | Bias: 303.3 | RMSE: 2724.9

######## CONFIG 11/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 1, 'tree_max_depth': 20, 'n_estimators': 400, 'max_samples': 0.5, 'max_features': 0.6}

[C11|F1] Processing fold...
  > Features before FS (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > Selected features (12/15) with FS_KEEP_RATIO=0.80
  > [TRAIN] R2: 0.9438 | RMSE: 2320 | MAE: 1261 | Bias: 349.1
  > [VAL]   R2: 0.9347 | RMSE: 2439 | MAE: 1463 | Bias: 359.8

[C11|F2] Processing fold...
  > [TRAIN] R2: 0.9437 | RMSE: 2311 | MAE: 1258 | Bias: 348.7
  > [VAL]   R2: 0.9236 | RMSE: 2689 | MAE: 1485 | Bias: 416.7

[C11|F3] Processing fold...
  > [TRAIN] R2: 0.9465 | RMSE: 2233 | MAE: 1253 | Bias: 344.6
  > [VAL]   R2: 0.9036 | RMSE: 3119 | MAE: 1502 | Bias: 425.9

[C11|F4] Processing fold...
  > [TRAIN] R2: 0.9446 | RMSE: 2285 | MAE: 1259 | Bias: 346.0
  > [VAL]   R2: 0.9211 | RMSE: 2764 | MAE: 1469 | Bias: 415.6

[C11|F5] Processing fold...
  > [TRAIN] R2: 0.9435 | RMSE: 2328 | MAE: 1263 | Bias: 350.4
  > [VAL]   R2: 0.9324 | RMSE: 2472 | MAE: 1439 | Bias: 359.7

Config 11 SUMMARY:
  Selected features (avg): 12 / 15 (after encoding)
  [TRAIN AVG] MAE: 1258.8 | R2: 0.9444 | Bias: 347.8
  [VAL AVG]   MAE: 1471.7 | R2: 0.9231 | Bias: 395.5 | RMSE: 2696.7

######## CONFIG 12/15 ########
Parameters: {'tree_min_samples_split': 50, 'tree_min_samples_leaf': 5, 'tree_max_depth': 20, 'n_estimators': 400, 'max_samples': 0.5, 'max_features': 0.8}

[C12|F1] Processing fold...
  > Features before FS (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > Selected features (12/15) with FS_KEEP_RATIO=0.80
  > [TRAIN] R2: 0.9245 | RMSE: 2689 | MAE: 1431 | Bias: 303.4
  > [VAL]   R2: 0.9304 | RMSE: 2518 | MAE: 1504 | Bias: 272.3

[C12|F2] Processing fold...
  > [TRAIN] R2: 0.9232 | RMSE: 2698 | MAE: 1433 | Bias: 304.0
  > [VAL]   R2: 0.9133 | RMSE: 2863 | MAE: 1522 | Bias: 341.9

[C12|F3] Processing fold...
  > [TRAIN] R2: 0.9267 | RMSE: 2616 | MAE: 1424 | Bias: 301.0
  > [VAL]   R2: 0.8949 | RMSE: 3258 | MAE: 1543 | Bias: 359.0

[C12|F4] Processing fold...
  > [TRAIN] R2: 0.9251 | RMSE: 2658 | MAE: 1433 | Bias: 301.8
  > [VAL]   R2: 0.9116 | RMSE: 2926 | MAE: 1515 | Bias: 344.5

[C12|F5] Processing fold...
  > [TRAIN] R2: 0.9244 | RMSE: 2692 | MAE: 1435 | Bias: 304.6
  > [VAL]   R2: 0.9242 | RMSE: 2619 | MAE: 1486 | Bias: 279.5

Config 12 SUMMARY:
  Selected features (avg): 12 / 15 (after encoding)
  [TRAIN AVG] MAE: 1430.9 | R2: 0.9248 | Bias: 303.0
  [VAL AVG]   MAE: 1514.0 | R2: 0.9149 | Bias: 319.4 | RMSE: 2836.9

######## CONFIG 13/15 ########
Parameters: {'tree_min_samples_split': 10, 'tree_min_samples_leaf': 5, 'tree_max_depth': 25, 'n_estimators': 1200, 'max_samples': 1.0, 'max_features': 0.9}

[C13|F1] Processing fold...
  > Features before FS (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > Selected features (12/15) with FS_KEEP_RATIO=0.80
  > [TRAIN] R2: 0.9592 | RMSE: 1977 | MAE: 1052 | Bias: 176.6
  > [VAL]   R2: 0.9473 | RMSE: 2190 | MAE: 1328 | Bias: 168.6

[C13|F2] Processing fold...
  > [TRAIN] R2: 0.9586 | RMSE: 1983 | MAE: 1051 | Bias: 176.9
  > [VAL]   R2: 0.9367 | RMSE: 2448 | MAE: 1338 | Bias: 234.6

[C13|F3] Processing fold...
  > [TRAIN] R2: 0.9617 | RMSE: 1890 | MAE: 1046 | Bias: 174.6
  > [VAL]   R2: 0.9182 | RMSE: 2873 | MAE: 1359 | Bias: 240.4

[C13|F4] Processing fold...
  > [TRAIN] R2: 0.9593 | RMSE: 1959 | MAE: 1053 | Bias: 176.3
  > [VAL]   R2: 0.9382 | RMSE: 2447 | MAE: 1325 | Bias: 225.7

[C13|F5] Processing fold...
  > [TRAIN] R2: 0.9588 | RMSE: 1987 | MAE: 1056 | Bias: 177.7
  > [VAL]   R2: 0.9458 | RMSE: 2215 | MAE: 1298 | Bias: 183.2

Config 13 SUMMARY:
  Selected features (avg): 12 / 15 (after encoding)
  [TRAIN AVG] MAE: 1051.6 | R2: 0.9595 | Bias: 176.4
  [VAL AVG]   MAE: 1329.4 | R2: 0.9372 | Bias: 210.5 | RMSE: 2434.5
[NEW BEST RMSE] Config 13

######## CONFIG 14/15 ########
Parameters: {'tree_min_samples_split': 30, 'tree_min_samples_leaf': 1, 'tree_max_depth': 15, 'n_estimators': 400, 'max_samples': 0.5, 'max_features': 0.9}

[C14|F1] Processing fold...
  > Features before FS (15): ['mileage', 'engineSize', 'tax', 'mpg', 'age', 'Brand', 'model', 'transmission_AUTOMATIC', 'transmission_MANUAL', 'transmission_SEMIAUTO', 'fuelType_DIESEL', 'fuelType_ELECTRIC', 'fuelType_HYBRID', 'fuelType_OTHER', 'fuelType_PETROL']
  > Selected features (12/15) with FS_KEEP_RATIO=0.80
  > [TRAIN] R2: 0.9408 | RMSE: 2380 | MAE: 1314 | Bias: 232.6
  > [VAL]   R2: 0.9394 | RMSE: 2349 | MAE: 1432 | Bias: 210.8

[C14|F2] Processing fold...

,config_id,val_rmse,val_mae,val_r2,val_bias,train_mae,train_r2,train_bias,avg_selected_features,n_estimators,max_samples,max_features,tree_max_depth,tree_min_samples_leaf,tree_min_samples_split
12,13,2434.492815,1329.417597,0.937246,210.481213,1051.567363,0.959514,176.429237,12.0,1200,1.0,0.9,25,5,10
7,8,2452.024414,1343.543170,0.936366,258.585076,1102.817806,0.957370,220.947615,12.0,1200,0.5,0.8,20,1,10
1,2,2510.758177,1370.679067,0.933286,262.598252,1175.983599,0.951901,230.661927,12.0,400,1.0,0.8,25,1,30
13,14,2611.373545,1434.997559,0.927861,251.047015,1312.317081,0.941599,231.352549,12.0,400,0.5,0.9,15,1,30
0,1,2614.429830,1404.051318,0.927665,234.703248,1233.966850,0.943563,211.635150,12.0,400,1.0,0.9,20,10,10

Best Config found:
{'tree_min_samples_split': 10, 'tree_min_samples_leaf': 5, 'tree_max_depth': 25, 'n_estimators': 1200, 'max_samples': 1.0, 'max_features': 0.9}

## 4. Final Model: Selected Configuration and Submission File <a id="finalconfig"></a>

final model e kaggle submission

visualização e considerações finais